/*
 * Copyright © 2021-present Arcade Data Ltd (info@arcadedata.com)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * SPDX-FileCopyrightText: 2021-present Arcade Data Ltd (info@arcadedata.com)
 * SPDX-License-Identifier: Apache-2.0
 */
package com.arcadedb.mongo;

import com.arcadedb.GlobalConfiguration;
import com.arcadedb.server.BaseGraphServerTest;
import com.mongodb.MongoClient;
import com.mongodb.MongoClientOptions;
import com.mongodb.MongoCredential;
import com.mongodb.ServerAddress;
import com.mongodb.client.MongoCollection;
import com.mongodb.client.result.DeleteResult;
import com.mongodb.client.result.UpdateResult;
import org.bson.Document;
import org.bson.types.ObjectId;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.List;

import static com.mongodb.client.model.Filters.eq;
import static org.assertj.core.api.Assertions.assertThat;

/**
 * Regression test for issue #6745: a filter referencing an {@code ObjectId _id} never matched, because the value
 * was stored as a bare hex string but bound into the query as the {@code ObjectId} object itself, whose
 * {@code toString()} does not equal the stored text. {@code findOne}/{@code updateOne}/{@code deleteOne} by
 * {@code _id} - the most common Mongo operations - silently found nothing.
 */
public class MongoDBObjectIdFilterTest extends BaseGraphServerTest {

  private static final int                       DEF_PORT = 27017;
  private              MongoClient               client;
  private              MongoCollection<Document> collection;

  @Override
  public void setTestConfiguration() {
    super.setTestConfiguration();
    GlobalConfiguration.SERVER_PLUGINS.setValue("MongoDB:com.arcadedb.mongo.MongoDBProtocolPlugin");
  }

  @BeforeEach
  @Override
  public void beginTest() {
    super.beginTest();
    getDatabase(0);
    client = new MongoClient(new ServerAddress("localhost", DEF_PORT),
        MongoCredential.createPlainCredential("root", getDatabaseName(), DEFAULT_PASSWORD_FOR_TESTS.toCharArray()),
        MongoClientOptions.builder().serverSelectionTimeout(5000).build());
    client.getDatabase(getDatabaseName()).createCollection("doc");
    collection = client.getDatabase(getDatabaseName()).getCollection("doc");
  }

  @AfterEach
  @Override
  public void endTest() {
    GlobalConfiguration.SERVER_PLUGINS.setValue("");
    if (client != null)
      client.close();
    super.endTest();
  }

  @Test
  void findOneByAutoGeneratedIdReturnsTheDocument() {
    collection.insertOne(new Document("name", "target"));
    final ObjectId id = collection.find(eq("name", "target")).first().getObjectId("_id");

    final Document found = collection.find(eq("_id", id)).first();

    assertThat(found).isNotNull();
    assertThat(found.getString("name")).isEqualTo("target");
  }

  /**
   * Follow-up to #6745, flagged by review on PR #6767: {@code buildCollection} bound {@code $in}/{@code $nin}
   * collections without normalizing an {@code ObjectId} element, so {@code $in} on {@code _id} kept missing its
   * document even after the scalar (equality) case was fixed.
   */
  @Test
  void findManyByIdUsingInFilterMatchesEveryListedId() {
    collection.insertOne(new Document("name", "a"));
    collection.insertOne(new Document("name", "b"));
    collection.insertOne(new Document("name", "c"));
    final ObjectId idA = collection.find(eq("name", "a")).first().getObjectId("_id");
    final ObjectId idB = collection.find(eq("name", "b")).first().getObjectId("_id");

    final List<Document> found = collection.find(new Document("_id", new Document("$in", List.of(idA, idB))))
        .into(new ArrayList<>());

    assertThat(found).extracting(d -> d.getString("name")).containsExactlyInAnyOrder("a", "b");
  }

  @Test
  void updateOneByIdModifiesTheMatchedDocument() {
    collection.insertOne(new Document("name", "target").append("counter", 1));
    final ObjectId id = collection.find(eq("name", "target")).first().getObjectId("_id");

    final UpdateResult result = collection.updateOne(eq("_id", id), new Document("$set", new Document("counter", 2)));

    assertThat(result.getModifiedCount()).isEqualTo(1);
    assertThat(collection.find(eq("_id", id)).first().getInteger("counter")).isEqualTo(2);
  }

  @Test
  void deleteOneByIdRemovesTheMatchedDocument() {
    collection.insertOne(new Document("name", "target"));
    final ObjectId id = collection.find(eq("name", "target")).first().getObjectId("_id");

    final DeleteResult result = collection.deleteOne(eq("_id", id));

    assertThat(result.getDeletedCount()).isEqualTo(1);
    assertThat(collection.find(eq("_id", id)).first()).isNull();
  }
}
