/* Generated by: JJTree: Do not edit this line. Directive.java Version 1.1 */
/* ParserGeneratorCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.arcadedb.graphql.parser;

public class Directive extends SimpleNode {

  protected Name      name;
  protected Arguments arguments;

  public Directive(int id) {
    super(id);
  }

  public Directive(GraphQLParser p, int id) {
    super(p, id);
  }

  /**
   * Accept the visitor.
   **/
  public Object jjtAccept(GraphQLParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }

  public String getName() {
    return name != null ? name.value : null;
  }

  public Arguments getArguments() {
    return arguments;
  }
}
/* ParserGeneratorCC - OriginalChecksum=2ab2407d8f843d5e31ff6480a48183d5 (do not edit this line) */
