/*
 * Copyright © 2021-present Arcade Data Ltd (info@arcadedata.com)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * SPDX-FileCopyrightText: 2021-present Arcade Data Ltd (info@arcadedata.com)
 * SPDX-License-Identifier: Apache-2.0
 */
/* Generated by: ParserGeneratorCC: Do not edit this line. GraphQLParserDefaultVisitor.java Version 1.1.3 */
package com.arcadedb.graphql.parser;

public class GraphQLParserDefaultVisitor implements GraphQLParserVisitor{
  public Object defaultVisit(final SimpleNode node, final Object data){

    return data;
  }
  public Object visit(final SimpleNode node, final Object data){
    return defaultVisit(node, data);
  }
  public Object visit(final Document node, final Object data){
    return defaultVisit(node, data);
  }
  public Object visit(final Definition node, final Object data){
    return defaultVisit(node, data);
  }
  public Object visit(final OperationDefinition node, final Object data){
    return defaultVisit(node, data);
  }
  public Object visit(final VariableDefinitions node, final Object data){
    return defaultVisit(node, data);
  }
  public Object visit(final VariableDefinition node, final Object data){
    return defaultVisit(node, data);
  }
  public Object visit(final VariableLiteral node, final Object data){
    return defaultVisit(node, data);
  }
  public Object visit(final DefaultValue node, final Object data){
    return defaultVisit(node, data);
  }
  public Object visit(final SelectionSet node, final Object data){
    return defaultVisit(node, data);
  }
  public Object visit(final Selection node, final Object data){
    return defaultVisit(node, data);
  }
  public Object visit(final Field node, final Object data){
    return defaultVisit(node, data);
  }
  public Object visit(final FieldWithAlias node, final Object data){
    return defaultVisit(node, data);
  }
  public Object visit(final Arguments node, final Object data){
    return defaultVisit(node, data);
  }
  public Object visit(final Argument node, final Object data){
    return defaultVisit(node, data);
  }
  public Object visit(final FragmentSpread node, final Object data){
    return defaultVisit(node, data);
  }
  public Object visit(final InlineFragment node, final Object data){
    return defaultVisit(node, data);
  }
  public Object visit(final FragmentDefinition node, final Object data){
    return defaultVisit(node, data);
  }
  public Object visit(final FragmentName node, final Object data){
    return defaultVisit(node, data);
  }
  public Object visit(final TypeCondition node, final Object data){
    return defaultVisit(node, data);
  }
  public Object visit(final Name node, final Object data){
    return defaultVisit(node, data);
  }
  public Object visit(final Value node, final Object data){
    return defaultVisit(node, data);
  }
  public Object visit(final ValueWithVariable node, final Object data){
    return defaultVisit(node, data);
  }
  public Object visit(final EnumValue node, final Object data){
    return defaultVisit(node, data);
  }
  public Object visit(final ListValue node, final Object data){
    return defaultVisit(node, data);
  }
  public Object visit(final ListValueWithVariable node, final Object data){
    return defaultVisit(node, data);
  }
  public Object visit(final ObjectValue node, final Object data){
    return defaultVisit(node, data);
  }
  public Object visit(final ObjectValueWithVariable node, final Object data){
    return defaultVisit(node, data);
  }
  public Object visit(final ObjectField node, final Object data){
    return defaultVisit(node, data);
  }
  public Object visit(final ObjectFieldWithValue node, final Object data){
    return defaultVisit(node, data);
  }
  public Object visit(final Directives node, final Object data){
    return defaultVisit(node, data);
  }
  public Object visit(final Directive node, final Object data){
    return defaultVisit(node, data);
  }
  public Object visit(final Type node, final Object data){
    return defaultVisit(node, data);
  }
  public Object visit(final TypeName node, final Object data){
    return defaultVisit(node, data);
  }
  public Object visit(final ListType node, final Object data){
    return defaultVisit(node, data);
  }
  public Object visit(final TypeSystemDefinition node, final Object data){
    return defaultVisit(node, data);
  }
  public Object visit(final SchemaDefinition node, final Object data){
    return defaultVisit(node, data);
  }
  public Object visit(final OperationTypeDefinition node, final Object data){
    return defaultVisit(node, data);
  }
  public Object visit(final TypeDefinition node, final Object data){
    return defaultVisit(node, data);
  }
  public Object visit(final ScalarTypeDefinition node, final Object data){
    return defaultVisit(node, data);
  }
  public Object visit(final ObjectTypeDefinition node, final Object data){
    return defaultVisit(node, data);
  }
  public Object visit(final ImplementsInterface node, final Object data){
    return defaultVisit(node, data);
  }
  public Object visit(final FieldDefinition node, final Object data){
    return defaultVisit(node, data);
  }
  public Object visit(final ArgumentsDefinition node, final Object data){
    return defaultVisit(node, data);
  }
  public Object visit(final InputValueDefinition node, final Object data){
    return defaultVisit(node, data);
  }
  public Object visit(final InterfaceTypeDefinition node, final Object data){
    return defaultVisit(node, data);
  }
  public Object visit(final UnionTypeDefinition node, final Object data){
    return defaultVisit(node, data);
  }
  public Object visit(final UnionMembers node, final Object data){
    return defaultVisit(node, data);
  }
  public Object visit(final EnumTypeDefinition node, final Object data){
    return defaultVisit(node, data);
  }
  public Object visit(final EnumValueDefinition node, final Object data){
    return defaultVisit(node, data);
  }
  public Object visit(final InputObjectTypeDefinition node, final Object data){
    return defaultVisit(node, data);
  }
  public Object visit(final TypeExtensionDefinition node, final Object data){
    return defaultVisit(node, data);
  }
  public Object visit(final DirectiveDefinition node, final Object data){
    return defaultVisit(node, data);
  }
  public Object visit(final DirectiveLocation node, final Object data){
    return defaultVisit(node, data);
  }
  public Object visit(final DirectiveLocations node, final Object data){
    return defaultVisit(node, data);
  }
  public Object visit(final BooleanValue node, final Object data){
    return defaultVisit(node, data);
  }
  public Object visit(final IntValue node, final Object data){
    return defaultVisit(node, data);
  }
  public Object visit(final FloatValue node, final Object data){
    return defaultVisit(node, data);
  }
  public Object visit(final StringValue node, final Object data){
    return defaultVisit(node, data);
  }
  public Object visit(final OperationType node, final Object data){
    return defaultVisit(node, data);
  }
}
/* ParserGeneratorCC - OriginalChecksum=e10e47b71ae8418b0a539838c2422255 (do not edit this line) */
