/*
 * Copyright © 2021-present Arcade Data Ltd (info@arcadedata.com)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * SPDX-FileCopyrightText: 2021-present Arcade Data Ltd (info@arcadedata.com)
 * SPDX-License-Identifier: Apache-2.0
 */
/* Generated by: ParserGeneratorCC: Do not edit this line. GraphQLParserTreeConstants.java Version 1.1.3 */
package com.arcadedb.graphql.parser;

public interface GraphQLParserTreeConstants
{
  public int JJTDOCUMENT = 0;
  public int JJTDEFINITION = 1;
  public int JJTOPERATIONDEFINITION = 2;
  public int JJTVARIABLEDEFINITIONS = 3;
  public int JJTVARIABLEDEFINITION = 4;
  public int JJTVARIABLELITERAL = 5;
  public int JJTDEFAULTVALUE = 6;
  public int JJTSELECTIONSET = 7;
  public int JJTSELECTION = 8;
  public int JJTFIELD = 9;
  public int JJTFIELDWITHALIAS = 10;
  public int JJTARGUMENTS = 11;
  public int JJTARGUMENT = 12;
  public int JJTFRAGMENTSPREAD = 13;
  public int JJTINLINEFRAGMENT = 14;
  public int JJTFRAGMENTDEFINITION = 15;
  public int JJTFRAGMENTNAME = 16;
  public int JJTTYPECONDITION = 17;
  public int JJTNAME = 18;
  public int JJTVALUE = 19;
  public int JJTVALUEWITHVARIABLE = 20;
  public int JJTENUMVALUE = 21;
  public int JJTLISTVALUE = 22;
  public int JJTLISTVALUEWITHVARIABLE = 23;
  public int JJTOBJECTVALUE = 24;
  public int JJTOBJECTVALUEWITHVARIABLE = 25;
  public int JJTOBJECTFIELD = 26;
  public int JJTOBJECTFIELDWITHVALUE = 27;
  public int JJTDIRECTIVES = 28;
  public int JJTDIRECTIVE = 29;
  public int JJTTYPE = 30;
  public int JJTTYPENAME = 31;
  public int JJTLISTTYPE = 32;
  public int JJTTYPESYSTEMDEFINITION = 33;
  public int JJTSCHEMADEFINITION = 34;
  public int JJTOPERATIONTYPEDEFINITION = 35;
  public int JJTTYPEDEFINITION = 36;
  public int JJTSCALARTYPEDEFINITION = 37;
  public int JJTOBJECTTYPEDEFINITION = 38;
  public int JJTIMPLEMENTSINTERFACE = 39;
  public int JJTFIELDDEFINITION = 40;
  public int JJTARGUMENTSDEFINITION = 41;
  public int JJTINPUTVALUEDEFINITION = 42;
  public int JJTINTERFACETYPEDEFINITION = 43;
  public int JJTUNIONTYPEDEFINITION = 44;
  public int JJTUNIONMEMBERS = 45;
  public int JJTENUMTYPEDEFINITION = 46;
  public int JJTENUMVALUEDEFINITION = 47;
  public int JJTINPUTOBJECTTYPEDEFINITION = 48;
  public int JJTTYPEEXTENSIONDEFINITION = 49;
  public int JJTDIRECTIVEDEFINITION = 50;
  public int JJTDIRECTIVELOCATION = 51;
  public int JJTDIRECTIVELOCATIONS = 52;
  public int JJTBOOLEANVALUE = 53;
  public int JJTINTVALUE = 54;
  public int JJTFLOATVALUE = 55;
  public int JJTSTRINGVALUE = 56;
  public int JJTOPERATIONTYPE = 57;


  public String[] jjtNodeName = {
    "Document",
    "Definition",
    "OperationDefinition",
    "VariableDefinitions",
    "VariableDefinition",
    "VariableLiteral",
    "DefaultValue",
    "SelectionSet",
    "Selection",
    "Field",
    "FieldWithAlias",
    "Arguments",
    "Argument",
    "FragmentSpread",
    "InlineFragment",
    "FragmentDefinition",
    "FragmentName",
    "TypeCondition",
    "Name",
    "Value",
    "ValueWithVariable",
    "EnumValue",
    "ListValue",
    "ListValueWithVariable",
    "ObjectValue",
    "ObjectValueWithVariable",
    "ObjectField",
    "ObjectFieldWithValue",
    "Directives",
    "Directive",
    "Type",
    "TypeName",
    "ListType",
    "TypeSystemDefinition",
    "SchemaDefinition",
    "OperationTypeDefinition",
    "TypeDefinition",
    "ScalarTypeDefinition",
    "ObjectTypeDefinition",
    "ImplementsInterface",
    "FieldDefinition",
    "ArgumentsDefinition",
    "InputValueDefinition",
    "InterfaceTypeDefinition",
    "UnionTypeDefinition",
    "UnionMembers",
    "EnumTypeDefinition",
    "EnumValueDefinition",
    "InputObjectTypeDefinition",
    "TypeExtensionDefinition",
    "DirectiveDefinition",
    "DirectiveLocation",
    "DirectiveLocations",
    "BooleanValue",
    "IntValue",
    "FloatValue",
    "StringValue",
    "OperationType",
  };
}
/* ParserGeneratorCC - OriginalChecksum=c673b5503d07c59e3a8f207cbc07b97e (do not edit this line) */
