/* Generated by: JJTree: Do not edit this line. InterfaceTypeDefinition.java Version 1.1 */
/* ParserGeneratorCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.arcadedb.graphql.parser;

import java.util.ArrayList;
import java.util.List;

public class InterfaceTypeDefinition extends TypeDefinition {

  protected Name                  name;
  protected Directives            directives;
  protected List<FieldDefinition> fieldDefinitions = new ArrayList<>();

  public InterfaceTypeDefinition(int id) {
    super(id);
  }

  public InterfaceTypeDefinition(GraphQLParser p, int id) {
    super(p, id);
  }

  /**
   * Accept the visitor.
   **/
  public Object jjtAccept(GraphQLParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* ParserGeneratorCC - OriginalChecksum=f67913a71b0a0ce7fd7cf20494bf7fdd (do not edit this line) */
