/* Generated by: JJTree: Do not edit this line. ObjectTypeDefinition.java Version 1.1 */
/* ParserGeneratorCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.arcadedb.graphql.parser;

import java.util.ArrayList;
import java.util.List;

public class ObjectTypeDefinition extends TypeDefinition {

  protected Name                name;
  protected ImplementsInterface implementsInterface;
  protected Directives          directives;
  List<FieldDefinition> fieldDefinitions = new ArrayList<>();

  public ObjectTypeDefinition(int id) {
    super(id);
  }

  public ObjectTypeDefinition(GraphQLParser p, int id) {
    super(p, id);
  }

  /**
   * Accept the visitor.
   **/
  public Object jjtAccept(GraphQLParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* ParserGeneratorCC - OriginalChecksum=22e41e7403da6914e57ff609136bdc3e (do not edit this line) */
