version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: weekly
      day: "sunday"
    open-pull-requests-limit: 20

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
      day: "sunday"
    open-pull-requests-limit: 10

  - package-ecosystem: "docker"
    directory: "/package/src/main/docker/"
    schedule:
      interval: weekly
      day: "sunday"
    open-pull-requests-limit: 10

  - package-ecosystem: "npm"
    directory: "/e2e-js"
    schedule:
      interval: weekly
      day: "sunday"
    open-pull-requests-limit: 10

  - package-ecosystem: "python"
    directory: "/e2e-pythom"
    schedule:
      interval: weekly
      day: "sunday"
    open-pull-requests-limit: 10
