version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: weekly
      day: "sunday"
    open-pull-requests-limit: 20

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
      day: "sunday"
    open-pull-requests-limit: 10

  - package-ecosystem: "docker"
    directory: "/package/src/main/docker/"
    schedule:
      interval: weekly
      day: "sunday"
    open-pull-requests-limit: 10

  # Studio Frontend Dependencies (npm) - HIGH PRIORITY
  - package-ecosystem: "npm"
    directory: "/studio"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    open-pull-requests-limit: 15
    target-branch: "main"
    commit-message:
      prefix: "chore(studio-deps)"
      prefix-development: "chore(studio-deps-dev)"
      include: "scope"
    labels:
      - "dependencies"
      - "studio"
      - "security"
      - "frontend"
    # Group related updates together for easier review
    groups:
      # Critical security libraries - immediate attention
      security-critical:
        patterns:
          - "jquery"
          - "bootstrap"
          - "datatables.net*"
          - "sweetalert2"
        update-types:
          - "patch"
          - "minor"
          - "major"
      # Visualization and UI libraries
      ui-visualization:
        patterns:
          - "cytoscape*"
          - "apexcharts"
          - "codemirror"
          - "notyf"
          - "clipboard"
          - "@fortawesome/*"
        update-types:
          - "patch"
          - "minor"
      # Build and development tools
      build-tools:
        patterns:
          - "webpack*"
          - "*-loader"
          - "*-plugin"
          - "copy-webpack-plugin"
          - "css-loader"
          - "style-loader"
          - "file-loader"
          - "url-loader"
          - "html-webpack-plugin"
        update-types:
          - "patch"
          - "minor"
    # Security-focused update strategy
    allow:
      - dependency-type: "all"
    # Controlled major version updates for stability
    ignore:
      - dependency-name: "webpack"
        update-types: ["version-update:semver-major"]
      - dependency-name: "bootstrap"
        update-types: ["version-update:semver-major"]

  # E2E JavaScript Testing Dependencies
  - package-ecosystem: "npm"
    directory: "/e2e-js"
    schedule:
      interval: weekly
      day: "sunday"
    open-pull-requests-limit: 10

  # E2E Studio Testing Dependencies
  - package-ecosystem: "npm"
    directory: "/e2e-studio"
    schedule:
      interval: weekly
      day: "sunday"
    open-pull-requests-limit: 10

  # E2E Python Testing Dependencies
  - package-ecosystem: "uv"
    enable-beta-ecosystems: "true"
    directory: "/e2e-python"
    schedule:
      interval: weekly
      day: "sunday"
    open-pull-requests-limit: 10
