---
exclude_paths:
  - "**/static/**"
  - "**/*.js"
  - "**/*.css"
  - "**/*.html"
  - "**/*.zip"
  - "**/*.tgz"
  - "**/*.sh"
  - "**/*.bat"
  - "**/*.md"
  - "**/src/test/*"
  - "**/*Test.java"
  - "**/*IT.java"
  - "**/*CharStream.java"
  - "**/SqlParser*.java"
  - "**/GraphQLParser*.java"
  - "**/ParseException*.java"
  - "**/TokenMgrException.java"
  - "**/TokenMgrError.java"
