---
exclude_paths:
  - "**/static/**"
  - "**/*.js"
  - "**/*.css"
  - "**/*.html"
  - "**/*.zip"
  - "**/*.tgz"
  - "**/*.sh"
  - "**/*.bat"
  - "**/*.md"
  - "**/src/test/*"
  - "**/*Test.java"
  - "**/*IT.java"
