version: "3.9"
services:
    arcade:
        image: arcadedata/arcadedb:latest
        ports:
            - 2480:2480  # host : container port
            - 2424:2424  # host : container port            
        environment:
            JAVA_OPTS: >
                -Darcadedb.server.rootPassword=playwithdata 
                -Darcadedb.dumpConfigAtStartup=true
                -Darcadedb.server.defaultDatabases=Imported[root]{import:https://github.com/ArcadeData/arcadedb-datasets/raw/main/orientdb/OpenBeer.gz}
        restart: always
volumes:
    arcade_db_vol:

networks:
    default:
