/*
 * Copyright © 2021-present Arcade Data Ltd (info@arcadedata.com)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * SPDX-FileCopyrightText: 2021-present Arcade Data Ltd (info@arcadedata.com)
 * SPDX-License-Identifier: Apache-2.0
 */
package com.arcadedb.index.sparsevector;

import com.arcadedb.database.RID;

/**
 * Typed marker for a single sparse-vector posting carried through the transaction commit replay
 * pipeline. Wraps the {@code (dim, rid, weight)} tuple that {@link LSMSparseVectorIndex} queues
 * onto {@code TransactionContext.addIndexOperation} so the wrapper's {@code put}/{@code remove}
 * overrides can identify a replay frame via {@code instanceof} instead of sniffing the shape
 * of the {@code Object[]} keys.
 * <p>
 * Implements {@link Comparable} so that
 * {@link com.arcadedb.database.TransactionIndexContext.ComparableKey#compareTo} can order
 * dedup-map entries (it routes through {@code BinaryComparator.compareTo}, which falls back to
 * {@code Comparable}). {@code equals} / {@code hashCode} are field-wise as auto-generated by the
 * record contract; this matches the prior 3-tuple shape's behavior in the dedup map (two puts on
 * the same {@code (dim, rid)} with different weights remain distinct entries).
 *
 * @author Luca Garulli (l.garulli@arcadedata.com)
 */
public record SparsePostingReplayKey(int dim, RID rid, float weight)
    implements Comparable<SparsePostingReplayKey> {

  @Override
  public int compareTo(final SparsePostingReplayKey o) {
    int c = Integer.compare(dim, o.dim);
    if (c != 0)
      return c;
    c = rid.compareTo(o.rid);
    if (c != 0)
      return c;
    return Float.compare(weight, o.weight);
  }
}
