/*
 * Copyright © 2021-present Arcade Data Ltd (info@arcadedata.com)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * SPDX-FileCopyrightText: 2021-present Arcade Data Ltd (info@arcadedata.com)
 * SPDX-License-Identifier: Apache-2.0
 */
package com.arcadedb.graphql.schema;

import com.arcadedb.database.Database;
import com.arcadedb.exception.CommandExecutionException;
import com.arcadedb.exception.CommandParsingException;
import com.arcadedb.graphql.parser.AbstractValue;
import com.arcadedb.graphql.parser.Argument;
import com.arcadedb.graphql.parser.Arguments;
import com.arcadedb.graphql.parser.Definition;
import com.arcadedb.graphql.parser.Directive;
import com.arcadedb.graphql.parser.Directives;
import com.arcadedb.graphql.parser.Document;
import com.arcadedb.graphql.parser.Field;
import com.arcadedb.graphql.parser.FieldDefinition;
import com.arcadedb.graphql.parser.FieldWithAlias;
import com.arcadedb.graphql.parser.GraphQLParser;
import com.arcadedb.graphql.parser.InputValueDefinition;
import com.arcadedb.graphql.parser.ObjectTypeDefinition;
import com.arcadedb.graphql.parser.OperationDefinition;
import com.arcadedb.graphql.parser.ParseException;
import com.arcadedb.graphql.parser.Selection;
import com.arcadedb.graphql.parser.SelectionSet;
import com.arcadedb.graphql.parser.TypeDefinition;
import com.arcadedb.graphql.parser.TypeName;
import com.arcadedb.graphql.parser.TypeSystemDefinition;
import com.arcadedb.graphql.parser.ValueWithVariable;
import com.arcadedb.graphql.parser.VariableDefinition;
import com.arcadedb.graphql.parser.VariableDefinitions;
import com.arcadedb.graphql.parser.VariableLiteral;
import com.arcadedb.query.sql.executor.InternalResultSet;
import com.arcadedb.query.sql.executor.ResultInternal;
import com.arcadedb.query.sql.executor.ResultSet;
import com.arcadedb.schema.DocumentType;
import com.arcadedb.schema.Property;
import com.arcadedb.schema.Type;

import java.math.BigInteger;
import java.util.*;

public class GraphQLSchema {
  /**
   * Prefix of the SQL parameter names generated by {@link #buildWhereClause}. The free-form {@code where} argument
   * is interpolated verbatim and could name a parameter of its own, so rather than rely on this prefix being an
   * unlikely choice, a predicate that uses it at all is rejected: the reservation is enforced, not hoped for.
   */
  private static final String BOUND_PARAMETER_PREFIX = "__gqlArg";

  private final Database                          database;
  private final Map<String, ObjectTypeDefinition> objectTypeDefinitionMap = new HashMap<>();
  private ObjectTypeDefinition              queryDefinition;

  public GraphQLSchema(final Database database) {
    this.database = database;
  }

  public ResultSet execute(final String query) throws ParseException {
    return execute(query, null);
  }

  /**
   * Executes a GraphQL document, binding the operation's variables from {@code parameters}. See issue #6834: before,
   * the parameters were dropped and every {@code $variable} resolved to {@code null}.
   */
  public ResultSet execute(final String query, final Map<String, Object> parameters) throws ParseException {
    final Document ast = GraphQLParser.parse(query);

    final List<Definition> definitions = ast.getDefinitions();
    if (!definitions.isEmpty()) {
      for (final Definition definition : definitions) {
        if (definition instanceof TypeSystemDefinition typeSystemDefinition) {

          final TypeDefinition type = typeSystemDefinition.getTypeDefinition();
          if (type instanceof ObjectTypeDefinition obj) {
            objectTypeDefinitionMap.put(obj.getName(), obj);

            if ("Query".equals(obj.getName()))
              // SPECIAL TYPE QUERY
              queryDefinition = obj;
          }

        } else if (definition instanceof OperationDefinition operationDefinition) {
          final OperationDefinition op = operationDefinition;
          if (op.isQuery()) {
            return executeQuery(op, parameters);
          } else
            throw new UnsupportedOperationException("GraphQL mutations not supported yet");
        }
      }
    }

    return new InternalResultSet();
  }

  private ResultSet executeQuery(final OperationDefinition op, final Map<String, Object> parameters) {
    String from = null;

    SelectionSet projection = null;
    ObjectTypeDefinition returnType = null;
    FieldDefinition typeDefinition = null;
    final Set<String> typeArgumentNames = new HashSet<>();

    if (op.getSelectionSet().getSelections().size() > 1)
      throw new CommandParsingException("Error on executing multiple queries");

    String queryName = null;

    try {
      final Map<String, Object> variables = resolveVariables(op, parameters);

      final Selection selection = op.getSelectionSet().getSelections().getFirst();
      final FieldWithAlias aliasField = selection.getFieldWithAlias();
      queryName = aliasField != null ? aliasField.getName() : selection.getName();

      // HANDLE INTROSPECTION QUERIES
      if ("__schema".equals(queryName))
        return executeIntrospectionSchema(selection);
      else if ("__type".equals(queryName))
        return executeIntrospectionType(selection, variables);
      else if ("__typename".equals(queryName))
        return executeIntrospectionTypename();
      if (queryDefinition != null) {
        for (final FieldDefinition f : queryDefinition.getFieldDefinitions()) {
          if (queryName.equals(f.getName())) {
            typeDefinition = f;
            returnType = getTypeFromField(f);
            // THE ARGUMENTS DEFINITION IS OPTIONAL IN THE GRAMMAR: A FIELD DECLARED WITHOUT A PARAMETER LIST
            // (E.G. `allBooks: [Book]`) LEAVES IT NULL. SEE ISSUE #6835
            if (f.getArgumentsDefinition() != null)
              for (final InputValueDefinition d : f.getArgumentsDefinition().getInputValueDefinitions())
                typeArgumentNames.add(d.getName().getValue());
            if (returnType != null)
              from = returnType.getName();
          }
        }
      }

      if (from == null)
        throw new CommandParsingException("Target type not defined for GraphQL query '" + queryName + "'");

      if (typeDefinition != null) {
        final Directives directives = typeDefinition.getDirectives();
        if (directives != null) {
          for (final Directive directive : directives.getDirectives()) {
            final String directiveName = directive.getName();

            // TODO: REFACTOR THIS IN MULTIPLE PLUGGABLE CLASSES
            if ("sql".equals(directiveName) ||
                "gremlin".equals(directiveName) ||
                "cypher".equals(directiveName))
              return parseNativeQueryDirective(directiveName, directive, selection, returnType, variables);
          }
        }
      }

      final Field field = selection.getField();
      final Arguments queryArguments = field != null ? field.getArguments() : aliasField != null ? aliasField.getArguments() : null;
      projection = field != null ? field.getSelectionSet() : aliasField != null ? aliasField.getSelectionSet() : null;

      final Map<String, Object> boundParameters = new HashMap<>();
      final String where = buildWhereClause(queryArguments, typeArgumentNames, variables, boundParameters);

      String query = "select from " + from;
      if (!where.isEmpty())
        query += " where " + where;

      final ResultSet resultSet =
          boundParameters.isEmpty() ? database.query("sql", query) : database.query("sql", query, boundParameters);

      return new GraphQLResultSet(this, resultSet, projection != null ? projection.getSelections() : null, returnType,
          variables);

    } catch (final CommandParsingException | CommandExecutionException e) {
      // An execution failure raised by the statement this query delegates to keeps the classification the engine
      // gave it. Rewrapping it as a parsing exception reported a runtime error - an arithmetic error, or the
      // NoSuchElementException #5219 covers - as a malformed document. See issue #5628.
      //
      // Deliberately narrower than ArcadeDBException: SchemaException is NOT passed through. It would reach the
      // HTTP handler, which has no arm for it, as a 500 - and the class is not purely a caller error (Dictionary
      // and TransactionManager raise it for genuine server faults, e.g. issue #4122), so it cannot simply be
      // mapped to 400 either. Tracked as a follow-up rather than decided here.
      throw e;
    } catch (final Exception e) {
      if (queryName != null)
        throw new CommandParsingException("Error on executing GraphQL query '" + queryName + "'", e);
      throw new CommandParsingException("Error on executing GraphQL query", e);
    }

  }

  /**
   * Builds a SQL {@code where} clause from a GraphQL field's arguments, shared by both the plain-field and
   * aliased-field dispatch paths so they cannot drift apart the way they did before (issue #6453).
   * <p>
   * Argument values are never written into the statement text: each one is bound as a named SQL parameter added to
   * {@code boundParameters}. Quoting them by hand made the correctness of any value carrying a quote or a backslash
   * depend on the SQL string-literal rules happening to match the GraphQL ones (issue #6836).
   * <p>
   * The one exception is the reserved {@code where} argument, which is a free-form SQL predicate by design and is
   * therefore still interpolated verbatim. Whatever is written there is SQL and has to be trusted the same way a
   * hand-written statement is - which is why it cannot be filled from a variable: an application that treats its
   * GraphQL document as trusted and its variables as untrusted input would otherwise be handing a caller raw SQL
   * without meaning to. Variables never resolved before issue #6834, so nothing can depend on that combination; a
   * predicate that genuinely has to vary at runtime belongs in a {@code @sql} directive with a bound parameter.
   */
  private String buildWhereClause(final Arguments queryArguments, final Set<String> typeArgumentNames,
      final Map<String, Object> variables, final Map<String, Object> boundParameters) {
    final StringBuilder where = new StringBuilder();

    if (queryArguments != null)
      for (final Argument queryArgument : queryArguments.getList()) {
        final String argName = queryArgument.getName();
        if (!typeArgumentNames.contains(argName))
          throw new CommandParsingException("Parameter '" + argName + "' not defined in query");

        final ValueWithVariable argument = queryArgument.getValueWithVariable();

        if ("where".equals(argName) && argument != null && argument.getValue() instanceof VariableLiteral variable)
          throw new CommandParsingException("The reserved 'where' argument is interpolated into the statement verbatim, "
              + "so it cannot be filled from the variable '$" + variable.getName()
              + "': use a @sql directive with a bound parameter for a predicate that has to vary at runtime");

        final Object argValue = resolveValue(argument, variables);

        if (!where.isEmpty())
          where.append(" and ");

        if ("where".equals(argName)) {
          final String predicate = String.valueOf(argValue);
          if (predicate.contains(BOUND_PARAMETER_PREFIX))
            throw new CommandParsingException("The 'where' predicate cannot name a parameter starting with '"
                + BOUND_PARAMETER_PREFIX + "': that prefix is reserved for the parameters bound for the other arguments");
          where.append(predicate);
        } else {
          final String parameterName = BOUND_PARAMETER_PREFIX + boundParameters.size();
          boundParameters.put(parameterName, argValue);
          where.append(argName).append(" = :").append(parameterName);
        }
      }

    return where.toString();
  }

  /**
   * Coerces the variable values of an operation: a value supplied by the caller wins, otherwise the declared default
   * value is used, otherwise the variable is null - and a variable declared non-null without any of the two is an
   * error. The returned map contains exactly the declared variables, so {@link #resolveValue} can tell a variable
   * that resolves to null from one that was never declared. See issue #6834.
   */
  private static Map<String, Object> resolveVariables(final OperationDefinition op, final Map<String, Object> parameters) {
    final VariableDefinitions definitions = op.getVariableDefinitions();
    if (definitions == null || definitions.getVariableDefinitions().isEmpty())
      return Collections.emptyMap();

    final Map<String, Object> variables = new HashMap<>(definitions.getVariableDefinitions().size());
    for (final VariableDefinition definition : definitions.getVariableDefinitions()) {
      final VariableLiteral literal = definition.getVariableLiteral();
      if (literal == null)
        continue;

      final String name = literal.getName();
      final boolean nonNull = definition.getType() != null && definition.getType().isBang();

      if (parameters != null && parameters.containsKey(name)) {
        final Object parameterValue = parameters.get(name);
        // A NON-NULL VARIABLE IS NOT SATISFIED BY A KEY THAT IS PRESENT WITH A NULL VALUE
        if (parameterValue == null && nonNull)
          throw new CommandParsingException("GraphQL variable '$" + name + "' is declared as non-null but null was passed");
        checkDeclaredType(name, definition, parameterValue, "passed");
        variables.put(name, parameterValue);
        continue;
      }

      if (definition.getDefaultValue() != null) {
        final AbstractValue defaultValue = definition.getDefaultValue().getValue().getValue();
        if (defaultValue == null)
          throw new CommandParsingException(
              "Default value of GraphQL variable '$" + name + "' is not a scalar: list and object default values are not supported");
        final Object value = defaultValue.getValue();
        checkDeclaredType(name, definition, value, "declared as its default");
        variables.put(name, value);
        continue;
      }

      if (nonNull)
        throw new CommandParsingException("GraphQL variable '$" + name + "' is declared as non-null but no value was passed");

      variables.put(name, null);
    }

    return variables;
  }

  /**
   * Rejects a variable value that the declared type cannot hold, so a mismatch is reported against the schema the
   * caller wrote rather than left to the SQL comparator to coerce - which it does today for a numeric string, but
   * not for every pairing, and a pairing it cannot coerce matches nothing without saying why.
   * <p>
   * Only the five built-in scalars are checked, with the coercion rules of the specification: {@code Int} takes
   * integral values in 32-bit range, {@code Float} takes any finite number (an integer input value is a valid
   * float, {@code NaN} and the infinities are not values the specification lets a Float carry),
   * {@code ID} takes a string or an integral value of any width - it is serialised as a string and carries no range
   * of its own, which is exactly why a schema uses it for a key too large for {@code Int}. Every other declared type name - a custom scalar such as the
   * {@code WHERE} used for the free-form predicate argument, an enum, an input object - is deliberately left
   * unchecked: this module does not model them, and rejecting what it cannot describe would be worse than passing
   * it through. A list type is skipped for the same reason.
   */
  private static void checkDeclaredType(final String name, final VariableDefinition definition, final Object value,
      final String origin) {
    if (value == null)
      return;

    final TypeName typeName = definition.getType() != null ? definition.getType().getTypeName() : null;
    if (typeName == null)
      return;

    final String declared = typeName.getName();
    final boolean valid = switch (declared) {
      case "Int" -> isInteger(value);
      case "Float" -> value instanceof Number && isFinite(value);
      case "Boolean" -> value instanceof Boolean;
      case "String" -> value instanceof String;
      case "ID" -> value instanceof String || isIntegral(value);
      default -> true;
    };

    if (!valid)
      throw new CommandParsingException(
          "GraphQL variable '$" + name + "' is declared as " + declared + " but a " + value.getClass().getSimpleName()
              + " value was " + origin);
  }

  /**
   * Whether the value is an integral number the 32-bit {@code Int} scalar can hold. The width has to be checked for
   * every type wide enough to exceed it, not only for {@code Long}: {@link BigInteger} carries no bound at all.
   */
  private static boolean isInteger(final Object value) {
    if (value instanceof Long l)
      return l == l.intValue();
    if (value instanceof BigInteger b)
      // bitLength() EXCLUDES THE SIGN BIT, SO A SIGNED 32-BIT VALUE IS EXACTLY ONE OF AT MOST 31 BITS
      return b.bitLength() < Integer.SIZE;
    return value instanceof Integer || value instanceof Short || value instanceof Byte;
  }

  /**
   * Whether the value is a finite number. {@code NaN} and the infinities are representable in Java but are not
   * values the {@code Float} scalar can carry.
   */
  private static boolean isFinite(final Object value) {
    if (value instanceof Double d)
      return !d.isNaN() && !d.isInfinite();
    if (value instanceof Float f)
      return !f.isNaN() && !f.isInfinite();
    return true;
  }

  /**
   * Whether the value is an integral number of any width. A floating-point value is not one even when it happens to
   * have no fractional part: the caller is checking what was passed, not what it could be rounded to.
   */
  private static boolean isIntegral(final Object value) {
    return value instanceof Integer || value instanceof Long || value instanceof Short || value instanceof Byte
        || value instanceof BigInteger;
  }

  /**
   * Resolves an argument value, substituting the operation's variable values for a {@code $variable} reference.
   */
  static Object resolveValue(final ValueWithVariable valueWithVariable, final Map<String, Object> variables) {
    final AbstractValue value = valueWithVariable != null ? valueWithVariable.getValue() : null;
    if (value instanceof VariableLiteral variable) {
      final String name = variable.getName();
      if (variables == null || !variables.containsKey(name))
        throw new CommandParsingException("GraphQL variable '$" + name + "' is not declared by the operation");
      return variables.get(name);
    }
    return value != null ? value.getValue() : null;
  }

  private GraphQLResultSet parseNativeQueryDirective(final String language, final Directive directive, final Selection selection,
      final ObjectTypeDefinition returnType, final Map<String, Object> variables) {
    if (directive.getArguments() == null)
      throw new CommandParsingException(language.toUpperCase(Locale.ENGLISH) + " directive has no `statement` argument");

    String statement = null;
    Map<String, Object> arguments = null;
    SelectionSet projection = null;

    final Field field = selection.getField();
    final FieldWithAlias aliasField = selection.getFieldWithAlias();

    for (final Argument argument : directive.getArguments().getList()) {
      if ("statement".equals(argument.getName())) {
        // THE DIRECTIVE IS PART OF THE SCHEMA, NOT OF THE OPERATION: NO VARIABLE CAN BE BOUND IN IT
        final Object statementValue = resolveValue(argument.getValueWithVariable(), null);
        statement = statementValue != null ? statementValue.toString() : null;

        if (field != null) {
          arguments = getArguments(field.getArguments(), variables);
          projection = field.getSelectionSet();
        } else if (aliasField != null) {
          arguments = getArguments(aliasField.getArguments(), variables);
          projection = aliasField.getSelectionSet();
        }
      }
    }

    if (statement == null)
      throw new CommandParsingException(language.toUpperCase() + " directive has no `statement` argument");

    final ResultSet resultSet = arguments != null ? database.query(language, statement, arguments) : database.query(language, statement);

    return new GraphQLResultSet(this, resultSet, projection != null ? projection.getSelections() : null, returnType, variables);
  }

  private static Map<String, Object> getArguments(final Arguments queryArguments, final Map<String, Object> variables) {
    Map<String, Object> arguments = null;

    if (queryArguments != null) {
      for (final Argument queryArgument : queryArguments.getList()) {
        final String argName = queryArgument.getName();
        final Object argValue = resolveValue(queryArgument.getValueWithVariable(), variables);

        if (arguments == null)
          arguments = new HashMap<>();

        arguments.put(argName, argValue);
      }
    }

    return arguments;
  }

  private ResultSet executeIntrospectionSchema(final Selection selection) {
    final InternalResultSet resultSet = new InternalResultSet();
    final ResultInternal schemaResult = new ResultInternal();

    final Field field = selection.getField();
    final SelectionSet selectionSet = field != null ? field.getSelectionSet() : null;

    if (selectionSet != null) {
      for (final Selection sub : selectionSet.getSelections()) {
        final String fieldName = sub.getName();
        if ("types".equals(fieldName))
          schemaResult.setProperty("types", buildTypeList(sub));
        else if ("queryType".equals(fieldName))
          schemaResult.setProperty("queryType", buildNameResult("Query"));
        else if ("mutationType".equals(fieldName))
          schemaResult.setProperty("mutationType", null);
        else if ("subscriptionType".equals(fieldName))
          schemaResult.setProperty("subscriptionType", null);
        else if ("directives".equals(fieldName))
          schemaResult.setProperty("directives", Collections.emptyList());
      }
    }

    resultSet.add(schemaResult);
    return resultSet;
  }

  private ResultSet executeIntrospectionType(final Selection selection, final Map<String, Object> variables) {
    final Field field = selection.getField();
    String typeName = null;

    if (field != null && field.getArguments() != null)
      for (final Argument arg : field.getArguments().getList())
        if ("name".equals(arg.getName())) {
          final Object nameValue = resolveValue(arg.getValueWithVariable(), variables);
          typeName = nameValue != null ? nameValue.toString() : null;
        }

    if (typeName == null)
      throw new CommandParsingException("__type query requires a 'name' argument");

    final SelectionSet selectionSet = field != null ? field.getSelectionSet() : null;
    final ResultInternal typeResult = buildTypeResult(typeName, selectionSet);

    if (typeResult == null)
      throw new CommandParsingException("Type '" + typeName + "' not found");

    final InternalResultSet resultSet = new InternalResultSet();
    resultSet.add(typeResult);
    return resultSet;
  }

  private ResultSet executeIntrospectionTypename() {
    final InternalResultSet resultSet = new InternalResultSet();
    final ResultInternal result = new ResultInternal();
    result.setProperty("__typename", "Query");
    resultSet.add(result);
    return resultSet;
  }

  private List<ResultInternal> buildTypeList(final Selection selection) {
    final List<ResultInternal> types = new ArrayList<>();
    final Set<String> addedTypes = new HashSet<>();

    final Field field = selection.getField();
    final SelectionSet selectionSet = field != null ? field.getSelectionSet() : null;

    // Add GraphQL-defined types
    for (final Map.Entry<String, ObjectTypeDefinition> entry : objectTypeDefinitionMap.entrySet()) {
      types.add(buildTypeResult(entry.getKey(), selectionSet));
      addedTypes.add(entry.getKey());
    }

    // Add database types not already covered by GraphQL definitions
    for (final DocumentType dbType : database.getSchema().getTypes()) {
      if (!addedTypes.contains(dbType.getName())) {
        types.add(buildDatabaseTypeResult(dbType, selectionSet));
        addedTypes.add(dbType.getName());
      }
    }

    // Add GraphQL built-in scalar types
    for (final String scalar : new String[] { "String", "Int", "Float", "Boolean", "ID" }) {
      if (!addedTypes.contains(scalar)) {
        final ResultInternal scalarResult = new ResultInternal();
        scalarResult.setProperty("name", scalar);
        scalarResult.setProperty("kind", "SCALAR");
        types.add(scalarResult);
      }
    }

    return types;
  }

  private ResultInternal buildTypeResult(final String typeName, final SelectionSet selectionSet) {
    final ObjectTypeDefinition objType = objectTypeDefinitionMap.get(typeName);
    if (objType != null)
      return buildGraphQLTypeResult(objType, selectionSet);

    // Check database types
    if (database.getSchema().existsType(typeName))
      return buildDatabaseTypeResult(database.getSchema().getType(typeName), selectionSet);

    // Check scalars
    if (Set.of("String", "Int", "Float", "Boolean", "ID").contains(typeName)) {
      final ResultInternal result = new ResultInternal();
      result.setProperty("name", typeName);
      result.setProperty("kind", "SCALAR");
      return result;
    }

    return null;
  }

  private ResultInternal buildGraphQLTypeResult(final ObjectTypeDefinition objType, final SelectionSet selectionSet) {
    final ResultInternal result = new ResultInternal();
    result.setProperty("name", objType.getName());
    result.setProperty("kind", "OBJECT");

    if (selectionSet != null) {
      for (final Selection sub : selectionSet.getSelections()) {
        if ("fields".equals(sub.getName())) {
          final List<ResultInternal> fields = new ArrayList<>();
          for (final FieldDefinition fd : objType.getFieldDefinitions()) {
            final ResultInternal fieldResult = new ResultInternal();
            fieldResult.setProperty("name", fd.getName());

            final Field subField = sub.getField();
            final SelectionSet fieldSelectionSet = subField != null ? subField.getSelectionSet() : null;
            if (fieldSelectionSet != null) {
              for (final Selection fieldSub : fieldSelectionSet.getSelections()) {
                if ("type".equals(fieldSub.getName()))
                  fieldResult.setProperty("type", buildFieldTypeInfo(fd));
              }
            }

            fields.add(fieldResult);
          }
          result.setProperty("fields", fields);
        }
      }
    }

    return result;
  }

  private ResultInternal buildDatabaseTypeResult(final DocumentType dbType, final SelectionSet selectionSet) {
    final ResultInternal result = new ResultInternal();
    result.setProperty("name", dbType.getName());
    result.setProperty("kind", "OBJECT");

    if (selectionSet != null) {
      for (final Selection sub : selectionSet.getSelections()) {
        if ("fields".equals(sub.getName())) {
          final List<ResultInternal> fields = new ArrayList<>();
          for (final Property prop : dbType.getProperties()) {
            final ResultInternal fieldResult = new ResultInternal();
            fieldResult.setProperty("name", prop.getName());

            final Field subField = sub.getField();
            final SelectionSet fieldSelectionSet = subField != null ? subField.getSelectionSet() : null;
            if (fieldSelectionSet != null) {
              for (final Selection fieldSub : fieldSelectionSet.getSelections()) {
                if ("type".equals(fieldSub.getName())) {
                  final ResultInternal typeInfo = new ResultInternal();
                  typeInfo.setProperty("name", mapDatabaseTypeToGraphQL(prop.getType()));
                  typeInfo.setProperty("kind", "SCALAR");
                  fieldResult.setProperty("type", typeInfo);
                }
              }
            }

            fields.add(fieldResult);
          }
          result.setProperty("fields", fields);
        }
      }
    }

    return result;
  }

  private ResultInternal buildFieldTypeInfo(final FieldDefinition fd) {
    final ResultInternal typeInfo = new ResultInternal();
    if (fd.getType().getListType() != null) {
      final String name = fd.getType().getListType().getType().getTypeName().getName();
      typeInfo.setProperty("name", name);
      typeInfo.setProperty("kind", "LIST");
    } else if (fd.getType().getTypeName() != null) {
      final String name = fd.getType().getTypeName().getName();
      typeInfo.setProperty("name", name);
      typeInfo.setProperty("kind", objectTypeDefinitionMap.containsKey(name) ? "OBJECT" : "SCALAR");
    }
    return typeInfo;
  }

  private ResultInternal buildNameResult(final String name) {
    final ResultInternal result = new ResultInternal();
    result.setProperty("name", name);
    return result;
  }

  private static String mapDatabaseTypeToGraphQL(final Type type) {
    if (type == null)
      return "String";
    return switch (type) {
      case INTEGER, SHORT, BYTE -> "Int";
      case LONG -> "Long";
      case FLOAT -> "Float";
      case DOUBLE -> "Float";
      case BOOLEAN -> "Boolean";
      default -> "String";
    };
  }

  public ObjectTypeDefinition getTypeFromField(final FieldDefinition fieldDefinition) {
    ObjectTypeDefinition returnType = null;
    if (fieldDefinition.getType().getTypeName() != null) {
      final String returnTypeName = fieldDefinition.getType().getTypeName().getName();
      returnType = objectTypeDefinitionMap.get(returnTypeName);

    } else if (fieldDefinition.getType().getListType() != null) {
      final String returnTypeName = fieldDefinition.getType().getListType().getType().getTypeName().getName();
      returnType = objectTypeDefinitionMap.get(returnTypeName);
    }
    return returnType;
  }
}
