/*
 * Copyright © 2021-present Arcade Data Ltd (info@arcadedata.com)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * SPDX-FileCopyrightText: 2021-present Arcade Data Ltd (info@arcadedata.com)
 * SPDX-License-Identifier: Apache-2.0
 */
package com.arcadedb.graphql.schema;

import com.arcadedb.database.Database;
import com.arcadedb.exception.CommandExecutionException;
import com.arcadedb.exception.CommandParsingException;
import com.arcadedb.graphql.parser.AbstractValue;
import com.arcadedb.graphql.parser.Argument;
import com.arcadedb.graphql.parser.Arguments;
import com.arcadedb.graphql.parser.Definition;
import com.arcadedb.graphql.parser.Directive;
import com.arcadedb.graphql.parser.Directives;
import com.arcadedb.graphql.parser.Document;
import com.arcadedb.graphql.parser.FieldDefinition;
import com.arcadedb.graphql.parser.GraphQLParser;
import com.arcadedb.graphql.parser.InputValueDefinition;
import com.arcadedb.graphql.parser.ListType;
import com.arcadedb.graphql.parser.ObjectTypeDefinition;
import com.arcadedb.graphql.parser.OperationDefinition;
import com.arcadedb.graphql.parser.ParseException;
import com.arcadedb.graphql.parser.Selection;
import com.arcadedb.graphql.parser.SelectionSet;
import com.arcadedb.graphql.parser.TypeDefinition;
import com.arcadedb.graphql.parser.TypeName;
import com.arcadedb.graphql.parser.TypeSystemDefinition;
import com.arcadedb.graphql.parser.ValueWithVariable;
import com.arcadedb.graphql.parser.VariableDefinition;
import com.arcadedb.graphql.parser.VariableDefinitions;
import com.arcadedb.graphql.parser.VariableLiteral;
import com.arcadedb.query.sql.executor.InternalResultSet;
import com.arcadedb.query.sql.executor.ResultInternal;
import com.arcadedb.query.sql.executor.ResultSet;
import com.arcadedb.schema.DocumentType;
import com.arcadedb.schema.Property;
import com.arcadedb.schema.Type;

import java.math.BigInteger;
import java.util.*;
import java.util.function.Function;

public class GraphQLSchema {
  /**
   * Prefix of the SQL parameter names generated by {@link #buildWhereClause}. The free-form {@code where} argument
   * is interpolated verbatim and could name a parameter of its own, so rather than rely on this prefix being an
   * unlikely choice, a predicate that uses it at all is rejected: the reservation is enforced, not hoped for.
   */
  private static final String BOUND_PARAMETER_PREFIX = "__gqlArg";
  /**
   * How many {@code fields} selections an introspection document may nest. A named type reached through {@code type}/{@code ofType}
   * is a full {@code __Type}, so without a cap each nested {@code fields} multiplies the work by the fan-out of the type it lists.
   */
  static final        int    MAX_INTROSPECTION_FIELDS_DEPTH = 2;

  private final Database                          database;
  private final Map<String, ObjectTypeDefinition> objectTypeDefinitionMap = new HashMap<>();
  private ObjectTypeDefinition              queryDefinition;

  public GraphQLSchema(final Database database) {
    this.database = database;
  }

  public ResultSet execute(final String query) throws ParseException {
    return execute(query, null);
  }

  /**
   * Executes a GraphQL document, binding the operation's variables from {@code parameters}. See issue #6834: before,
   * the parameters were dropped and every {@code $variable} resolved to {@code null}.
   */
  public ResultSet execute(final String query, final Map<String, Object> parameters) throws ParseException {
    final Document ast = GraphQLParser.parse(query);

    final List<Definition> definitions = ast.getDefinitions();
    if (!definitions.isEmpty()) {
      // COLLECTED FROM THE WHOLE DOCUMENT UP FRONT: THE OPERATION BELOW IS EXECUTED AS SOON AS IT IS MET, AND A FRAGMENT
      // IT SPREADS MAY BE DECLARED AFTER IT. SEE ISSUE #7770
      final GraphQLFragments fragments = GraphQLFragments.of(definitions);

      for (final Definition definition : definitions) {
        if (definition instanceof TypeSystemDefinition typeSystemDefinition) {

          final TypeDefinition type = typeSystemDefinition.getTypeDefinition();
          if (type instanceof ObjectTypeDefinition obj) {
            objectTypeDefinitionMap.put(obj.getName(), obj);

            if ("Query".equals(obj.getName()))
              // SPECIAL TYPE QUERY
              queryDefinition = obj;
          }

        } else if (definition instanceof OperationDefinition operationDefinition) {
          final OperationDefinition op = operationDefinition;
          if (op.isQuery()) {
            return executeQuery(op, parameters, fragments);
          } else
            throw new UnsupportedOperationException("GraphQL mutations not supported yet");
        }
      }
    }

    return new InternalResultSet();
  }

  private ResultSet executeQuery(final OperationDefinition op, final Map<String, Object> parameters,
      final GraphQLFragments documentFragments) {
    String from = null;

    SelectionSet projection = null;
    ObjectTypeDefinition returnType = null;
    FieldDefinition typeDefinition = null;
    final Set<String> typeArgumentNames = new HashSet<>();

    final Map<String, Object> variables = resolveVariables(op, parameters);
    // BOUND TO THE VARIABLES BEFORE ANYTHING IS EXPANDED: THE if ARGUMENT OF @skip AND @include CAN REFERENCE THEM
    final GraphQLFragments fragments = documentFragments.withVariables(variables);

    // UNKNOWN AND CYCLIC FRAGMENTS AND INVALID @skip/@include ARE REJECTED HERE, BEFORE ANY RECORD IS READ: THE RESULT SET
    // EXPANDS THE SELECTIONS LAZILY, WHILE IT IS ITERATED, WHERE AN ERROR WOULD NO LONGER BE CLASSIFIED AS A PARSING ONE
    fragments.validate(op.getSelectionSet());

    // THE OPERATION'S OWN SELECTIONS ARE FIELDS OF THE Query TYPE, WHICH A TOP-LEVEL FRAGMENT CAN BE WRITTEN ON
    final List<Selection> operationSelections = fragments.expand(op.getSelectionSet().getSelections(), "Query"::equals);
    if (operationSelections.size() > 1)
      throw new CommandParsingException("Error on executing multiple queries");
    if (operationSelections.isEmpty()) {
      // EXCLUDED BY @skip OR @include, THE ONLY FIELD IS WHAT A VALID DOCUMENT ASKED FOR: A RESPONSE WITH NO FIELD. WITHOUT
      // THEM THERE IS STILL NO FIELD WHEN THE FRAGMENTS CANNOT APPLY TO Query, WHICH THE SPECIFICATION REJECTS
      if (!fragments.expand(op.getSelectionSet().getSelections(), "Query"::equals, false).isEmpty())
        return new InternalResultSet();
      throw new CommandParsingException("GraphQL query selects no field");
    }

    String queryName = null;

    try {
      final Selection selection = operationSelections.getFirst();
      queryName = selection.getFieldName();

      // HANDLE INTROSPECTION QUERIES
      if ("__schema".equals(queryName))
        return executeIntrospectionSchema(selection, fragments);
      else if ("__type".equals(queryName))
        return executeIntrospectionType(selection, variables, fragments);
      else if ("__typename".equals(queryName))
        return executeIntrospectionTypename(selection);
      if (queryDefinition != null) {
        for (final FieldDefinition f : queryDefinition.getFieldDefinitions()) {
          if (queryName.equals(f.getName())) {
            typeDefinition = f;
            returnType = getTypeFromField(f);
            // THE ARGUMENTS DEFINITION IS OPTIONAL IN THE GRAMMAR: A FIELD DECLARED WITHOUT A PARAMETER LIST
            // (E.G. `allBooks: [Book]`) LEAVES IT NULL. SEE ISSUE #6835
            if (f.getArgumentsDefinition() != null)
              for (final InputValueDefinition d : f.getArgumentsDefinition().getInputValueDefinitions())
                typeArgumentNames.add(d.getName().getValue());
            if (returnType != null)
              from = returnType.getName();
          }
        }
      }

      if (from == null)
        throw new CommandParsingException("Target type not defined for GraphQL query '" + queryName + "'");

      if (typeDefinition != null) {
        final Directives directives = typeDefinition.getDirectives();
        if (directives != null) {
          for (final Directive directive : directives.getDirectives()) {
            final String directiveName = directive.getName();

            // TODO: REFACTOR THIS IN MULTIPLE PLUGGABLE CLASSES
            if ("sql".equals(directiveName) ||
                "gremlin".equals(directiveName) ||
                "cypher".equals(directiveName))
              return parseNativeQueryDirective(directiveName, directive, selection, returnType, variables, fragments);
          }
        }
      }

      final Arguments queryArguments = selection.getArguments();
      projection = selection.getSelectionSet();

      final Map<String, Object> boundParameters = new HashMap<>();
      final String where = buildWhereClause(queryArguments, typeArgumentNames, variables, boundParameters);

      String query = "select from " + from;
      if (!where.isEmpty())
        query += " where " + where;

      final ResultSet resultSet =
          boundParameters.isEmpty() ? database.query("sql", query) : database.query("sql", query, boundParameters);

      return new GraphQLResultSet(this, resultSet, projection != null ? projection.getSelections() : null, returnType,
          variables, fragments);

    } catch (final CommandParsingException | CommandExecutionException e) {
      // An execution failure raised by the statement this query delegates to keeps the classification the engine
      // gave it. Rewrapping it as a parsing exception reported a runtime error - an arithmetic error, or the
      // NoSuchElementException #5219 covers - as a malformed document. See issue #5628.
      //
      // Deliberately narrower than ArcadeDBException: SchemaException is NOT passed through. It would reach the
      // HTTP handler, which has no arm for it, as a 500 - and the class is not purely a caller error (Dictionary
      // and TransactionManager raise it for genuine server faults, e.g. issue #4122), so it cannot simply be
      // mapped to 400 either. Tracked as a follow-up rather than decided here.
      throw e;
    } catch (final Exception e) {
      if (queryName != null)
        throw new CommandParsingException("Error on executing GraphQL query '" + queryName + "'", e);
      throw new CommandParsingException("Error on executing GraphQL query", e);
    }

  }

  /**
   * Builds a SQL {@code where} clause from a GraphQL field's arguments, shared by both the plain-field and
   * aliased-field dispatch paths so they cannot drift apart the way they did before (issue #6453).
   * <p>
   * Argument values are never written into the statement text: each one is bound as a named SQL parameter added to
   * {@code boundParameters}. Quoting them by hand made the correctness of any value carrying a quote or a backslash
   * depend on the SQL string-literal rules happening to match the GraphQL ones (issue #6836).
   * <p>
   * The one exception is the reserved {@code where} argument, which is a free-form SQL predicate by design and is
   * therefore still interpolated verbatim. Whatever is written there is SQL and has to be trusted the same way a
   * hand-written statement is - which is why it cannot be filled from a variable: an application that treats its
   * GraphQL document as trusted and its variables as untrusted input would otherwise be handing a caller raw SQL
   * without meaning to. Variables never resolved before issue #6834, so nothing can depend on that combination; a
   * predicate that genuinely has to vary at runtime belongs in a {@code @sql} directive with a bound parameter.
   */
  private String buildWhereClause(final Arguments queryArguments, final Set<String> typeArgumentNames,
      final Map<String, Object> variables, final Map<String, Object> boundParameters) {
    final StringBuilder where = new StringBuilder();

    if (queryArguments != null)
      for (final Argument queryArgument : queryArguments.getList()) {
        final String argName = queryArgument.getName();
        if (!typeArgumentNames.contains(argName))
          throw new CommandParsingException("Parameter '" + argName + "' not defined in query");

        final ValueWithVariable argument = queryArgument.getValueWithVariable();

        if ("where".equals(argName) && argument != null && argument.getValue() instanceof VariableLiteral variable)
          throw new CommandParsingException("The reserved 'where' argument is interpolated into the statement verbatim, "
              + "so it cannot be filled from the variable '$" + variable.getName()
              + "': use a @sql directive with a bound parameter for a predicate that has to vary at runtime");

        final Object argValue = resolveValue(argument, variables);

        if (!where.isEmpty())
          where.append(" and ");

        if ("where".equals(argName)) {
          final String predicate = String.valueOf(argValue);
          if (predicate.contains(BOUND_PARAMETER_PREFIX))
            throw new CommandParsingException("The 'where' predicate cannot name a parameter starting with '"
                + BOUND_PARAMETER_PREFIX + "': that prefix is reserved for the parameters bound for the other arguments");
          where.append(predicate);
        } else {
          final String parameterName = BOUND_PARAMETER_PREFIX + boundParameters.size();
          boundParameters.put(parameterName, argValue);
          where.append(argName).append(" = :").append(parameterName);
        }
      }

    return where.toString();
  }

  /**
   * Coerces the variable values of an operation: a value supplied by the caller wins, otherwise the declared default
   * value is used, otherwise the variable is null - and a variable declared non-null without any of the two is an
   * error. The returned map contains exactly the declared variables, so {@link #resolveValue} can tell a variable
   * that resolves to null from one that was never declared. See issue #6834.
   */
  private static Map<String, Object> resolveVariables(final OperationDefinition op, final Map<String, Object> parameters) {
    final VariableDefinitions definitions = op.getVariableDefinitions();
    if (definitions == null || definitions.getVariableDefinitions().isEmpty())
      return Collections.emptyMap();

    final Map<String, Object> variables = new HashMap<>(definitions.getVariableDefinitions().size());
    for (final VariableDefinition definition : definitions.getVariableDefinitions()) {
      final VariableLiteral literal = definition.getVariableLiteral();
      if (literal == null)
        continue;

      final String name = literal.getName();
      final boolean nonNull = definition.getType() != null && definition.getType().isBang();

      if (parameters != null && parameters.containsKey(name)) {
        final Object parameterValue = parameters.get(name);
        // A NON-NULL VARIABLE IS NOT SATISFIED BY A KEY THAT IS PRESENT WITH A NULL VALUE
        if (parameterValue == null && nonNull)
          throw new CommandParsingException("GraphQL variable '$" + name + "' is declared as non-null but null was passed");
        checkDeclaredType(name, definition, parameterValue, "passed");
        variables.put(name, parameterValue);
        continue;
      }

      if (definition.getDefaultValue() != null) {
        final AbstractValue defaultValue = definition.getDefaultValue().getValue().getValue();
        if (defaultValue == null)
          throw new CommandParsingException(
              "Default value of GraphQL variable '$" + name + "' is not a scalar: list and object default values are not supported");
        final Object value = defaultValue.getValue();
        checkDeclaredType(name, definition, value, "declared as its default");
        variables.put(name, value);
        continue;
      }

      if (nonNull)
        throw new CommandParsingException("GraphQL variable '$" + name + "' is declared as non-null but no value was passed");

      variables.put(name, null);
    }

    return variables;
  }

  /**
   * Rejects a variable value that the declared type cannot hold, so a mismatch is reported against the schema the
   * caller wrote rather than left to the SQL comparator to coerce - which it does today for a numeric string, but
   * not for every pairing, and a pairing it cannot coerce matches nothing without saying why.
   * <p>
   * Only the five built-in scalars are checked, with the coercion rules of the specification: {@code Int} takes
   * integral values in 32-bit range, {@code Float} takes any finite number (an integer input value is a valid
   * float, {@code NaN} and the infinities are not values the specification lets a Float carry),
   * {@code ID} takes a string or an integral value of any width - it is serialised as a string and carries no range
   * of its own, which is exactly why a schema uses it for a key too large for {@code Int}. Every other declared type name - a custom scalar such as the
   * {@code WHERE} used for the free-form predicate argument, an enum, an input object - is deliberately left
   * unchecked: this module does not model them, and rejecting what it cannot describe would be worse than passing
   * it through. A list type is skipped for the same reason.
   */
  private static void checkDeclaredType(final String name, final VariableDefinition definition, final Object value,
      final String origin) {
    if (value == null)
      return;

    final TypeName typeName = definition.getType() != null ? definition.getType().getTypeName() : null;
    if (typeName == null)
      return;

    final String declared = typeName.getName();
    final boolean valid = switch (declared) {
      case "Int" -> isInteger(value);
      case "Float" -> value instanceof Number && isFinite(value);
      case "Boolean" -> value instanceof Boolean;
      case "String" -> value instanceof String;
      case "ID" -> value instanceof String || isIntegral(value);
      default -> true;
    };

    if (!valid)
      throw new CommandParsingException(
          "GraphQL variable '$" + name + "' is declared as " + declared + " but a " + value.getClass().getSimpleName()
              + " value was " + origin);
  }

  /**
   * Whether the value is an integral number the 32-bit {@code Int} scalar can hold. The width has to be checked for
   * every type wide enough to exceed it, not only for {@code Long}: {@link BigInteger} carries no bound at all.
   */
  private static boolean isInteger(final Object value) {
    if (value instanceof Long l)
      return l == l.intValue();
    if (value instanceof BigInteger b)
      // bitLength() EXCLUDES THE SIGN BIT, SO A SIGNED 32-BIT VALUE IS EXACTLY ONE OF AT MOST 31 BITS
      return b.bitLength() < Integer.SIZE;
    return value instanceof Integer || value instanceof Short || value instanceof Byte;
  }

  /**
   * Whether the value is a finite number. {@code NaN} and the infinities are representable in Java but are not
   * values the {@code Float} scalar can carry.
   */
  private static boolean isFinite(final Object value) {
    if (value instanceof Double d)
      return !d.isNaN() && !d.isInfinite();
    if (value instanceof Float f)
      return !f.isNaN() && !f.isInfinite();
    return true;
  }

  /**
   * Whether the value is an integral number of any width. A floating-point value is not one even when it happens to
   * have no fractional part: the caller is checking what was passed, not what it could be rounded to.
   */
  private static boolean isIntegral(final Object value) {
    return value instanceof Integer || value instanceof Long || value instanceof Short || value instanceof Byte
        || value instanceof BigInteger;
  }

  /**
   * Resolves an argument value, substituting the operation's variable values for a {@code $variable} reference.
   */
  static Object resolveValue(final ValueWithVariable valueWithVariable, final Map<String, Object> variables) {
    final AbstractValue value = valueWithVariable != null ? valueWithVariable.getValue() : null;
    if (value instanceof VariableLiteral variable) {
      final String name = variable.getName();
      if (variables == null || !variables.containsKey(name))
        throw new CommandParsingException("GraphQL variable '$" + name + "' is not declared by the operation");
      return variables.get(name);
    }
    return value != null ? value.getValue() : null;
  }

  private GraphQLResultSet parseNativeQueryDirective(final String language, final Directive directive, final Selection selection,
      final ObjectTypeDefinition returnType, final Map<String, Object> variables, final GraphQLFragments fragments) {
    if (directive.getArguments() == null)
      throw new CommandParsingException(language.toUpperCase(Locale.ENGLISH) + " directive has no `statement` argument");

    String statement = null;
    Map<String, Object> arguments = null;
    SelectionSet projection = null;

    for (final Argument argument : directive.getArguments().getList()) {
      if ("statement".equals(argument.getName())) {
        // THE DIRECTIVE IS PART OF THE SCHEMA, NOT OF THE OPERATION: NO VARIABLE CAN BE BOUND IN IT
        final Object statementValue = resolveValue(argument.getValueWithVariable(), null);
        statement = statementValue != null ? statementValue.toString() : null;

        arguments = getArguments(selection.getArguments(), variables);
        projection = selection.getSelectionSet();
      }
    }

    if (statement == null)
      throw new CommandParsingException(language.toUpperCase(Locale.ROOT) + " directive has no `statement` argument");

    final ResultSet resultSet = arguments != null ? database.query(language, statement, arguments) : database.query(language, statement);

    return new GraphQLResultSet(this, resultSet, projection != null ? projection.getSelections() : null, returnType, variables,
        fragments);
  }

  private static Map<String, Object> getArguments(final Arguments queryArguments, final Map<String, Object> variables) {
    Map<String, Object> arguments = null;

    if (queryArguments != null) {
      for (final Argument queryArgument : queryArguments.getList()) {
        final String argName = queryArgument.getName();
        final Object argValue = resolveValue(queryArgument.getValueWithVariable(), variables);

        if (arguments == null)
          arguments = new HashMap<>();

        arguments.put(argName, argValue);
      }
    }

    return arguments;
  }

  private ResultSet executeIntrospectionSchema(final Selection selection, final GraphQLFragments fragments) {
    final InternalResultSet resultSet = new InternalResultSet();
    final ResultInternal schemaResult = new ResultInternal();

    // Resolved through Selection.getSelectionSet()/getFieldName() so an aliased selection (`s: __schema { ... }`,
    // `t: types { ... }`) is served exactly as the plain one, and the result is keyed by the alias the client wrote,
    // as the GraphQL spec requires for response keys (issue #7036)
    final SelectionSet selectionSet = selection.getSelectionSet();

    if (selectionSet != null) {
      for (final Selection sub : fragments.expand(selectionSet.getSelections(), "__Schema"::equals)) {
        final String fieldName = sub.getFieldName();
        final String responseKey = sub.getName();
        if ("types".equals(fieldName))
          schemaResult.setProperty(responseKey, buildTypeList(sub, fragments));
        else if ("queryType".equals(fieldName))
          schemaResult.setProperty(responseKey, buildQueryTypeResult(sub.getSelectionSet(), fragments, 0));
        else if ("mutationType".equals(fieldName))
          schemaResult.setProperty(responseKey, null);
        else if ("subscriptionType".equals(fieldName))
          schemaResult.setProperty(responseKey, null);
        else if ("directives".equals(fieldName))
          schemaResult.setProperty(responseKey, Collections.emptyList());
        else if ("__typename".equals(fieldName))
          schemaResult.setProperty(responseKey, "__Schema");
      }
    }

    resultSet.add(schemaResult);
    return resultSet;
  }

  private ResultSet executeIntrospectionType(final Selection selection, final Map<String, Object> variables,
      final GraphQLFragments fragments) {
    final Arguments arguments = selection.getArguments();
    String typeName = null;

    if (arguments != null)
      for (final Argument arg : arguments.getList())
        if ("name".equals(arg.getName())) {
          final Object nameValue = resolveValue(arg.getValueWithVariable(), variables);
          typeName = nameValue != null ? nameValue.toString() : null;
        }

    if (typeName == null)
      throw new CommandParsingException("__type query requires a 'name' argument");

    final ResultInternal typeResult = buildTypeResult(typeName, selection.getSelectionSet(), fragments, 0);

    if (typeResult == null)
      throw new CommandParsingException("Type '" + typeName + "' not found");

    final InternalResultSet resultSet = new InternalResultSet();
    resultSet.add(typeResult);
    return resultSet;
  }

  private ResultSet executeIntrospectionTypename(final Selection selection) {
    final InternalResultSet resultSet = new InternalResultSet();
    final ResultInternal result = new ResultInternal();
    // Keyed by the response key the client wrote: `{ t: __typename }` answers under "t" (issue #7888)
    result.setProperty(selection.getName(), "Query");
    resultSet.add(result);
    return resultSet;
  }

  private List<ResultInternal> buildTypeList(final Selection selection, final GraphQLFragments fragments) {
    final List<ResultInternal> types = new ArrayList<>();
    final Set<String> addedTypes = new HashSet<>();

    final SelectionSet selectionSet = selection.getSelectionSet();

    // Add GraphQL-defined types
    for (final Map.Entry<String, ObjectTypeDefinition> entry : objectTypeDefinitionMap.entrySet()) {
      types.add(buildTypeResult(entry.getKey(), selectionSet, fragments, 0));
      addedTypes.add(entry.getKey());
    }

    // Add database types not already covered by GraphQL definitions
    for (final DocumentType dbType : database.getSchema().getTypes()) {
      if (!addedTypes.contains(dbType.getName())) {
        types.add(buildDatabaseTypeResult(dbType, selectionSet, fragments, 0));
        addedTypes.add(dbType.getName());
      }
    }

    // Add GraphQL built-in scalar types
    for (final String scalar : new String[] { "String", "Int", "Float", "Boolean", "ID" }) {
      if (!addedTypes.contains(scalar))
        types.add(buildIntrospectionLeafType(scalar, "SCALAR", selectionSet, fragments));
    }

    return types;
  }

  private ResultInternal buildTypeResult(final String typeName, final SelectionSet selectionSet, final GraphQLFragments fragments,
      final int fieldsDepth) {
    final ObjectTypeDefinition objType = objectTypeDefinitionMap.get(typeName);
    if (objType != null)
      return buildGraphQLTypeResult(objType, selectionSet, fragments, fieldsDepth);

    // Check database types
    if (database.getSchema().existsType(typeName))
      return buildDatabaseTypeResult(database.getSchema().getType(typeName), selectionSet, fragments, fieldsDepth);

    // Check scalars
    if (Set.of("String", "Int", "Float", "Boolean", "ID").contains(typeName))
      return buildIntrospectionLeafType(typeName, "SCALAR", selectionSet, fragments);

    return null;
  }

  private ResultInternal buildGraphQLTypeResult(final ObjectTypeDefinition objType, final SelectionSet selectionSet,
      final GraphQLFragments fragments, final int fieldsDepth) {
    return buildIntrospectionType(objType.getName(), "OBJECT", selectionSet, fragments, fieldsSelection -> {
      final List<Selection> fieldSelections = expandFieldSelections(fieldsSelection, fragments, fieldsDepth);
      final List<ResultInternal> fields = new ArrayList<>();
      for (final FieldDefinition fd : objType.getFieldDefinitions())
        fields.add(buildIntrospectionField(fd.getName(), fieldSelections,
            typeSelectionSet -> buildTypeInfo(fd.getType(), typeSelectionSet, fragments, fieldsDepth + 1)));
      return fields;
    }, null);
  }

  private ResultInternal buildDatabaseTypeResult(final DocumentType dbType, final SelectionSet selectionSet,
      final GraphQLFragments fragments, final int fieldsDepth) {
    return buildIntrospectionType(dbType.getName(), "OBJECT", selectionSet, fragments, fieldsSelection -> {
      final List<Selection> fieldSelections = expandFieldSelections(fieldsSelection, fragments, fieldsDepth);
      final List<ResultInternal> fields = new ArrayList<>();
      for (final Property prop : dbType.getProperties())
        fields.add(buildIntrospectionField(prop.getName(), fieldSelections,
            typeSelectionSet -> buildIntrospectionLeafType(mapDatabaseTypeToGraphQL(prop.getType()), "SCALAR", typeSelectionSet,
                fragments)));
      return fields;
    }, null);
  }

  /**
   * The {@code Query} root type of {@code __schema { queryType { ... } }}: the full {@code __Type} when the SDL declares it, otherwise
   * a named OBJECT with no fields to list.
   */
  private ResultInternal buildQueryTypeResult(final SelectionSet selectionSet, final GraphQLFragments fragments,
      final int fieldsDepth) {
    final ObjectTypeDefinition queryType = objectTypeDefinitionMap.get("Query");
    if (queryType != null)
      return buildGraphQLTypeResult(queryType, selectionSet, fragments, fieldsDepth);
    return buildIntrospectionLeafType("Query", "OBJECT", selectionSet, fragments);
  }

  /**
   * Recursively describes a GraphQL type reference, matching the introspection schema a client relies on to walk list/non-null
   * wrappers (#7116): a wrapping type (LIST or NON_NULL) carries {@code ofType} and no {@code name} of its own; only the innermost
   * named type carries {@code name}. Every hop is built from the selection set the client wrote for it (#7888). The parameter is
   * {@code com.arcadedb.graphql.parser.Type}, qualified because {@code com.arcadedb.schema.Type} is already imported under the same
   * simple name.
   */
  private ResultInternal buildTypeInfo(final com.arcadedb.graphql.parser.Type type, final SelectionSet selectionSet,
      final GraphQLFragments fragments, final int fieldsDepth) {
    final Function<SelectionSet, ResultInternal> unwrapped;
    final boolean nonNull;
    if (type.getListType() != null) {
      final ListType listType = type.getListType();
      unwrapped = listSelectionSet -> buildIntrospectionType(null, "LIST", listSelectionSet, fragments, null,
          ofTypeSelectionSet -> buildTypeInfo(listType.getType(), ofTypeSelectionSet, fragments, fieldsDepth));
      nonNull = listType.isBang();
    } else {
      final String name = type.getTypeName().getName();
      unwrapped = namedSelectionSet -> {
        final ObjectTypeDefinition objType = objectTypeDefinitionMap.get(name);
        return objType != null ?
            buildGraphQLTypeResult(objType, namedSelectionSet, fragments, fieldsDepth) :
            buildIntrospectionLeafType(name, "SCALAR", namedSelectionSet, fragments);
      };
      nonNull = type.isBang();
    }
    return nonNull ? buildIntrospectionType(null, "NON_NULL", selectionSet, fragments, null, unwrapped) : unwrapped.apply(selectionSet);
  }

  /**
   * Builds one {@code __Type} object from the selections the client wrote: each leaf is written only when selected, under the
   * response key the selection carries (the alias when there is one), as the GraphQL spec requires (issue #7888). A selection set
   * of null, which a valid document never has for an object-typed field, keeps the historical shape: {@code name} and {@code kind},
   * plus the {@code ofType} chain of a wrapper.
   *
   * @param fields the builder of the {@code fields} list, given the {@code fields} selection; null for a type with no fields
   * @param ofType the builder of the wrapped type, given the {@code ofType} selection set; null for a named type
   */
  private static ResultInternal buildIntrospectionType(final String name, final String kind, final SelectionSet selectionSet,
      final GraphQLFragments fragments, final Function<Selection, List<ResultInternal>> fields,
      final Function<SelectionSet, ResultInternal> ofType) {
    final ResultInternal result = new ResultInternal();
    if (selectionSet == null) {
      result.setProperty("name", name);
      result.setProperty("kind", kind);
      if (ofType != null)
        result.setProperty("ofType", ofType.apply(null));
      return result;
    }

    for (final Selection sub : fragments.expand(selectionSet.getSelections(), "__Type"::equals)) {
      final String fieldName = sub.getFieldName();
      final String responseKey = sub.getName();
      if ("name".equals(fieldName))
        result.setProperty(responseKey, name);
      else if ("kind".equals(fieldName))
        result.setProperty(responseKey, kind);
      else if ("fields".equals(fieldName))
        result.setProperty(responseKey, fields != null ? fields.apply(sub) : null);
      else if ("ofType".equals(fieldName))
        result.setProperty(responseKey, ofType != null ? ofType.apply(sub.getSelectionSet()) : null);
      else if ("__typename".equals(fieldName))
        result.setProperty(responseKey, "__Type");
    }
    return result;
  }

  /**
   * A {@code __Type} with neither {@code fields} nor {@code ofType} to describe: a SCALAR, or an OBJECT whose fields are not known.
   */
  private static ResultInternal buildIntrospectionLeafType(final String name, final String kind, final SelectionSet selectionSet,
      final GraphQLFragments fragments) {
    return buildIntrospectionType(name, kind, selectionSet, fragments, null, null);
  }

  /**
   * Builds one {@code __Field} object, with the same selection-driven keying as {@link #buildIntrospectionType}. Null selections (a
   * {@code fields} selection with no selection set of its own) keep the historical shape: the field's {@code name} only.
   */
  private static ResultInternal buildIntrospectionField(final String name, final List<Selection> fieldSelections,
      final Function<SelectionSet, ResultInternal> type) {
    final ResultInternal result = new ResultInternal();
    if (fieldSelections == null) {
      result.setProperty("name", name);
      return result;
    }

    for (final Selection sub : fieldSelections) {
      final String fieldName = sub.getFieldName();
      if ("name".equals(fieldName))
        result.setProperty(sub.getName(), name);
      else if ("type".equals(fieldName))
        result.setProperty(sub.getName(), type.apply(sub.getSelectionSet()));
      else if ("__typename".equals(fieldName))
        result.setProperty(sub.getName(), "__Field");
    }
    return result;
  }

  /**
   * The selections of a {@code fields { ... }} selection, with its fragments expanded once for every field it describes.
   */
  private static List<Selection> expandFieldSelections(final Selection fieldsSelection, final GraphQLFragments fragments,
      final int fieldsDepth) {
    if (fieldsDepth >= MAX_INTROSPECTION_FIELDS_DEPTH)
      throw new CommandParsingException(
          "Introspection query nests 'fields' more than " + MAX_INTROSPECTION_FIELDS_DEPTH + " levels deep");
    final SelectionSet fieldSelectionSet = fieldsSelection.getSelectionSet();
    return fieldSelectionSet != null ? fragments.expand(fieldSelectionSet.getSelections(), "__Field"::equals) : null;
  }

  private static String mapDatabaseTypeToGraphQL(final Type type) {
    if (type == null)
      return "String";
    return switch (type) {
      case INTEGER, SHORT, BYTE -> "Int";
      case LONG -> "Long";
      case FLOAT -> "Float";
      case DOUBLE -> "Float";
      case BOOLEAN -> "Boolean";
      default -> "String";
    };
  }

  /**
   * Whether the SDL registered so far declares an object type with this name. Interfaces, unions and input types are
   * not modeled, so they are never reported.
   */
  public boolean isObjectType(final String name) {
    return objectTypeDefinitionMap.containsKey(name);
  }

  /**
   * Whether the database schema has a type with this name.
   */
  public boolean isDatabaseType(final String name) {
    return database.getSchema().existsType(name);
  }

  public ObjectTypeDefinition getTypeFromField(final FieldDefinition fieldDefinition) {
    ObjectTypeDefinition returnType = null;
    if (fieldDefinition.getType().getTypeName() != null) {
      final String returnTypeName = fieldDefinition.getType().getTypeName().getName();
      returnType = objectTypeDefinitionMap.get(returnTypeName);

    } else if (fieldDefinition.getType().getListType() != null) {
      final String returnTypeName = fieldDefinition.getType().getListType().getType().getTypeName().getName();
      returnType = objectTypeDefinitionMap.get(returnTypeName);
    }
    return returnType;
  }
}
