/* Generated By:JJTree: Do not edit this line. Batch.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=O,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.arcadedb.query.sql.parser;

import com.arcadedb.exception.CommandExecutionException;
import com.arcadedb.query.sql.executor.CommandContext;

import java.util.*;

public class Batch extends SimpleNode {

  protected PInteger num;

  protected InputParameter inputParam;

  public Batch(final int id) {
    super(id);
  }

  public Integer evaluate(final CommandContext ctx) {
    if (this.num != null) {
      return num.getValue().intValue();
    } else if (inputParam != null) {
      final Object obj = inputParam.getValue(ctx.getInputParameters());
      if (!(obj instanceof Number)) {
        throw new CommandExecutionException(obj + " is not a number (BATCH)");
      }
      return ((Number) obj).intValue();
    }
    return -1;
  }

  public void toString(final Map<String, Object> params, final StringBuilder builder) {
    if (num == null && inputParam == null)
      return;

    builder.append(" BATCH ");
    if (num != null)
      num.toString(params, builder);
    else
      inputParam.toString(params, builder);
  }

  public Batch copy() {
    final Batch result = new Batch(-1);
    result.inputParam = inputParam == null ? null : inputParam.copy();
    result.num = num == null ? null : num.copy();
    return result;
  }

  @Override
  public boolean equals(final Object o) {
    if (this == o)
      return true;
    if (o == null || getClass() != o.getClass())
      return false;

    final Batch batch = (Batch) o;

    if (!Objects.equals(num, batch.num))
      return false;
    if (!Objects.equals(inputParam, batch.inputParam))
      return false;

    return true;
  }

  @Override
  public int hashCode() {
    int result = num != null ? num.hashCode() : 0;
    result = 31 * result + (inputParam != null ? inputParam.hashCode() : 0);
    return result;
  }
}
/* JavaCC - OriginalChecksum=b1587460e08cbf21086d8c8fcca192e0 (do not edit this line) */
