/*
 * Copyright © 2021-present Arcade Data Ltd (info@arcadedata.com)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * SPDX-FileCopyrightText: 2021-present Arcade Data Ltd (info@arcadedata.com)
 * SPDX-License-Identifier: Apache-2.0
 */
/* Generated by: JJTree: Do not edit this line. ImportDatabaseStatement.java Version 1.1 */
/* ParserGeneratorCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.arcadedb.query.sql.parser;

import com.arcadedb.GlobalConfiguration;
import com.arcadedb.database.Database;
import com.arcadedb.database.DatabaseInternal;
import com.arcadedb.database.Identifiable;
import com.arcadedb.engine.OperationProgress;
import com.arcadedb.engine.OperationProgressRegistry;
import com.arcadedb.exception.CommandExecutionException;
import com.arcadedb.query.sql.executor.CommandContext;
import com.arcadedb.query.sql.executor.InternalResultSet;
import com.arcadedb.query.sql.executor.ResultInternal;
import com.arcadedb.query.sql.executor.ResultSet;
import com.arcadedb.security.SecurityDatabaseUser;

import java.lang.reflect.InvocationTargetException;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;

public class ImportDatabaseStatement extends SimpleExecStatement {

  public          Url                         url;
  protected       Expression                  key;
  protected       Expression                  value;
  public final    Map<Expression, Expression> settings = new HashMap<>();

  public ImportDatabaseStatement() {
  }

  @Override
  public ResultSet executeSimple(final CommandContext context) {
    // IMPORT DATABASE can create schema, overwrite data and read local files / remote URLs (SSRF/LFI surface), so it is
    // restricted to administrative users. In embedded mode (no security configured) this check is a no-op.
    context.getDatabase().checkPermissionsOnDatabase(SecurityDatabaseUser.DATABASE_ACCESS.UPDATE_SECURITY);

    final ResultInternal result = new ResultInternal(context.getDatabase());
    result.setProperty("operation", "import database");

    if (this.url != null)
      result.setProperty("fromUrl", this.url.getUrlString());

    // PUBLISH LIVE PROGRESS (issue #5376): the importer runs behind a reflective boundary (integration
    // module) and its record total is unknown upfront, so only the coarse operation is published - visible in
    // the progress endpoint, console and Studio while it runs. Always retired in the finally.
    final OperationProgress progress = OperationProgressRegistry.instance()
        .register(context.getDatabase().getName(), "import database");
    progress.onProgress("Importing database", 1, 1, 0, -1);
    try {
      final Class<?> clazz = Class.forName("com.arcadedb.integration.importer.Importer");
      // Use the outermost database wrapper (e.g. RaftReplicatedDatabase in HA mode) so that
      // the importer's commit() calls are intercepted for replication. In non-HA mode,
      // getWrappedDatabaseInstance() returns the database itself, so there is no change in behaviour.
      final Database db = context.getDatabase();
      final Database effectiveDb = db instanceof DatabaseInternal di ? di.getWrappedDatabaseInstance() : db;
      final Object importer = clazz.getConstructor(Database.class, String.class).newInstance(effectiveDb, url != null ? url.getUrlString() : null);

      // Threads this command's resolved SERVER_SECURITY_IMPORT_BLOCK_LOCAL_NETWORKS through to the importer's deep
      // fetch explicitly, rather than letting SourceDiscovery re-derive it from the static GlobalConfiguration value
      // on its own. context.getConfiguration() falls back to that same static value when no caller overrode it (a
      // client-issued 'IMPORT DATABASE ...' reaches here with no override and sees no behaviour change), but when
      // PostServerCommandHandler's 'import database' server command already validated the URL against its own,
      // possibly per-instance-overridden SERVER_RESTORE_IMPORT_ALLOW_LOCAL_URLS, it passes the resolved answer down
      // via the ContextConfiguration it hands to database.command(...) so the two layers cannot disagree (#6474).
      // This is NOT settable through the statement's own 'WITH ...' settings map below: those settings map to
      // ImporterSettings fields one at a time by name, and allowLocalUrls is deliberately not one of them, or any
      // client able to run IMPORT DATABASE could self-authorize past the SSRF guard from SQL text alone.
      final boolean blockLocalNetworks = context.getConfiguration().getValue(GlobalConfiguration.SERVER_SECURITY_IMPORT_BLOCK_LOCAL_NETWORKS);
      clazz.getMethod("setAllowLocalUrls", boolean.class).invoke(importer, !blockLocalNetworks);

      // TRANSFORM SETTINGS
      final Map<String, String> settingsToString = new HashMap<>();
      for (final Map.Entry<Expression, Expression> entry : settings.entrySet()) {
        final Object valueResult = entry.getValue().execute((Identifiable) null, context);
        final String valueStr = valueResult != null ? valueResult.toString() : entry.getValue().toString();
        settingsToString.put(entry.getKey().toString(), valueStr);
      }

      clazz.getMethod("setSettings", Map.class).invoke(importer, settingsToString);
      final Map<String, Object> statistics = (Map<String, Object>) clazz.getMethod("load").invoke(importer);

      if (statistics != null)
        result.setPropertiesFromMap(statistics);

    } catch (final ClassNotFoundException | NoSuchMethodException | IllegalAccessException | InstantiationException e) {
      throw new CommandExecutionException("Error on importing database, importer libs not found in classpath", e);
    } catch (final InvocationTargetException e) {
      // SURFACE A SECURITY VIOLATION (SSRF/LFI GUARD IN THE IMPORTER) DIRECTLY SO IT MAPS TO HTTP 403 INSTEAD OF 500
      for (Throwable cause = e.getTargetException(); cause != null; cause = cause.getCause())
        if (cause instanceof SecurityException se)
          throw se;

      if ("IllegalArgumentException".equals(e.getCause().getClass().getSimpleName()))
        result.setProperty("result", "FAIL");
      else
        throw new CommandExecutionException("Error on importing database", e.getTargetException());
    } finally {
      OperationProgressRegistry.instance().unregister(progress);
    }

    result.setProperty("result", "OK");

    final InternalResultSet rs = new InternalResultSet();
    rs.add(result);
    return rs;
  }

  @Override
  public void toString(final Map<String, Object> params, final StringBuilder builder) {
    builder.append("IMPORT DATABASE ");
    if (url != null)
      url.toString(params, builder);
    appendWithSettings(settings, params, builder);
  }

  /**
   * Compares {@code settings} too, not just {@code url}: for {@code IMPORT DATABASE} the settings ARE the statement
   * (a CSV import has no URL at all, only {@code WITH vertices=..., edges=...}), so leaving them out of identity
   * made two imports with completely different sources compare equal (found reviewing #6409, item 3's sweep - the
   * same over-match direction {@link CaseExpression} had, on a statement rather than an expression node).
   */
  @Override
  public boolean equals(final Object o) {
    if (this == o)
      return true;
    if (o == null || getClass() != o.getClass())
      return false;
    final ImportDatabaseStatement that = (ImportDatabaseStatement) o;
    return Objects.equals(url, that.url) && Objects.equals(settings, that.settings);
  }

  @Override
  public int hashCode() {
    return Objects.hash(url, settings);
  }

  @Override
  public Statement copy() {
    final ImportDatabaseStatement result = new ImportDatabaseStatement();
    result.url = this.url;
    // WITHOUT THIS, A COPY SILENTLY DROPS EVERY 'WITH ...' SETTING - THE SAME DEFECT BackupDatabaseStatement HAD
    // (#6080). FOR IMPORT THE SETTINGS ARE THE STATEMENT: WITHOUT THEM AN 'IMPORT DATABASE WITH vertices=...' HAS NO
    // SOURCE AT ALL
    result.settings.putAll(this.settings);
    return result;
  }
}
/* ParserGeneratorCC - OriginalChecksum=ed8df9761ba25c4fca4bc31ece14a5f3 (do not edit this line) */
