/*
 * Copyright © 2021-present Arcade Data Ltd (info@arcadedata.com)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * SPDX-FileCopyrightText: 2021-present Arcade Data Ltd (info@arcadedata.com)
 * SPDX-License-Identifier: Apache-2.0
 */
/* Generated By:JJTree: Do not edit this line. OProjection.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=O,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_USERTYPE_VISIBILITY_PUBLIC=true */
package com.arcadedb.query.sql.parser;

import com.arcadedb.database.Document;
import com.arcadedb.exception.CommandSQLParsingException;
import com.arcadedb.query.sql.executor.CommandContext;
import com.arcadedb.query.sql.executor.Result;
import com.arcadedb.query.sql.executor.ResultInternal;
import com.arcadedb.schema.Property;

import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Set;
import java.util.stream.Collectors;

import static com.arcadedb.schema.Property.RID_PROPERTY;

public class Projection extends SimpleNode {

  public boolean distinct = false;

  public List<ProjectionItem> items;
  // runtime
  /**
   * The aliases {@code SELECT *, !alias} excludes. Volatile, and published by a single write in
   * {@link #initExcludes()} - see that method for why a shared, per-statement {@link Projection} needs both.
   */
  private volatile Set<String> excludes;
  /**
   * What every explicit (non-{@code *}) projection item publishes under its alias: the name of the source column
   * for a plain, unqualified column reference ({@code d}, or {@code d AS x} - not {@code d.sub}, not an
   * expression, not a nested projection), and a NULL VALUE for everything else. Lets a row this projection
   * produces report the schema type of the column each value came from, which its Java class does not always say
   * (issue #7638, and see {@link com.arcadedb.query.sql.executor.Result#getPropertyType}).
   * <p>
   * COMPUTED ITEMS ARE RECORDED TOO, as the marker, and that is not redundant. {@code SELECT *, n + 1 AS d} keeps
   * the backing element AND publishes a computed value under a name the element also has, so a lookup that fell
   * through to the element would answer with column {@code d}'s declared type for a value that is not column
   * {@code d}'s at all - a DATE verdict for an integer, and DATE formatting for any temporal the expression
   * happened to produce. A null VALUE says "this alias is this projection's, and it has no source column", which
   * a missing KEY - "this projection never mentioned it" - does not; the two are told apart by
   * {@code containsKey}, which is why a null value is stored rather than the entry being skipped (found reviewing
   * review).
   * <p>
   * Computed once and never mutated afterwards, alongside {@link #excludes} and for the same reason: a
   * {@link Projection} is cached per statement and shared by every row and every thread executing it, so this must
   * not become per-row work, and the map handed to a row must be safe to read concurrently.
   */
  private volatile Map<String, String> sourceColumns;

  public Projection(final List<ProjectionItem> items, final boolean distinct) {
    this.items = items;
    this.distinct = distinct;
    //TODO make the whole class immutable!
  }

  public Projection() {
  }

  public List<ProjectionItem> getItems() {
    return items;
  }

  public void setItems(final List<ProjectionItem> items) {
    this.items = items;
  }

  @Override
  public void toString(final Map<String, Object> params, final StringBuilder builder) {
    if (items == null)
      return;

    boolean first = true;

    if (distinct)
      builder.append("DISTINCT ");

    // print * before
    for (final ProjectionItem item : items) {
      if (item.isAll()) {
        if (!first)
          builder.append(", ");

        item.toString(params, builder);
        first = false;
      }
    }

    // and then the rest of the projections
    for (final ProjectionItem item : items) {
      if (!item.isAll()) {
        if (!first)
          builder.append(", ");

        item.toString(params, builder);
        first = false;
      }
    }
  }

  public Result calculateSingle(final CommandContext context, final Result record) {
    initExcludes();
    // ONE READ OF EACH, held for the whole row. Both fields are volatile (see initExcludes), and re-reading them
    // per use would both cost a volatile read per property and let one row see two different - though
    // content-identical - instances if an initialization race is in flight.
    final Set<String> excludedAliases = excludes;
    final Map<String, String> projectedColumns = sourceColumns;

    if (isExpand())
      throw new IllegalStateException("This is an expand projection, it cannot be calculated as a single result" + this);

    if (items.size() == 1 &&
        items.getFirst().getExpression() != null &&
        Property.THIS_PROPERTY.equals(items.getFirst().getExpression().toString()) &&
        items.getFirst().nestedProjection == null)
      return record;

    final ResultInternal result = new ResultInternal(context.getDatabase());
    for (final ProjectionItem item : items) {
      if (item.exclude)
        continue;

      if (item.isAll()) {
        result.setElement(record.toElement());

        // `hidden` is a schema annotation only, and has been since #2378 removed database-level support for it:
        // ALTER PROPERTY still records the flag and SHOW/schema introspection still report it, but no read path
        // filters on it. This loop used to, which made `SELECT *` disagree with a bare `SELECT` on the same row -
        // and the disagreement was invisible for a year because ResultInternal.getPropertyNames() unioned the
        // element's names back over the top of it, until #5613 removed that union and left the filter exposed.
        // Do not reinstate it here: hiding a property from a projection but not from the record that backs it is
        // not a security boundary, it only makes the two spellings of "give me everything" return different rows.
        for (final String alias : record.getPropertyNames()) {
          if (excludedAliases.contains(alias))
            continue;
          Object value = item.convert(record.getProperty(alias));
          if (item.nestedProjection != null) {
            value = item.nestedProjection.apply(item.expression, value, context);
          }
          result.setProperty(alias, value);
        }

        record.getElement().ifPresent(doc -> {
          if (!excludedAliases.contains(RID_PROPERTY) && doc.getIdentity() != null) {
            result.setProperty(RID_PROPERTY, doc.getIdentity());
          }
          if (!excludedAliases.contains(Property.TYPE_PROPERTY)) {
            result.setProperty(Property.TYPE_PROPERTY, doc.getType().getName());
          }

        });
      } else {
        result.setProperty(item.getProjectionAliasAsString(), item.execute(record, context));
      }
    }

    // Two reference writes, so a column-list projection's non-element row can still say which column each value
    // came from (issue #7638). Skipped entirely when there is nothing to say - an untyped source, or a projection
    // with no plain column reference in it.
    if (!projectedColumns.isEmpty()) {
      final Document sourceElement = record.isElement() ? record.toElement() : null;
      if (sourceElement != null && sourceElement.getType() != null)
        result.setProjectionSource(sourceElement.getType(), projectedColumns);
    }

    for (final String key : record.getMetadataKeys()) {
      if (!result.getMetadataKeys().contains(key))
        result.setMetadata(key, record.getMetadata(key));
    }
    return result;
  }

  /**
   * Computes the two per-statement lookups this projection needs, once.
   * <p>
   * BOTH ARE BUILT INTO A LOCAL AND PUBLISHED BY A SINGLE WRITE, and both fields are {@code volatile}. A
   * {@link Projection} belongs to a statement held in the SQL statement cache and is shared by every thread
   * executing that statement, so a racing initialization here is expected rather than exotic. Racing to compute
   * the same value twice is harmless - the result is identical and the loser's copy is simply dropped - but
   * publishing a HALF-BUILT one is not, and {@code excludes} used to do exactly that: it assigned the empty
   * {@code HashSet} to the field and only then filled it, so a second thread could read a non-null, INCOMPLETE
   * set and fail to exclude a property that {@code SELECT *, !secret} had excluded. Building into a local fixes
   * the ordering, and {@code volatile} fixes the JMM half of it - without it a reader can see the reference
   * before the collection's own internal state. Found in review; {@code sourceColumns} was written this
   * way from the start, and {@code excludes} now matches it.
   */
  private void initExcludes() {
    if (excludes == null) {
      Set<String> resolvedExcludes = null;
      for (final ProjectionItem item : items) {
        if (item.exclude) {
          if (resolvedExcludes == null)
            resolvedExcludes = new HashSet<>();

          resolvedExcludes.add(item.getProjectionAliasAsString());
        }
      }

      excludes = resolvedExcludes != null ? Collections.unmodifiableSet(resolvedExcludes) : Collections.emptySet();
    }

    if (sourceColumns == null) {
      Map<String, String> resolved = null;
      for (final ProjectionItem item : items) {
        if (item.exclude || item.isAll())
          continue;

        final Expression expression = item.getExpression();
        // isBaseIdentifier() is exactly "a bare column name and nothing else": no traversal, no method, no
        // arithmetic - so getDefaultAlias() names the source column, and the value published under the item's
        // alias IS that column's value (ProjectionItem.convert only unwraps iterators and result sets). Anything
        // else - an expression, a nested projection - publishes a value with no source column, and is recorded as
        // the marker rather than skipped, so a lookup cannot fall through to a same-named backing property.
        final boolean plainColumn = item.nestedProjection == null && expression != null && expression.isBaseIdentifier();

        if (resolved == null)
          resolved = new HashMap<>(items.size());
        resolved.put(item.getProjectionAliasAsString(),
            plainColumn ? expression.getDefaultAlias().getStringValue() : null);
      }
      sourceColumns = resolved != null ? Collections.unmodifiableMap(resolved) : Collections.emptyMap();
    }
  }

  public boolean isExpand() {
    return items != null && items.size() == 1 && items.getFirst().isExpand();
  }

  public void validate() {
    if (items != null && items.size() > 1) {
      for (final ProjectionItem item : items) {
        if (item.isExpand())
          throw new CommandSQLParsingException("Cannot execute a query with expand() together with other projections");
      }
    }
  }

  public Projection getExpandContent() {
    final Projection result = new Projection();
    result.setItems(new ArrayList<>());
    result.getItems().add(this.getItems().getFirst().getExpandContent());
    return result;
  }

  public List<String> getAllAliases() {
    return items.stream().map(ProjectionItem::getProjectionAliasAsString).collect(Collectors.toList());
  }

  public Projection copy() {
    final Projection result = new Projection();
    if (items != null)
      result.items = items.stream().map(ProjectionItem::copy).collect(Collectors.toList());

    result.distinct = distinct;
    return result;
  }

  @Override
  public boolean equals(final Object o) {
    if (this == o)
      return true;
    if (o == null || getClass() != o.getClass())
      return false;

    final Projection that = (Projection) o;

    return Objects.equals(items, that.items);
  }

  @Override
  public int hashCode() {
    return items != null ? items.hashCode() : 0;
  }

  public boolean isDistinct() {
    return distinct;
  }

  public void setDistinct(final boolean distinct) {
    this.distinct = distinct;
  }

  public void extractSubQueries(final SubQueryCollector collector) {
    if (items != null) {
      for (final ProjectionItem item : items) {
        item.extractSubQueries(collector);
      }
    }
  }

  public boolean refersToParent() {
    for (final ProjectionItem item : items) {
      if (item.refersToParent())
        return true;
    }
    return false;
  }

  @Override
  protected SimpleNode[] getCacheableElements() {
    return items.toArray(new ProjectionItem[items.size()]);
  }
  @Override
  public Map<String, Object> toJSON() {
    final Map<String, Object> json = super.toJSON();

    json.put("distinct", distinct);
    if (items != null) {
      json.put("items", items);
    }

    return json;
  }

}
/* JavaCC - OriginalChecksum=3a650307b53bae626dc063c4b35e62c3 (do not edit this line) */
