/* Generated By:JJTree&JavaCC: Do not edit this line. SqlParserConstants.java */
package com.arcadedb.query.sql.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SqlParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int FORMAL_COMMENT = 8;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 9;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 11;
  /** RegularExpression Id. */
  int ALIGN = 12;
  /** RegularExpression Id. */
  int BATCH = 13;
  /** RegularExpression Id. */
  int SELECT = 14;
  /** RegularExpression Id. */
  int TRAVERSE = 15;
  /** RegularExpression Id. */
  int MATCH = 16;
  /** RegularExpression Id. */
  int INSERT = 17;
  /** RegularExpression Id. */
  int CREATE = 18;
  /** RegularExpression Id. */
  int CUSTOM = 19;
  /** RegularExpression Id. */
  int DELETE = 20;
  /** RegularExpression Id. */
  int DOCUMENT = 21;
  /** RegularExpression Id. */
  int VERTEX = 22;
  /** RegularExpression Id. */
  int EDGE = 23;
  /** RegularExpression Id. */
  int UPDATE = 24;
  /** RegularExpression Id. */
  int UPSERT = 25;
  /** RegularExpression Id. */
  int FROM = 26;
  /** RegularExpression Id. */
  int TO = 27;
  /** RegularExpression Id. */
  int WHERE = 28;
  /** RegularExpression Id. */
  int WHILE = 29;
  /** RegularExpression Id. */
  int INTO = 30;
  /** RegularExpression Id. */
  int VALUE = 31;
  /** RegularExpression Id. */
  int VALUES = 32;
  /** RegularExpression Id. */
  int SET = 33;
  /** RegularExpression Id. */
  int ADD = 34;
  /** RegularExpression Id. */
  int PUT = 35;
  /** RegularExpression Id. */
  int MERGE = 36;
  /** RegularExpression Id. */
  int CONTENT = 37;
  /** RegularExpression Id. */
  int REMOVE = 38;
  /** RegularExpression Id. */
  int INCREMENT = 39;
  /** RegularExpression Id. */
  int AND = 40;
  /** RegularExpression Id. */
  int OR = 41;
  /** RegularExpression Id. */
  int NULL = 42;
  /** RegularExpression Id. */
  int DEFINE = 43;
  /** RegularExpression Id. */
  int DEFINED = 44;
  /** RegularExpression Id. */
  int ORDER_BY = 45;
  /** RegularExpression Id. */
  int GROUP_BY = 46;
  /** RegularExpression Id. */
  int BY = 47;
  /** RegularExpression Id. */
  int BREAK = 48;
  /** RegularExpression Id. */
  int LIMIT = 49;
  /** RegularExpression Id. */
  int SKIP2 = 50;
  /** RegularExpression Id. */
  int ERROR2 = 51;
  /** RegularExpression Id. */
  int OF = 52;
  /** RegularExpression Id. */
  int OFFSET = 53;
  /** RegularExpression Id. */
  int TIMEOUT = 54;
  /** RegularExpression Id. */
  int ASC = 55;
  /** RegularExpression Id. */
  int AS = 56;
  /** RegularExpression Id. */
  int DESC = 57;
  /** RegularExpression Id. */
  int RETURN = 58;
  /** RegularExpression Id. */
  int BEFORE = 59;
  /** RegularExpression Id. */
  int AFTER = 60;
  /** RegularExpression Id. */
  int RECORD = 61;
  /** RegularExpression Id. */
  int WAIT = 62;
  /** RegularExpression Id. */
  int RETRY = 63;
  /** RegularExpression Id. */
  int LET = 64;
  /** RegularExpression Id. */
  int CHECK = 65;
  /** RegularExpression Id. */
  int UNSAFE = 66;
  /** RegularExpression Id. */
  int STRATEGY = 67;
  /** RegularExpression Id. */
  int DEPTH_FIRST = 68;
  /** RegularExpression Id. */
  int BREADTH_FIRST = 69;
  /** RegularExpression Id. */
  int NEAR = 70;
  /** RegularExpression Id. */
  int WITH = 71;
  /** RegularExpression Id. */
  int WITHIN = 72;
  /** RegularExpression Id. */
  int UNWIND = 73;
  /** RegularExpression Id. */
  int MAXDEPTH = 74;
  /** RegularExpression Id. */
  int MINDEPTH = 75;
  /** RegularExpression Id. */
  int TYPE = 76;
  /** RegularExpression Id. */
  int SUPERTYPE = 77;
  /** RegularExpression Id. */
  int TYPES = 78;
  /** RegularExpression Id. */
  int EXCEPTION = 79;
  /** RegularExpression Id. */
  int PROFILE = 80;
  /** RegularExpression Id. */
  int ON = 81;
  /** RegularExpression Id. */
  int OFF = 82;
  /** RegularExpression Id. */
  int TRUNCATE = 83;
  /** RegularExpression Id. */
  int POLYMORPHIC = 84;
  /** RegularExpression Id. */
  int FIND = 85;
  /** RegularExpression Id. */
  int EXTENDS = 86;
  /** RegularExpression Id. */
  int BACKUP = 87;
  /** RegularExpression Id. */
  int BUCKETS = 88;
  /** RegularExpression Id. */
  int BUCKETSELECTIONSTRATEGY = 89;
  /** RegularExpression Id. */
  int ALTER = 90;
  /** RegularExpression Id. */
  int NAME = 91;
  /** RegularExpression Id. */
  int ADDBUCKET = 92;
  /** RegularExpression Id. */
  int REMOVEBUCKET = 93;
  /** RegularExpression Id. */
  int DROP = 94;
  /** RegularExpression Id. */
  int PROPERTY = 95;
  /** RegularExpression Id. */
  int HIDDEN = 96;
  /** RegularExpression Id. */
  int FORCE = 97;
  /** RegularExpression Id. */
  int SCHEMA = 98;
  /** RegularExpression Id. */
  int INDEX = 99;
  /** RegularExpression Id. */
  int NULL_STRATEGY = 100;
  /** RegularExpression Id. */
  int ENGINE = 101;
  /** RegularExpression Id. */
  int METADATA = 102;
  /** RegularExpression Id. */
  int REBUILD = 103;
  /** RegularExpression Id. */
  int FORMAT = 104;
  /** RegularExpression Id. */
  int OVERWRITE = 105;
  /** RegularExpression Id. */
  int EXPORT = 106;
  /** RegularExpression Id. */
  int IMPORT = 107;
  /** RegularExpression Id. */
  int DATABASE = 108;
  /** RegularExpression Id. */
  int OPTIMIZE = 109;
  /** RegularExpression Id. */
  int LINK = 110;
  /** RegularExpression Id. */
  int INVERSE = 111;
  /** RegularExpression Id. */
  int EXPLAIN = 112;
  /** RegularExpression Id. */
  int GRANT = 113;
  /** RegularExpression Id. */
  int REVOKE = 114;
  /** RegularExpression Id. */
  int READ = 115;
  /** RegularExpression Id. */
  int EXECUTE = 116;
  /** RegularExpression Id. */
  int ALL = 117;
  /** RegularExpression Id. */
  int NONE = 118;
  /** RegularExpression Id. */
  int FUNCTION = 119;
  /** RegularExpression Id. */
  int PARAMETERS = 120;
  /** RegularExpression Id. */
  int LANGUAGE = 121;
  /** RegularExpression Id. */
  int BEGIN = 122;
  /** RegularExpression Id. */
  int COMMIT = 123;
  /** RegularExpression Id. */
  int ROLLBACK = 124;
  /** RegularExpression Id. */
  int IF = 125;
  /** RegularExpression Id. */
  int ELSE = 126;
  /** RegularExpression Id. */
  int CONTINUE = 127;
  /** RegularExpression Id. */
  int FAIL = 128;
  /** RegularExpression Id. */
  int FIX = 129;
  /** RegularExpression Id. */
  int ISOLATION = 130;
  /** RegularExpression Id. */
  int SLEEP = 131;
  /** RegularExpression Id. */
  int CONSOLE = 132;
  /** RegularExpression Id. */
  int START = 133;
  /** RegularExpression Id. */
  int OPTIONAL = 134;
  /** RegularExpression Id. */
  int COUNT = 135;
  /** RegularExpression Id. */
  int DISTINCT = 136;
  /** RegularExpression Id. */
  int EXISTS = 137;
  /** RegularExpression Id. */
  int FOREACH = 138;
  /** RegularExpression Id. */
  int MOVE = 139;
  /** RegularExpression Id. */
  int DEPTH_ALIAS = 140;
  /** RegularExpression Id. */
  int PATH_ALIAS = 141;
  /** RegularExpression Id. */
  int IDENTIFIED = 142;
  /** RegularExpression Id. */
  int RID = 143;
  /** RegularExpression Id. */
  int SYSTEM = 144;
  /** RegularExpression Id. */
  int UNIDIRECTIONAL = 145;
  /** RegularExpression Id. */
  int THIS = 146;
  /** RegularExpression Id. */
  int RECORD_ATTRIBUTE = 147;
  /** RegularExpression Id. */
  int RID_ATTR = 148;
  /** RegularExpression Id. */
  int RID_STRING = 149;
  /** RegularExpression Id. */
  int OUT_ATTR = 150;
  /** RegularExpression Id. */
  int IN_ATTR = 151;
  /** RegularExpression Id. */
  int TYPE_ATTR = 152;
  /** RegularExpression Id. */
  int RID_ID_ATTR = 153;
  /** RegularExpression Id. */
  int RID_POS_ATTR = 154;
  /** RegularExpression Id. */
  int FIELDS_ATTR = 155;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 156;
  /** RegularExpression Id. */
  int DECIMAL_LITERAL = 157;
  /** RegularExpression Id. */
  int HEX_LITERAL = 158;
  /** RegularExpression Id. */
  int OCTAL_LITERAL = 159;
  /** RegularExpression Id. */
  int FLOATING_POINT_LITERAL = 160;
  /** RegularExpression Id. */
  int DECIMAL_FLOATING_POINT_LITERAL = 161;
  /** RegularExpression Id. */
  int DECIMAL_EXPONENT = 162;
  /** RegularExpression Id. */
  int HEXADECIMAL_FLOATING_POINT_LITERAL = 163;
  /** RegularExpression Id. */
  int HEXADECIMAL_EXPONENT = 164;
  /** RegularExpression Id. */
  int CHARACTER_LITERAL = 165;
  /** RegularExpression Id. */
  int STRING_LITERAL = 166;
  /** RegularExpression Id. */
  int INTEGER_RANGE = 167;
  /** RegularExpression Id. */
  int ELLIPSIS_INTEGER_RANGE = 168;
  /** RegularExpression Id. */
  int TRUE = 169;
  /** RegularExpression Id. */
  int FALSE = 170;
  /** RegularExpression Id. */
  int LPAREN = 171;
  /** RegularExpression Id. */
  int RPAREN = 172;
  /** RegularExpression Id. */
  int LBRACE = 173;
  /** RegularExpression Id. */
  int RBRACE = 174;
  /** RegularExpression Id. */
  int LBRACKET = 175;
  /** RegularExpression Id. */
  int RBRACKET = 176;
  /** RegularExpression Id. */
  int SEMICOLON = 177;
  /** RegularExpression Id. */
  int COMMA = 178;
  /** RegularExpression Id. */
  int DOT = 179;
  /** RegularExpression Id. */
  int AT = 180;
  /** RegularExpression Id. */
  int DOLLAR = 181;
  /** RegularExpression Id. */
  int BACKTICK = 182;
  /** RegularExpression Id. */
  int EQ = 183;
  /** RegularExpression Id. */
  int EQEQ = 184;
  /** RegularExpression Id. */
  int NSEQ = 185;
  /** RegularExpression Id. */
  int LT = 186;
  /** RegularExpression Id. */
  int GT = 187;
  /** RegularExpression Id. */
  int BANG = 188;
  /** RegularExpression Id. */
  int TILDE = 189;
  /** RegularExpression Id. */
  int HOOK = 190;
  /** RegularExpression Id. */
  int COLON = 191;
  /** RegularExpression Id. */
  int LE = 192;
  /** RegularExpression Id. */
  int GE = 193;
  /** RegularExpression Id. */
  int NE = 194;
  /** RegularExpression Id. */
  int NEQ = 195;
  /** RegularExpression Id. */
  int SC_OR = 196;
  /** RegularExpression Id. */
  int SC_AND = 197;
  /** RegularExpression Id. */
  int INCR = 198;
  /** RegularExpression Id. */
  int DECR = 199;
  /** RegularExpression Id. */
  int PLUS = 200;
  /** RegularExpression Id. */
  int MINUS = 201;
  /** RegularExpression Id. */
  int STAR = 202;
  /** RegularExpression Id. */
  int SLASH = 203;
  /** RegularExpression Id. */
  int BIT_AND = 204;
  /** RegularExpression Id. */
  int NULL_COALESCING = 205;
  /** RegularExpression Id. */
  int BIT_OR = 206;
  /** RegularExpression Id. */
  int XOR = 207;
  /** RegularExpression Id. */
  int REM = 208;
  /** RegularExpression Id. */
  int LSHIFT = 209;
  /** RegularExpression Id. */
  int PLUSASSIGN = 210;
  /** RegularExpression Id. */
  int MINUSASSIGN = 211;
  /** RegularExpression Id. */
  int STARASSIGN = 212;
  /** RegularExpression Id. */
  int SLASHASSIGN = 213;
  /** RegularExpression Id. */
  int ANDASSIGN = 214;
  /** RegularExpression Id. */
  int ORASSIGN = 215;
  /** RegularExpression Id. */
  int XORASSIGN = 216;
  /** RegularExpression Id. */
  int REMASSIGN = 217;
  /** RegularExpression Id. */
  int LSHIFTASSIGN = 218;
  /** RegularExpression Id. */
  int RSIGNEDSHIFTASSIGN = 219;
  /** RegularExpression Id. */
  int RUNSIGNEDSHIFTASSIGN = 220;
  /** RegularExpression Id. */
  int RSHIFT = 221;
  /** RegularExpression Id. */
  int RUNSIGNEDSHIFT = 222;
  /** RegularExpression Id. */
  int ELLIPSIS = 223;
  /** RegularExpression Id. */
  int RANGE = 224;
  /** RegularExpression Id. */
  int NOT = 225;
  /** RegularExpression Id. */
  int IN = 226;
  /** RegularExpression Id. */
  int LIKE = 227;
  /** RegularExpression Id. */
  int ILIKE = 228;
  /** RegularExpression Id. */
  int IS = 229;
  /** RegularExpression Id. */
  int BETWEEN = 230;
  /** RegularExpression Id. */
  int CONTAINS = 231;
  /** RegularExpression Id. */
  int CONTAINSALL = 232;
  /** RegularExpression Id. */
  int CONTAINSANY = 233;
  /** RegularExpression Id. */
  int CONTAINSKEY = 234;
  /** RegularExpression Id. */
  int CONTAINSVALUE = 235;
  /** RegularExpression Id. */
  int CONTAINSTEXT = 236;
  /** RegularExpression Id. */
  int MATCHES = 237;
  /** RegularExpression Id. */
  int KEY = 238;
  /** RegularExpression Id. */
  int INSTANCEOF = 239;
  /** RegularExpression Id. */
  int BUCKET = 240;
  /** RegularExpression Id. */
  int IDENTIFIER = 241;
  /** RegularExpression Id. */
  int QUOTED_IDENTIFIER = 242;
  /** RegularExpression Id. */
  int INDEX_COLON = 243;
  /** RegularExpression Id. */
  int INDEXVALUES_IDENTIFIER = 244;
  /** RegularExpression Id. */
  int INDEXVALUESASC_IDENTIFIER = 245;
  /** RegularExpression Id. */
  int INDEXVALUESDESC_IDENTIFIER = 246;
  /** RegularExpression Id. */
  int BUCKET_IDENTIFIER = 247;
  /** RegularExpression Id. */
  int BUCKET_NUMBER_IDENTIFIER = 248;
  /** RegularExpression Id. */
  int HTTP_URL = 249;
  /** RegularExpression Id. */
  int HTTPS_URL = 250;
  /** RegularExpression Id. */
  int FILE_URL = 251;
  /** RegularExpression Id. */
  int CLASSPATH_URL = 252;
  /** RegularExpression Id. */
  int SCHEMA_IDENTIFIER = 253;
  /** RegularExpression Id. */
  int LETTER = 254;
  /** RegularExpression Id. */
  int PART_LETTER = 255;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_FORMAL_COMMENT = 1;
  /** Lexical state. */
  int IN_MULTI_LINE_COMMENT = 2;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<token of kind 6>",
    "\"/*\"",
    "\"*/\"",
    "\"*/\"",
    "<token of kind 10>",
    "<SINGLE_LINE_COMMENT>",
    "<ALIGN>",
    "<BATCH>",
    "<SELECT>",
    "<TRAVERSE>",
    "<MATCH>",
    "<INSERT>",
    "<CREATE>",
    "<CUSTOM>",
    "<DELETE>",
    "<DOCUMENT>",
    "<VERTEX>",
    "<EDGE>",
    "<UPDATE>",
    "<UPSERT>",
    "<FROM>",
    "<TO>",
    "<WHERE>",
    "<WHILE>",
    "<INTO>",
    "<VALUE>",
    "<VALUES>",
    "<SET>",
    "<ADD>",
    "<PUT>",
    "<MERGE>",
    "<CONTENT>",
    "<REMOVE>",
    "<INCREMENT>",
    "<AND>",
    "<OR>",
    "<NULL>",
    "<DEFINE>",
    "<DEFINED>",
    "<ORDER_BY>",
    "<GROUP_BY>",
    "<BY>",
    "<BREAK>",
    "<LIMIT>",
    "<SKIP2>",
    "<ERROR2>",
    "<OF>",
    "<OFFSET>",
    "<TIMEOUT>",
    "<ASC>",
    "<AS>",
    "<DESC>",
    "<RETURN>",
    "<BEFORE>",
    "<AFTER>",
    "<RECORD>",
    "<WAIT>",
    "<RETRY>",
    "<LET>",
    "<CHECK>",
    "<UNSAFE>",
    "<STRATEGY>",
    "<DEPTH_FIRST>",
    "<BREADTH_FIRST>",
    "<NEAR>",
    "<WITH>",
    "<WITHIN>",
    "<UNWIND>",
    "<MAXDEPTH>",
    "<MINDEPTH>",
    "<TYPE>",
    "<SUPERTYPE>",
    "<TYPES>",
    "<EXCEPTION>",
    "<PROFILE>",
    "<ON>",
    "<OFF>",
    "<TRUNCATE>",
    "<POLYMORPHIC>",
    "<FIND>",
    "<EXTENDS>",
    "<BACKUP>",
    "<BUCKETS>",
    "<BUCKETSELECTIONSTRATEGY>",
    "<ALTER>",
    "<NAME>",
    "<ADDBUCKET>",
    "<REMOVEBUCKET>",
    "<DROP>",
    "<PROPERTY>",
    "<HIDDEN>",
    "<FORCE>",
    "<SCHEMA>",
    "<INDEX>",
    "<NULL_STRATEGY>",
    "<ENGINE>",
    "<METADATA>",
    "<REBUILD>",
    "<FORMAT>",
    "<OVERWRITE>",
    "<EXPORT>",
    "<IMPORT>",
    "<DATABASE>",
    "<OPTIMIZE>",
    "<LINK>",
    "<INVERSE>",
    "<EXPLAIN>",
    "<GRANT>",
    "<REVOKE>",
    "<READ>",
    "<EXECUTE>",
    "<ALL>",
    "<NONE>",
    "<FUNCTION>",
    "<PARAMETERS>",
    "<LANGUAGE>",
    "<BEGIN>",
    "<COMMIT>",
    "<ROLLBACK>",
    "<IF>",
    "<ELSE>",
    "<CONTINUE>",
    "<FAIL>",
    "<FIX>",
    "<ISOLATION>",
    "<SLEEP>",
    "<CONSOLE>",
    "<START>",
    "<OPTIONAL>",
    "<COUNT>",
    "<DISTINCT>",
    "<EXISTS>",
    "<FOREACH>",
    "<MOVE>",
    "<DEPTH_ALIAS>",
    "<PATH_ALIAS>",
    "<IDENTIFIED>",
    "<RID>",
    "<SYSTEM>",
    "<UNIDIRECTIONAL>",
    "<THIS>",
    "<RECORD_ATTRIBUTE>",
    "<RID_ATTR>",
    "<RID_STRING>",
    "<OUT_ATTR>",
    "<IN_ATTR>",
    "<TYPE_ATTR>",
    "<RID_ID_ATTR>",
    "<RID_POS_ATTR>",
    "<FIELDS_ATTR>",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<DECIMAL_FLOATING_POINT_LITERAL>",
    "<DECIMAL_EXPONENT>",
    "<HEXADECIMAL_FLOATING_POINT_LITERAL>",
    "<HEXADECIMAL_EXPONENT>",
    "<CHARACTER_LITERAL>",
    "<STRING_LITERAL>",
    "<INTEGER_RANGE>",
    "<ELLIPSIS_INTEGER_RANGE>",
    "<TRUE>",
    "<FALSE>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"@\"",
    "\"$\"",
    "\"`\"",
    "\"=\"",
    "\"==\"",
    "\"<=>\"",
    "\"<\"",
    "\">\"",
    "\"!\"",
    "\"~\"",
    "\"?\"",
    "\":\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "\"<>\"",
    "\"||\"",
    "\"&&\"",
    "\"++\"",
    "\"--\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"&\"",
    "\"??\"",
    "\"|\"",
    "\"^\"",
    "\"%\"",
    "\"<<\"",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "\"/=\"",
    "\"&=\"",
    "\"|=\"",
    "\"^=\"",
    "\"%=\"",
    "\"<<=\"",
    "\">>=\"",
    "\">>>=\"",
    "\">>\"",
    "\">>>\"",
    "\"...\"",
    "\"..\"",
    "<NOT>",
    "<IN>",
    "<LIKE>",
    "<ILIKE>",
    "<IS>",
    "<BETWEEN>",
    "<CONTAINS>",
    "<CONTAINSALL>",
    "<CONTAINSANY>",
    "<CONTAINSKEY>",
    "<CONTAINSVALUE>",
    "<CONTAINSTEXT>",
    "<MATCHES>",
    "<KEY>",
    "<INSTANCEOF>",
    "<BUCKET>",
    "<IDENTIFIER>",
    "<QUOTED_IDENTIFIER>",
    "<INDEX_COLON>",
    "<INDEXVALUES_IDENTIFIER>",
    "<INDEXVALUESASC_IDENTIFIER>",
    "<INDEXVALUESDESC_IDENTIFIER>",
    "<BUCKET_IDENTIFIER>",
    "<BUCKET_NUMBER_IDENTIFIER>",
    "<HTTP_URL>",
    "<HTTPS_URL>",
    "<FILE_URL>",
    "<CLASSPATH_URL>",
    "<SCHEMA_IDENTIFIER>",
    "<LETTER>",
    "<PART_LETTER>",
    "\"#\"",
  };

}
