/* Generated by: ParserGeneratorCC: Do not edit this line. SqlParserTreeConstants.java Version 1.1.3 */
package com.arcadedb.query.sql.parser;

public interface SqlParserTreeConstants
{
  public int JJTRID = 0;
  public int JJTBUCKETIDENTIFIER = 1;
  public int JJTPARSE = 2;
  public int JJTPARSESCRIPT = 3;
  public int JJTPSTRING = 4;
  public int JJTIDENTIFIER = 5;
  public int JJTPINTEGER = 6;
  public int JJTFLOATINGPOINT = 7;
  public int JJTPNUMBER = 8;
  public int JJTSTATEMENT = 9;
  public int JJTSTATEMENTSEMICOLON = 10;
  public int JJTSTATEMENTINTERNAL = 11;
  public int JJTQUERYSTATEMENT = 12;
  public int JJTSELECTWITHOUTTARGETSTATEMENT = 13;
  public int JJTSELECTSTATEMENT = 14;
  public int JJTTRAVERSESTATEMENT = 15;
  public int JJTMATCHSTATEMENT = 16;
  public int JJTDELETESTATEMENT = 17;
  public int JJTDELETEVERTEXSTATEMENT = 18;
  public int JJTDELETEEDGESTATEMENT = 19;
  public int JJTDELETEEDGEBYRIDSTATEMENT = 20;
  public int JJTDELETEEDGEFROMTOSTATEMENT = 21;
  public int JJTDELETEEDGETOSTATEMENT = 22;
  public int JJTDELETEEDGEVTOSTATEMENT = 23;
  public int JJTDELETEEDGEWHERESTATEMENT = 24;
  public int JJTUPDATEEDGESTATEMENT = 25;
  public int JJTUPDATESTATEMENT = 26;
  public int JJTUPDATEOPERATIONS = 27;
  public int JJTUPDATEITEM = 28;
  public int JJTUPDATEINCREMENTITEM = 29;
  public int JJTUPDATEREMOVEITEM = 30;
  public int JJTUPDATEPUTITEM = 31;
  public int JJTUPDATEADDITEM = 32;
  public int JJTINSERTSTATEMENT = 33;
  public int JJTINSERTBODY = 34;
  public int JJTCREATEVERTEXSTATEMENTEMPTYNOTARGET = 35;
  public int JJTCREATEVERTEXSTATEMENTEMPTY = 36;
  public int JJTCREATEVERTEXSTATEMENT = 37;
  public int JJTCREATEVERTEXSTATEMENTNOTARGET = 38;
  public int JJTCREATEEDGESTATEMENT = 39;
  public int JJTINPUTPARAMETER = 40;
  public int JJTPOSITIONALPARAMETER = 41;
  public int JJTNAMEDPARAMETER = 42;
  public int JJTPROJECTION = 43;
  public int JJTPROJECTIONITEM = 44;
  public int JJTNESTEDPROJECTION = 45;
  public int JJTNESTEDPROJECTIONITEM = 46;
  public int JJTARRAYSELECTOR = 47;
  public int JJTARRAYNUMBERSELECTOR = 48;
  public int JJTARRAYSINGLEVALUESSELECTOR = 49;
  public int JJTARRAYRANGESELECTOR = 50;
  public int JJTALIAS = 51;
  public int JJTRECORDATTRIBUTE = 52;
  public int JJTFUNCTIONCALL = 53;
  public int JJTMETHODCALL = 54;
  public int JJTLEVELZEROIDENTIFIER = 55;
  public int JJTSUFFIXIDENTIFIER = 56;
  public int JJTBASEIDENTIFIER = 57;
  public int JJTMODIFIER = 58;
  public int JJTEXPRESSION = 59;
  public int JJTARRAYCONCATEXPRESSION = 60;
  public int JJTARRAYCONCATEXPRESSIONELEMENT = 61;
  public int JJTMATHEXPRESSION = 62;
  public int JJTFIRSTLEVELEXPRESSION = 63;
  public int JJTPARENTHESISEXPRESSION = 64;
  public int JJTBASEEXPRESSION = 65;
  public int JJTFROMCLAUSE = 66;
  public int JJTLETCLAUSE = 67;
  public int JJTLETITEM = 68;
  public int JJTFROMITEM = 69;
  public int JJTBUCKET = 70;
  public int JJTBUCKETLIST = 71;
  public int JJTSCHEMAIDENTIFIER = 72;
  public int JJTINDEXNAME = 73;
  public int JJTINDEXIDENTIFIER = 74;
  public int JJTWHERECLAUSE = 75;
  public int JJTORBLOCK = 76;
  public int JJTANDBLOCK = 77;
  public int JJTNOTBLOCK = 78;
  public int JJTPARENTHESISBLOCK = 79;
  public int JJTCONDITIONBLOCK = 80;
  public int JJTCOMPAREOPERATOR = 81;
  public int JJTLTOPERATOR = 82;
  public int JJTGTOPERATOR = 83;
  public int JJTNEOPERATOR = 84;
  public int JJTNEQOPERATOR = 85;
  public int JJTGEOPERATOR = 86;
  public int JJTLEOPERATOR = 87;
  public int JJTLIKEOPERATOR = 88;
  public int JJTNEAROPERATOR = 89;
  public int JJTWITHINOPERATOR = 90;
  public int JJTSCANDOPERATOR = 91;
  public int JJTCONTAINSKEYOPERATOR = 92;
  public int JJTCONTAINSVALUEOPERATOR = 93;
  public int JJTEQUALSCOMPAREOPERATOR = 94;
  public int JJTRIGHTBINARYCONDITION = 95;
  public int JJTBINARYCONDITION = 96;
  public int JJTCONTAINSVALUECONDITION = 97;
  public int JJTINSTANCEOFCONDITION = 98;
  public int JJTINDEXMATCHCONDITION = 99;
  public int JJTBETWEENCONDITION = 100;
  public int JJTISNULLCONDITION = 101;
  public int JJTISNOTNULLCONDITION = 102;
  public int JJTISDEFINEDCONDITION = 103;
  public int JJTISNOTDEFINEDCONDITION = 104;
  public int JJTCONTAINSCONDITION = 105;
  public int JJTINOPERATOR = 106;
  public int JJTINCONDITION = 107;
  public int JJTNOTINCONDITION = 108;
  public int JJTCONTAINSALLCONDITION = 109;
  public int JJTCONTAINSANYCONDITION = 110;
  public int JJTCONTAINSTEXTCONDITION = 111;
  public int JJTMATCHESCONDITION = 112;
  public int JJTORDERBY = 113;
  public int JJTGROUPBY = 114;
  public int JJTUNWIND = 115;
  public int JJTLIMIT = 116;
  public int JJTSKIP = 117;
  public int JJTTIMEOUT = 118;
  public int JJTWAIT = 119;
  public int JJTRETRY = 120;
  public int JJTPCOLLECTION = 121;
  public int JJTTRAVERSEPROJECTIONITEM = 122;
  public int JJTJSON = 123;
  public int JJTMATCHEXPRESSION = 124;
  public int JJTMATCHPATHITEM = 125;
  public int JJTFIELDMATCHPATHITEM = 126;
  public int JJTMATCHPATHITEMFIRST = 127;
  public int JJTMULTIMATCHPATHITEM = 128;
  public int JJTMULTIMATCHPATHITEMARROWS = 129;
  public int JJTMATCHFILTER = 130;
  public int JJTMATCHFILTERITEM = 131;
  public int JJTOUTPATHITEM = 132;
  public int JJTINPATHITEM = 133;
  public int JJTBOTHPATHITEM = 134;
  public int JJTOUTPATHITEMOPT = 135;
  public int JJTINPATHITEMOPT = 136;
  public int JJTBOTHPATHITEMOPT = 137;
  public int JJTTRUNCATETYPESTATEMENT = 138;
  public int JJTTRUNCATEBUCKETSTATEMENT = 139;
  public int JJTTRUNCATERECORDSTATEMENT = 140;
  public int JJTCREATEDOCUMENTTYPESTATEMENT = 141;
  public int JJTCREATEVERTEXTYPESTATEMENT = 142;
  public int JJTCREATEEDGETYPESTATEMENT = 143;
  public int JJTALTERTYPESTATEMENT = 144;
  public int JJTDROPTYPESTATEMENT = 145;
  public int JJTIFNOTEXISTS = 146;
  public int JJTCREATEPROPERTYSTATEMENT = 147;
  public int JJTCREATEPROPERTYATTRIBUTESTATEMENT = 148;
  public int JJTALTERPROPERTYSTATEMENT = 149;
  public int JJTDROPPROPERTYSTATEMENT = 150;
  public int JJTCREATEINDEXSTATEMENT = 151;
  public int JJTREBUILDINDEXSTATEMENT = 152;
  public int JJTDROPINDEXSTATEMENT = 153;
  public int JJTCREATEBUCKETSTATEMENT = 154;
  public int JJTALTERBUCKETSTATEMENT = 155;
  public int JJTDROPBUCKETSTATEMENT = 156;
  public int JJTALTERDATABASESTATEMENT = 157;
  public int JJTCOMMANDLINEOPTION = 158;
  public int JJTEXPLAINSTATEMENT = 159;
  public int JJTPROFILESTATEMENT = 160;
  public int JJTLETSTATEMENT = 161;
  public int JJTBEGINSTATEMENT = 162;
  public int JJTCOMMITSTATEMENT = 163;
  public int JJTROLLBACKSTATEMENT = 164;
  public int JJTRETURNSTATEMENT = 165;
  public int JJTIFSTATEMENT = 166;
  public int JJTSLEEPSTATEMENT = 167;
  public int JJTFOREACHBLOCK = 168;
  public int JJTWHILEBLOCK = 169;
  public int JJTIMPORTDATABASESTATEMENT = 170;
  public int JJTEXPORTDATABASESTATEMENT = 171;
  public int JJTURL = 172;
  public int JJTBACKUPDATABASESTATEMENT = 173;
  public int JJTCHECKDATABASESTATEMENT = 174;
  public int JJTALIGNDATABASESTATEMENT = 175;


  public String[] jjtNodeName = {
    "Rid",
    "BucketIdentifier",
    "parse",
    "ParseScript",
    "PString",
    "Identifier",
    "PInteger",
    "FloatingPoint",
    "PNumber",
    "Statement",
    "StatementSemicolon",
    "StatementInternal",
    "QueryStatement",
    "SelectWithoutTargetStatement",
    "SelectStatement",
    "TraverseStatement",
    "MatchStatement",
    "DeleteStatement",
    "DeleteVertexStatement",
    "DeleteEdgeStatement",
    "DeleteEdgeByRidStatement",
    "DeleteEdgeFromToStatement",
    "DeleteEdgeToStatement",
    "DeleteEdgeVToStatement",
    "DeleteEdgeWhereStatement",
    "UpdateEdgeStatement",
    "UpdateStatement",
    "UpdateOperations",
    "UpdateItem",
    "UpdateIncrementItem",
    "UpdateRemoveItem",
    "UpdatePutItem",
    "UpdateAddItem",
    "InsertStatement",
    "InsertBody",
    "CreateVertexStatementEmptyNoTarget",
    "CreateVertexStatementEmpty",
    "CreateVertexStatement",
    "CreateVertexStatementNoTarget",
    "CreateEdgeStatement",
    "InputParameter",
    "PositionalParameter",
    "NamedParameter",
    "Projection",
    "ProjectionItem",
    "NestedProjection",
    "NestedProjectionItem",
    "ArraySelector",
    "ArrayNumberSelector",
    "ArraySingleValuesSelector",
    "ArrayRangeSelector",
    "Alias",
    "RecordAttribute",
    "FunctionCall",
    "MethodCall",
    "LevelZeroIdentifier",
    "SuffixIdentifier",
    "BaseIdentifier",
    "Modifier",
    "Expression",
    "ArrayConcatExpression",
    "ArrayConcatExpressionElement",
    "MathExpression",
    "FirstLevelExpression",
    "ParenthesisExpression",
    "BaseExpression",
    "FromClause",
    "LetClause",
    "LetItem",
    "FromItem",
    "Bucket",
    "BucketList",
    "SchemaIdentifier",
    "IndexName",
    "IndexIdentifier",
    "WhereClause",
    "OrBlock",
    "AndBlock",
    "NotBlock",
    "ParenthesisBlock",
    "ConditionBlock",
    "CompareOperator",
    "LtOperator",
    "GtOperator",
    "NeOperator",
    "NeqOperator",
    "GeOperator",
    "LeOperator",
    "LikeOperator",
    "NearOperator",
    "WithinOperator",
    "ScAndOperator",
    "ContainsKeyOperator",
    "ContainsValueOperator",
    "EqualsCompareOperator",
    "RightBinaryCondition",
    "BinaryCondition",
    "ContainsValueCondition",
    "InstanceofCondition",
    "IndexMatchCondition",
    "BetweenCondition",
    "IsNullCondition",
    "IsNotNullCondition",
    "IsDefinedCondition",
    "IsNotDefinedCondition",
    "ContainsCondition",
    "InOperator",
    "InCondition",
    "NotInCondition",
    "ContainsAllCondition",
    "ContainsAnyCondition",
    "ContainsTextCondition",
    "MatchesCondition",
    "OrderBy",
    "GroupBy",
    "Unwind",
    "Limit",
    "Skip",
    "Timeout",
    "Wait",
    "Retry",
    "PCollection",
    "TraverseProjectionItem",
    "Json",
    "MatchExpression",
    "MatchPathItem",
    "FieldMatchPathItem",
    "MatchPathItemFirst",
    "MultiMatchPathItem",
    "MultiMatchPathItemArrows",
    "MatchFilter",
    "MatchFilterItem",
    "OutPathItem",
    "InPathItem",
    "BothPathItem",
    "OutPathItemOpt",
    "InPathItemOpt",
    "BothPathItemOpt",
    "TruncateTypeStatement",
    "TruncateBucketStatement",
    "TruncateRecordStatement",
    "CreateDocumentTypeStatement",
    "CreateVertexTypeStatement",
    "CreateEdgeTypeStatement",
    "AlterTypeStatement",
    "DropTypeStatement",
    "IfNotExists",
    "CreatePropertyStatement",
    "CreatePropertyAttributeStatement",
    "AlterPropertyStatement",
    "DropPropertyStatement",
    "CreateIndexStatement",
    "RebuildIndexStatement",
    "DropIndexStatement",
    "CreateBucketStatement",
    "AlterBucketStatement",
    "DropBucketStatement",
    "AlterDatabaseStatement",
    "CommandLineOption",
    "ExplainStatement",
    "ProfileStatement",
    "LetStatement",
    "BeginStatement",
    "CommitStatement",
    "RollbackStatement",
    "ReturnStatement",
    "IfStatement",
    "SleepStatement",
    "ForEachBlock",
    "WhileBlock",
    "ImportDatabaseStatement",
    "ExportDatabaseStatement",
    "Url",
    "BackupDatabaseStatement",
    "CheckDatabaseStatement",
    "AlignDatabaseStatement",
  };
}
/* ParserGeneratorCC - OriginalChecksum=0dec94bf69545275c2e875e7030cc83a (do not edit this line) */
