/*
 * Copyright © 2021-present Arcade Data Ltd (info@arcadedata.com)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * SPDX-FileCopyrightText: 2021-present Arcade Data Ltd (info@arcadedata.com)
 * SPDX-License-Identifier: Apache-2.0
 */
/* Generated By:JJTree: Do not edit this line. OTruncateClassStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=O,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_USERTYPE_VISIBILITY_PUBLIC=true */
package com.arcadedb.query.sql.parser;

import com.arcadedb.GlobalConfiguration;
import com.arcadedb.database.Database;
import com.arcadedb.exception.CommandExecutionException;
import com.arcadedb.index.TypeIndex;
import com.arcadedb.index.lsm.LSMTreeIndexAbstract;
import com.arcadedb.query.sql.executor.CommandContext;
import com.arcadedb.query.sql.executor.InternalResultSet;
import com.arcadedb.query.sql.executor.ResultInternal;
import com.arcadedb.query.sql.executor.ResultSet;
import com.arcadedb.schema.DocumentType;
import com.arcadedb.schema.EdgeType;
import com.arcadedb.schema.IndexMetadata;
import com.arcadedb.schema.Schema;
import com.arcadedb.schema.TypeIndexBuilder;

import java.util.*;

/**
 * {@code TRUNCATE TYPE <type> [POLYMORPHIC] [UNSAFE]}.
 * <p>
 * The statement has two execution paths, picked by who owns the transaction - see
 * {@link TruncateRecordDeleter} for the rule and why it exists (issue #6220). Inside a caller's transaction the
 * deletes join it and the indexes are maintained per record, so a {@code ROLLBACK} puts every record back. With no
 * transaction active the statement owns one and takes the fast path: drop the indexes, delete in small committed
 * batches, rebuild the (empty) indexes.
 * <p>
 * Which one a caller gets is therefore entirely up to the caller. Embedded, the fast path is
 * {@code database.command("sql", "TRUNCATE TYPE ...")} with no {@code begin()} around it. Over HTTP the request's
 * auto-commit transaction is what makes the statement transactional, so {@code "autoCommit": false} in the request
 * payload selects the fast path for a bulk clear that does not need to be undoable.
 */
public class TruncateTypeStatement extends DDLStatement {
  public Identifier typeName;
  public boolean    polymorphic = false;
  public boolean    unsafe      = false;

  public TruncateTypeStatement() {
  }

  @Override
  public ResultSet executeDDL(final CommandContext context) {
    final Database db = context.getDatabase();
    final Schema schema = db.getSchema();
    final DocumentType typez = schema.getType(typeName.getStringValue());
    if (typez == null) {
      throw new CommandExecutionException("Schema Class not found: " + typeName);
    }

    // TRUNCATE deletes what scanType() finds, and scanType() reads the type's buckets directly - it never goes
    // through the planner, so the walk that issue #7477 gave SELECT and DELETE does not reach it. A lightweight
    // edge allocates no record, so those buckets are empty by construction: left alone, the statement would report
    // success having deleted nothing while every edge of the type is still live in the vertices holding it.
    //
    // Below, such a type is routed to DELETE FROM <type> instead (issue #7481): that statement already reaches
    // these edges correctly (issue #7477/#7478), through the same removal-safe walk GraphEngine.deleteEdge relies
    // on, so reusing it avoids re-implementing the read-modify-write hazard EdgeLinkedList.edgeIteratorForRemoval
    // exists for. Nothing here is lost by giving up the index-drop/rebuild speed-up truncateInOwnTransaction uses:
    // a lightweight type can hold no properties, so it has no index to drop in the first place.
    final boolean lightweight = EdgeType.holdsLightweightEdges(typez);

    // DELETE FROM <type> is unconditionally polymorphic (it walks the type's own buckets AND every subtype's, and
    // for a lightweight edge type resolves subtype edges the same way): there is no "bucket-only" reading of it to
    // fall back on the way there is for an ordinary TRUNCATE. So when the caller asked for the non-POLYMORPHIC
    // behaviour and a subtype exists, delegating would either delete a subtype's records the caller did not ask
    // for (silently wider than requested) or - if that were special-cased away - leave a lightweight subtype's
    // edges behind with no bucket for a future TRUNCATE to find them in (silently narrower). Both are worse than
    // refusing: a type with no subtypes at all has no such ambiguity, whichever way POLYMORPHIC was spelled.
    if (lightweight && !polymorphic && !typez.getSubTypes().isEmpty())
      throw new CommandExecutionException("'TRUNCATE TYPE' cannot be used on '" + typeName.getStringValue()
          + "' without POLYMORPHIC because it is a LIGHTWEIGHT edge type (or has one below it) with a subtype: "
          + "a lightweight edge has no bucket of its own to scope a non-polymorphic TRUNCATE to, so this would "
          + "either reach into '" + typeName.getStringValue() + "'s subtypes unasked or leave a subtype's "
          + "lightweight edges behind. Use 'TRUNCATE TYPE " + typeName.getStringValue()
          + " POLYMORPHIC' to delete every shape under it, or 'DELETE FROM " + typeName.getStringValue()
          + " WHERE ...' to scope it precisely. See issue #7481");

    // Database.countType() sums bucket record counts, and a LIGHTWEIGHT edge allocates none - it answers 0 for such
    // a type no matter how many edges it holds (issue #7477), which would let this guard through unconditionally
    // for exactly the type this method is about to delete via a walk rather than a bucket scan. The SQL count(*)
    // push-down already knows how to count such a type correctly (CountFromTypeStep routes it to the same vertex
    // walk SELECT uses), so it is reused here - skipped entirely when UNSAFE is already given, since the O(V+E)
    // walk would buy nothing the check below would use.
    final long recs = lightweight
        ? (unsafe ? 0 : countRecordsIncludingLightweightEdges(db, typeName))
        : context.getDatabase().countType(typeName.getStringValue(), polymorphic);
    if (recs > 0 && !unsafe) {
      if (typez.isSubTypeOf("V")) {
        throw new CommandExecutionException(
            "'TRUNCATE TYPE' command cannot be used on not empty vertex classes. Apply the 'UNSAFE' keyword to force it (at your own risk)");
      } else if (typez.isSubTypeOf("E")) {
        throw new CommandExecutionException(
            "'TRUNCATE TYPE' command cannot be used on not empty edge classes. Apply the 'UNSAFE' keyword to force it (at your own risk)");
      }
    }

    final InternalResultSet rs = new InternalResultSet();
    final Collection<DocumentType> subTypes = typez.getSubTypes();
    if (polymorphic && !unsafe) {// for multiple inheritance
      for (final DocumentType subType : subTypes) {
        final long subTypeRecs = context.getDatabase().countType(typeName.getStringValue(), false);
        if (subTypeRecs > 0) {
          if (subType.isSubTypeOf("V")) {
            throw new CommandExecutionException("'TRUNCATE TYPE' command cannot be used on not empty vertex classes (" + subType.getName()
                + "). Apply the 'UNSAFE' keyword to force it (at your own risk)");
          } else if (subType.isSubTypeOf("E")) {
            throw new CommandExecutionException("'TRUNCATE TYPE' command cannot be used on not empty edge classes (" + subType.getName()
                + "). Apply the 'UNSAFE' keyword to force it (at your own risk)");
          }
        }
      }
    }

    final boolean transactional = db.isTransactionActive();
    if (lightweight)
      truncateLightweightEdgeType(db, transactional);
    else if (transactional)
      truncateInCallerTransaction(db);
    else
      truncateInOwnTransaction(db, schema, typez);

    final ResultInternal result = new ResultInternal(context.getDatabase());
    result.setProperty("operation", "truncate type");
    result.setProperty("typeName", typeName.getStringValue());
    // Which of the two paths ran, so a caller can tell whether its ROLLBACK will put the records back. The old
    // behaviour was indistinguishable from the transactional one right up to the rollback that silently kept most of
    // the deletes (issue #6220), and an answer nobody can read is half a fix.
    result.setProperty("transactional", transactional);
    rs.add(result);

    return rs;
  }

  /**
   * Deletes a LIGHTWEIGHT edge type (or one with a LIGHTWEIGHT edge type below it, once POLYMORPHIC has cleared it
   * for that) by running {@code DELETE FROM <type>} through the query engine, rather than {@code scanType()}: that
   * statement already walks the vertices that hold such an edge and removes each one from both endpoints' lists
   * correctly (issue #7477/#7478), so this reuses it instead of re-deriving the same removal-safe walk.
   * <p>
   * {@code typeName.toString()}, not {@code getStringValue()}: the latter returns the plain, unescaped name, so a
   * type created with a name that needs back-tick quoting (a reserved word, or one with a space) would rebuild into
   * SQL text that fails to parse or, worse, is parsed as a different statement. {@code toString()} re-emits the
   * back-tick quoting the parser produced this identifier from in the first place, which is what it exists for.
   * <p>
   * Mirrors the caller-transaction-vs-own-transaction split the record-backed paths make, for the same reason
   * (issue #6220): inside a caller transaction the delete joins it, so a {@code ROLLBACK} puts the edges back;
   * with none active, this opens and closes its own so the statement is atomic on its own. The own-transaction
   * branch also carries over the batching {@link #truncateInOwnTransaction} uses (the same {@code BATCH} clause
   * {@code TruncateRecordDeleter} builds its own deleter around): a lightweight type has no index to protect from
   * LSM-Tree tombstones, but the batch size still bounds how large a single committed transaction - one Raft log
   * entry in HA - gets for a type with a very large number of edges (issue #4817).
   */
  private void truncateLightweightEdgeType(final Database db, final boolean transactional) {
    if (transactional) {
      db.command("sql", "DELETE FROM " + typeName).close();
      return;
    }

    final int batchSize = Math.max(1, db.getConfiguration().getValueAsInteger(GlobalConfiguration.TRUNCATE_BATCH_SIZE));

    db.begin();
    boolean success = false;
    try {
      db.command("sql", "DELETE FROM " + typeName + " BATCH " + batchSize).close();
      success = true;
    } finally {
      if (success)
        db.commit();
      else
        db.rollback();
    }
  }

  /**
   * Counts a LIGHTWEIGHT edge type's rows the way {@link com.arcadedb.query.sql.executor.CountFromTypeStep} already
   * does for {@code SELECT count(*)} - by running the query rather than reading {@code Database.countType()}, which
   * reads bucket record counts directly and answers 0 for such a type regardless of how many edges it holds.
   */
  private static long countRecordsIncludingLightweightEdges(final Database db, final Identifier typeName) {
    try (final ResultSet rs = db.query("sql", "SELECT count(*) AS c FROM " + typeName)) {
      return rs.hasNext() ? ((Number) rs.next().getProperty("c")).longValue() : 0L;
    }
  }

  /**
   * The caller owns the transaction, so this is one more operation inside it: every record is deleted in that
   * transaction, with the indexes maintained per record exactly as {@code DELETE FROM} does, and a {@code ROLLBACK}
   * puts all of them back (issue #6220).
   * <p>
   * Neither of the two speed-ups the {@linkplain #truncateInOwnTransaction own-transaction path} uses is available
   * here, and both for the same reason: they commit. Dropping the indexes is a schema change, which
   * {@code LocalSchema.recordFileChanges} applies immediately; batching means calling {@code commit()} on the
   * caller's transaction. Either one turns a subsequent {@code ROLLBACK} into a partial, silent data loss.
   */
  private void truncateInCallerTransaction(final Database db) {
    final RuntimeException failure = TruncateRecordDeleter.deleteAll(db, 0,
        callback -> db.scanType(typeName.getStringValue(), polymorphic, callback::test));

    // Report the failure rather than a partial truncate masquerading as success (issue #4817). The caller's
    // transaction is left untouched, so its own rollback undoes the deletes that did happen.
    if (failure != null)
      throw failure;
  }

  /**
   * No transaction was active, so the statement owns one and can use the fast path: drop the indexes, delete the
   * records in small committed batches, rebuild the (empty) indexes.
   * <p>
   * The index drop/rebuild is not only a speed-up (issue #4352): scanning + record-by-record delete with an in-loop
   * batched commit can leave LSM-Tree indexes full of stale tombstones, so the index ends up in an inconsistent state
   * (infinite-loop iteration, spurious duplicate-key errors). Dropping the indexes, clearing the records and
   * recreating the (empty) indexes is both faster and safer - and it is only ever correct here, where no caller
   * transaction can be committed through.
   */
  private void truncateInOwnTransaction(final Database db, final Schema schema, final DocumentType typez) {
    // Capture index definitions BEFORE truncating records: the drop below is a committed schema change and the
    // definitions are all that is left to rebuild from.
    final List<IndexDefinition> indexDefs = collectIndexDefinitions(typez, polymorphic);
    for (final IndexDefinition def : indexDefs)
      schema.dropIndex(def.name);

    final int batchSize = Math.max(1, db.getConfiguration().getValueAsInteger(GlobalConfiguration.TRUNCATE_BATCH_SIZE));

    final RuntimeException failure = TruncateRecordDeleter.deleteAllInOwnTransaction(db, batchSize,
        callback -> db.scanType(typeName.getStringValue(), polymorphic, callback::test),
        deletionFailure -> rebuildIndexes(db, schema, indexDefs, deletionFailure),
        "TYPE '" + typeName.getStringValue() + "'");

    // Report the failure rather than a partial truncate masquerading as success (issue #4817).
    if (failure != null)
      throw failure;
  }

  /**
   * Recreates the indexes dropped at the start of {@link #truncateInOwnTransaction}, inside that method's
   * transaction and before it is closed.
   * <p>
   * They are rebuilt in <b>every</b> case: on success they start empty since all records are gone; on failure they
   * are rebuilt over whatever records remain, so the schema is never left without the indexes it had - the
   * {@code dropIndex} is a committed schema change and nothing later can undo it. A subsequent retry/run re-drops
   * and re-empties them.
   * <p>
   * The rebuild survives the rollback that a failure triggers, and has to: the {@code dropIndex} above is a committed
   * schema change that nothing later can undo, so a rebuild discarded with the failing transaction would leave the
   * type carrying an EMPTY index over records that are all still there.
   *
   * @return the failure to carry on with: the one passed in, or the first rebuild failure when there was none.
   */
  private RuntimeException rebuildIndexes(final Database db, final Schema schema, final List<IndexDefinition> indexDefs,
      RuntimeException deletionFailure) {
    if (indexDefs.isEmpty())
      // Nothing to rebuild, so the deletion transaction is left exactly as it was for the caller to decide.
      return deletionFailure;

    // CLOSE OUT THE DELETION TRANSACTION FIRST, in whichever direction the outcome calls for: commit when the deletes
    // are good, so the build sees the empty buckets instead of repopulating the index with records that are logically
    // deleted but not yet flushed; roll back when they are not, so it sees the state that is going to survive.
    //
    // Either way the rebuild must not run INSIDE a transaction whose fate somebody else is about to decide, because a
    // build's entries now commit with the transaction it runs in (issue #6324, item 1): a rebuild left in the failing
    // one would be built and then thrown away with it, leaving the type with the empty index the committed drop had
    // already reduced it to. Deciding it here is also what leaves TruncateRecordDeleter with no transaction of its
    // own to close, which is the point.
    if (db.isTransactionActive()) {
      try {
        if (deletionFailure == null)
          db.commit();
        else
          db.rollback();
      } catch (final RuntimeException e) {
        if (deletionFailure == null)
          deletionFailure = e;
        else
          deletionFailure.addSuppressed(e);
      }
    }

    // Every definition is attempted, and one that cannot be recreated does not take the others with it. Each
    // create() opens and commits its own transaction, so abandoning the loop at the first failure would leave the
    // type missing indexes that had nothing wrong with them - the opposite of what rebuilding on failure at all is for.
    for (final IndexDefinition def : indexDefs) {
      try {
        recreateIndex(schema, def);
      } catch (final RuntimeException e) {
        if (deletionFailure == null)
          deletionFailure = e;
        else
          deletionFailure.addSuppressed(e);
      }
    }

    return deletionFailure;
  }

  private void recreateIndex(final Schema schema, final IndexDefinition def) {
    // withType() may swap the builder to a type-specific subclass (e.g. TypeLSMVectorIndexBuilder
    // for LSM_VECTOR), so call it first and keep the returned reference instead of chaining.
    final TypeIndexBuilder builder = schema.buildTypeIndex(def.typeName, def.propertyNames).withType(def.indexType);
    builder.withUnique(def.unique);
    builder.withPageSize(def.pageSize);
    builder.withNullStrategy(def.nullStrategy);

    // Type-specific metadata must be carried over, otherwise the recreated index loses its configuration: a vector
    // index comes back with dimensions 0 and rejects every insert (issue #4359), a full-text one with a different
    // analyzer and a different ranking, a geospatial one with a different cell size (issue #5742). withType() above
    // has already swapped in the builder subclass that owns those settings, so the polymorphic withMetadata() call
    // lands on the override that reinstates them - no per-index-type branch here to forget one.
    //
    // A copy - rather than the original reference - keeps the dropped index's per-index runtime state (notably the
    // vector index's buildState and the full-text corpus counters, which describe records that are about to be gone)
    // off the rebuilt one, and resets associatedBucketId so the per-bucket builder sets it during create().
    if (def.metadata != null)
      builder.withMetadata(def.metadata.copy(def.typeName, def.propertyNames, -1));

    builder.create();
  }

  private static List<IndexDefinition> collectIndexDefinitions(final DocumentType typez, final boolean polymorphic) {
    final List<IndexDefinition> defs = new ArrayList<>();
    final Set<String> seen = new HashSet<>();
    for (final TypeIndex index : typez.getAllIndexes(false))
      if (seen.add(index.getName()))
        defs.add(IndexDefinition.from(index));
    if (polymorphic)
      for (final DocumentType sub : typez.getSubTypes())
        for (final TypeIndex index : sub.getAllIndexes(false))
          if (seen.add(index.getName()))
            defs.add(IndexDefinition.from(index));
    return defs;
  }

  private static final class IndexDefinition {
    final String                              name;
    final String                              typeName;
    final String[]                            propertyNames;
    final Schema.INDEX_TYPE                   indexType;
    final boolean                             unique;
    final int                                 pageSize;
    final LSMTreeIndexAbstract.NULL_STRATEGY  nullStrategy;
    final IndexMetadata                       metadata;

    private IndexDefinition(final String name, final String typeName, final String[] propertyNames,
        final Schema.INDEX_TYPE indexType, final boolean unique, final int pageSize,
        final LSMTreeIndexAbstract.NULL_STRATEGY nullStrategy, final IndexMetadata metadata) {
      this.name = name;
      this.typeName = typeName;
      this.propertyNames = propertyNames;
      this.indexType = indexType;
      this.unique = unique;
      this.pageSize = pageSize;
      this.nullStrategy = nullStrategy;
      this.metadata = metadata;
    }

    static IndexDefinition from(final TypeIndex index) {
      final List<String> props = index.getPropertyNames();
      // getPageSizeForNewFile()/getMetadataForNewFile(), not getPageSize()/getMetadata(): this definition is replayed
      // through the creation path after the index has been dropped, so the page size carried over has to be one that
      // path accepts (#5713), and the configuration has to be the one the WRAPPER index types keep outside the
      // underlying LSM-Tree - analyzers, geohash resolution, sparse dimensionality (#5742).
      return new IndexDefinition(index.getName(), index.getTypeName(), props.toArray(new String[0]),
          index.getType(), index.isUnique(), index.getPageSizeForNewFile(), index.getNullStrategy(),
          index.getMetadataForNewFile());
    }
  }

  @Override
  public void toString(final Map<String, Object> params, final StringBuilder builder) {
    builder.append("TRUNCATE TYPE " + typeName.toString());
    if (polymorphic) {
      builder.append(" POLYMORPHIC");
    }
    if (unsafe) {
      builder.append(" UNSAFE");
    }
  }

  @Override
  public TruncateTypeStatement copy() {
    final TruncateTypeStatement result = new TruncateTypeStatement();
    result.typeName = typeName == null ? null : typeName.copy();
    result.polymorphic = polymorphic;
    result.unsafe = unsafe;
    return result;
  }

  @Override
  public boolean equals(final Object o) {
    if (this == o)
      return true;
    if (o == null || getClass() != o.getClass())
      return false;

    final TruncateTypeStatement that = (TruncateTypeStatement) o;

    if (polymorphic != that.polymorphic)
      return false;
    if (unsafe != that.unsafe)
      return false;
    return Objects.equals(typeName, that.typeName);
  }

  @Override
  public int hashCode() {
    int result = typeName != null ? typeName.hashCode() : 0;
    result = 31 * result + (polymorphic ? 1 : 0);
    result = 31 * result + (unsafe ? 1 : 0);
    return result;
  }
}
/* JavaCC - OriginalChecksum=301f993f6ba2893cb30c8f189674b974 (do not edit this line) */
