{{- if not .Values.arcadedb.credentials.rootPassword.secret.name }}
{{ $secret := (lookup "v1" "Secret" .Release.Namespace "arcadedb-credentials-secret") | default dict }}
apiVersion: v1
kind: Secret
metadata:
  name: arcadedb-credentials-secret
type: Opaque
data:
  # retrieve the secret data using lookup function and when not exists, return an empty dictionary / map as result
  {{- $secretData := (get $secret "data") | default dict }}
  {{- $rootPassword := (get $secretData "rootPassword") | default (randAlphaNum 32 | b64enc) }}
  rootPassword: {{ $rootPassword }}
{{- end }}
