sudo: false
language: java
branches:
  only:
  - develop
jdk:
  - oraclejdk8
before_install:
  - sed -i.bak -e 's|https://nexus.codehaus.org/snapshots/|https://oss.sonatype.org/content/repositories/codehaus-snapshots/|g' ~/.m2/settings.xml
