/*
 * Copyright © 2021-present Arcade Data Ltd (info@arcadedata.com)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * SPDX-FileCopyrightText: 2021-present Arcade Data Ltd (info@arcadedata.com)
 * SPDX-License-Identifier: Apache-2.0
 */
package com.arcadedb.integration.importer;

import com.arcadedb.database.Database;
import com.arcadedb.database.DatabaseFactory;
import com.arcadedb.integration.TestHelper;
import com.arcadedb.integration.importer.format.CSVImporterFormat;
import com.arcadedb.integration.importer.format.FormatImporter;
import com.arcadedb.integration.importer.format.JSONImporterFormat;
import com.arcadedb.integration.importer.format.RDFImporterFormat;
import com.arcadedb.integration.importer.format.XMLImporterFormat;
import com.arcadedb.schema.Schema;
import com.arcadedb.schema.Type;
import com.arcadedb.utility.FileUtils;

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.EnumSource;

import java.io.File;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

/**
 * Issue #7347: {@code SourceDiscovery} has never skipped a leading {@code #} or {@code //} comment line, so content
 * sniffing read the comment itself as the first data line.
 * <p>
 * Four separate defects in the two loops that were supposed to do the skipping, each of which alone is enough to
 * make it a no-op:
 * <ol>
 * <li>{@code skipLine()} stopped on the {@code '\n'} it had just read, so the {@code analyzeChar()} call that
 * followed it was handed a {@code '\n'} - a character its dispatch on {@code <}, {@code _} and <code>{</code>
 * cannot match, whatever the line after the comment holds;</li>
 * <li>the {@code #} loop's own condition re-read that same {@code '\n'}, so it ran at most once however many
 * comment lines the source opened with;</li>
 * <li>the {@code //} loop ran after a {@code parser.reset()}, which leaves {@code getCurrentChar()} at {@code 0},
 * so it never ran at all - not even on a source whose very first characters are {@code //};</li>
 * <li>that same {@code reset()} gave back the one line the {@code #} loop had consumed, so the separator scan
 * below it started on the comment.</li>
 * </ol>
 * The reported symptom is the last one: {@code # generated by something} over an N-Triples file made the spaces of
 * the comment the delimiter candidates, the file was sniffed as CSV, and the import died with
 * {@code NumberFormatException: For input string: "generated"}.
 * <p>
 * The first group of tests below asserts the FORMAT a source is recognised as, which is the whole of what this fix
 * changes, without going on to parse it. The second group runs the live {@code Importer.load()} and asserts a
 * commented source imports exactly as the identical source without its comments.
 * <p>
 * The second group covers {@code #} on the delimited-text formats only, and that is not an oversight: the comment
 * prefix this fix skips is handed on intact to whichever format the decision picked, and the only thing skipped
 * there is univocity's single comment character, {@code #}. A commented XML or JSON source, or a
 * {@code //}-commented source of any kind, is now recognised correctly and then fails in the format's own parser.
 * That is issue #7490, whose fix is in the format layer rather than here.
 *
 * @author Roberto Franchini (r.franchini@arcadedata.com)
 */
class Issue7347CommentSkippingTest {

  private static final String TRIPLES = """
      <http://a/s1> <http://a/rel> <http://a/o1> .
      <http://a/s2> <http://a/rel> <http://a/o2> .
      <http://a/s3> <http://a/rel> <http://a/o3> .
      """;

  private static final String SEMICOLON_CSV = """
      id;name;score
      1;first;10
      2;second;20
      """;

  private static final String COMMENT_BLOCK = """
      # generated by something
      # on some date
      """;

  private final List<Path>   sourceFiles   = new ArrayList<>();
  private final List<String> databasePaths = new ArrayList<>();

  @AfterEach
  void cleanup() {
    for (final String path : databasePaths)
      FileUtils.deleteRecursively(new File(path));
    databasePaths.clear();

    for (final Path file : sourceFiles) {
      try {
        Files.deleteIfExists(file);
      } catch (final Exception ignored) {
        // A leftover source file under target/ is not worth failing a green run over.
      }
    }
    sourceFiles.clear();
    TestHelper.checkActiveDatabases();
  }

  // -----------------------------------------------------------------------------------------------------------
  // What the source is RECOGNISED as. Every case pairs a comment block whose own first line sniffs as delimited
  // text - it carries spaces, so the separator scan has candidates - with a data line that sniffs as something
  // else. Before the fix each of them came back as CSV, which is the defect.
  // -----------------------------------------------------------------------------------------------------------

  @Test
  void aHashCommentIsSkippedAndTheNTriplesLineBelowItIsRecognised() throws Exception {
    assertThat(detect("hash-nt", "# generated by something\n" + TRIPLES)).isInstanceOf(RDFImporterFormat.class);
  }

  @Test
  void aSlashCommentIsSkippedAndTheNTriplesLineBelowItIsRecognised() throws Exception {
    assertThat(detect("slash-nt", "// generated by something\n" + TRIPLES)).isInstanceOf(RDFImporterFormat.class);
  }

  /** Defect 2: the {@code #} loop re-tested the newline it had stopped on, so it never reached a second line. */
  @Test
  void aWholeBlockOfHashCommentsIsSkipped() throws Exception {
    assertThat(detect("hash-block-nt", """
        # generated by something
        # on some date
        # by someone
        """ + TRIPLES)).isInstanceOf(RDFImporterFormat.class);
  }

  @Test
  void aWholeBlockOfSlashCommentsIsSkipped() throws Exception {
    assertThat(detect("slash-block-nt", """
        // generated by something
        // on some date
        // by someone
        """ + TRIPLES)).isInstanceOf(RDFImporterFormat.class);
  }

  /** The two markers interleave in real files, and one loop handles both where two never could. */
  @Test
  void hashAndSlashCommentsInterleaveInTheSameBlock() throws Exception {
    assertThat(detect("mixed-block-nt", """
        # generated by something
        // on some date
        # by someone
        // and revised by someone else
        """ + TRIPLES)).isInstanceOf(RDFImporterFormat.class);
  }

  /** Defect 1, on the <code>{</code> arm of the dispatch rather than the {@code <} one. */
  @Test
  void aCommentedJsonSourceIsRecognisedAsJson() throws Exception {
    assertThat(detect("hash-json", "# generated by something\n{\"id\": 1, \"name\": \"first\"}\n"))
        .isInstanceOf(JSONImporterFormat.class);
    assertThat(detect("slash-json", "// generated by something\n{\"id\": 1, \"name\": \"first\"}\n"))
        .isInstanceOf(JSONImporterFormat.class);
  }

  /** Defect 1 again, on the XML arm - the third thing {@code analyzeChar} can return and the third one lost. */
  @Test
  void aCommentedXmlSourceIsRecognisedAsXml() throws Exception {
    assertThat(detect("hash-xml", "# generated by something\n<row id=\"1\"/>\n<row id=\"2\"/>\n"))
        .isInstanceOf(XMLImporterFormat.class);
    assertThat(detect("slash-xml", "// generated by something\n<row id=\"1\"/>\n<row id=\"2\"/>\n"))
        .isInstanceOf(XMLImporterFormat.class);
  }

  /**
   * Defect 4 on a delimited source, where the format class is the same either way and only the delimiter tells the
   * two answers apart. The comment carries spaces and no semicolon, so a scan that read it settles on a space.
   */
  @Test
  void theSeparatorOfACommentedDelimitedSourceIsTakenFromItsFirstDataLine() throws Exception {
    final FormatImporter format = detect("hash-csv", "# generated by something\n" + SEMICOLON_CSV);
    assertThat(format).isInstanceOf(CSVImporterFormat.class);
    assertThat(((CSVImporterFormat) format).getDelimiter())
        .as("the ';' of the header line, not the ' ' of the comment above it")
        .isEqualTo(";");
  }

  @Test
  void theSeparatorOfASlashCommentedDelimitedSourceIsTakenFromItsFirstDataLine() throws Exception {
    final FormatImporter format = detect("slash-csv", "// generated by something\n" + SEMICOLON_CSV);
    assertThat(format).isInstanceOf(CSVImporterFormat.class);
    assertThat(((CSVImporterFormat) format).getDelimiter()).isEqualTo(";");
  }

  /**
   * A lone {@code /} opens no comment - a first column holding a path starts with one - and telling it from
   * {@code //} costs a character the parser cannot push back. It is given back by rewinding, and this is the test
   * that the rewind lands on the right character rather than one past it.
   */
  @Test
  void aFirstLineOpeningWithASingleSlashIsData() throws Exception {
    final FormatImporter format = detect("single-slash-csv", """
        /path/to/a;name;score
        /path/to/b;second;20
        """);
    assertThat(format).isInstanceOf(CSVImporterFormat.class);
    assertThat(((CSVImporterFormat) format).getDelimiter())
        .as("the whole first line was scanned, its leading '/' included")
        .isEqualTo(";");
  }

  /** The uncommented shapes, kept so a regression in them is not read as a regression in the commented ones. */
  @Test
  void uncommentedSourcesAreUnchanged() throws Exception {
    assertThat(detect("plain-nt", TRIPLES)).isInstanceOf(RDFImporterFormat.class);
    assertThat(detect("plain-json", "{\"id\": 1}\n")).isInstanceOf(JSONImporterFormat.class);
    assertThat(detect("plain-xml", "<row id=\"1\"/>\n<row id=\"2\"/>\n")).isInstanceOf(XMLImporterFormat.class);
    assertThat(((CSVImporterFormat) detect("plain-csv", SEMICOLON_CSV)).getDelimiter()).isEqualTo(";");
  }

  /**
   * The comment skipping sits after the per-entity file-type and delimiter resolution, so it is the same code for
   * every entity an import can have. Driven through all four rather than argued, because the four differ in which
   * settings they read on the way in.
   */
  @ParameterizedTest
  @EnumSource(AnalyzedEntity.EntityType.class)
  void everyEntityTypeSkipsTheComment(final AnalyzedEntity.EntityType entityType) throws Exception {
    assertThat(detect("entity-" + entityType, "# generated by something\n" + TRIPLES, entityType))
        .isInstanceOf(RDFImporterFormat.class);
  }

  /** A CRLF-terminated comment block: the line the skip lands on must be the data line, not the '\r' before it. */
  @Test
  void aCommentBlockWithWindowsLineEndingsIsSkipped() throws Exception {
    assertThat(detect("crlf-nt", "# generated by something\r\n// on some date\r\n"
        + TRIPLES.replace("\n", "\r\n"))).isInstanceOf(RDFImporterFormat.class);
  }

  /**
   * The lone-{@code /} rewind again, but with a comment block above it so the rewind target is not zero. The two
   * are different arithmetic and only this one can be off by the length of the block.
   */
  @Test
  void aDataLineOpeningWithASingleSlashBelowACommentBlockIsStillData() throws Exception {
    final FormatImporter format = detect("comment-then-single-slash", COMMENT_BLOCK + """
        /path/to/a;name;score
        /path/to/b;second;20
        """);
    assertThat(format).isInstanceOf(CSVImporterFormat.class);
    assertThat(((CSVImporterFormat) format).getDelimiter())
        .as("the rewind landed on the '/' the data line opens with, not one character past it")
        .isEqualTo(";");
  }

  /**
   * Skipping is bounded: a source that is comments all the way down would otherwise be read end to end just to
   * decide its format. At the bound the skip still works; one line past it sniffing gives up and analyzes line 1,
   * which is what it did before comment skipping worked at all.
   */
  @Test
  void commentSkippingIsBoundedAndTheBoundIsNotOffByOne() throws Exception {
    // Semicolons in the filler and none in the data: the format alone says which of the two lines was sniffed
    final String filler = "#;filler;line\n";

    assertThat(detect("comments-at-the-bound", filler.repeat(10_000) + TRIPLES))
        .as("exactly the bound is still skipped, so the N-Triples line below it is what gets sniffed")
        .isInstanceOf(RDFImporterFormat.class);

    final FormatImporter tooMany = detect("comments-past-the-bound", filler.repeat(10_001) + TRIPLES);
    assertThat(tooMany)
        .as("one line past the bound, sniffing gives up and reads the first comment line as data")
        .isInstanceOf(CSVImporterFormat.class);
    assertThat(((CSVImporterFormat) tooMany).getDelimiter())
        .as("the ';' of the comment, which is the giving-up the bound is there to make explicit")
        .isEqualTo(";");
  }

  /**
   * A blank line between the comment block and the data is ordinary, and skipping the comments but stopping on it
   * would hand the separator scan an empty line - no candidate, so "Cannot determine the file type", which is a
   * worse answer than the wrong-delimiter one this shape used to get.
   */
  @Test
  void aBlankLineBetweenTheCommentBlockAndTheDataIsSkippedToo() throws Exception {
    final FormatImporter format = detect("blank-after-comments", COMMENT_BLOCK + "\n" + SEMICOLON_CSV);
    assertThat(format).isInstanceOf(CSVImporterFormat.class);
    assertThat(((CSVImporterFormat) format).getDelimiter()).isEqualTo(";");

    assertThat(detect("blank-after-comments-nt", COMMENT_BLOCK + "\r\n" + TRIPLES))
        .as("and a blank line with Windows line endings is still a blank line")
        .isInstanceOf(RDFImporterFormat.class);
  }

  /** The same test also covers a source that simply opens with a blank line, which used to fail the scan outright. */
  @Test
  void aLeadingBlankLineIsSkipped() throws Exception {
    assertThat(detect("leading-blank-nt", "\n" + TRIPLES)).isInstanceOf(RDFImporterFormat.class);
    assertThat(((CSVImporterFormat) detect("leading-blank-csv", "\n\n" + SEMICOLON_CSV)).getDelimiter()).isEqualTo(";");
  }

  /**
   * The issue's own closing note: skipping the comments makes {@code analyzeChar}'s second call site live for the
   * first time, and that site hands the user's delimiter to the format it builds. A user's delimiter is never
   * overridden by a detected one (#6946), and this is the path on which that had never once executed.
   */
  @Test
  void anExplicitDelimiterStillWinsOnTheNewlyLiveDispatch() throws Exception {
    final FormatImporter format = detect("explicit-delimiter-nt", "# generated by something\n" + TRIPLES,
        AnalyzedEntity.EntityType.DATABASE, ",");

    assertThat(format).as("the source is still recognised as RDF").isInstanceOf(RDFImporterFormat.class);
    assertThat(((CSVImporterFormat) format).getDelimiter())
        .as("but parsed with the user's ',', not with the ' ' detected between the terms")
        .isEqualTo(",");
  }

  /** A source that is nothing but comments has no data line to sniff, and saying so is the right answer. */
  @Test
  void aSourceThatIsAllCommentsIsStillUndeterminable() {
    assertThatThrownBy(() -> detect("all-comments", """
        # generated by something
        // on some date
        # by someone
        """))
        .isInstanceOf(ImportException.class)
        .hasMessageContaining("Cannot determine the file type");
  }

  // -----------------------------------------------------------------------------------------------------------
  // End to end. '#' on the delimited-text formats only: that is the one combination where the format layer also
  // skips the comment (univocity's single comment character). Everything else arrives at the format layer as
  // data - issue #7490 - which is why the group above asserts detection rather than a completed import.
  // -----------------------------------------------------------------------------------------------------------

  /** The issue's own repro, through {@code -url}. It used to fail with a {@code NumberFormatException}. */
  @Test
  void aHashCommentedNTriplesFileImportsThroughTheUrlRouteAsIfTheCommentWereNotThere() throws Exception {
    final Map<String, Object> commented = importTriples("url-commented", COMMENT_BLOCK + TRIPLES, "-url");
    final Map<String, Object> plain = importTriples("url-plain", TRIPLES, "-url");

    assertThat(commented.get("createdEdges")).isEqualTo(plain.get("createdEdges")).isEqualTo(2L);
    assertThat(commented.get("parsedRecords")).isEqualTo(plain.get("parsedRecords")).isEqualTo(3L);
  }

  /** The other route an RDF source can arrive by, and a different branch of the settings the sniffing reads. */
  @Test
  void aHashCommentedNTriplesFileImportsThroughTheEdgesRouteAsIfTheCommentWereNotThere() throws Exception {
    final Map<String, Object> commented = importTriples("edges-commented", COMMENT_BLOCK + TRIPLES, "-edges");
    final Map<String, Object> plain = importTriples("edges-plain", TRIPLES, "-edges");

    assertThat(commented.get("createdEdges")).isEqualTo(plain.get("createdEdges")).isEqualTo(2L);
    assertThat(commented.get("parsedRecords")).isEqualTo(plain.get("parsedRecords")).isEqualTo(3L);
  }

  /**
   * A delimited source, where the comment did not stop the import but silently changed the delimiter: the spaces
   * of the comment beat the semicolons of the header, so every row arrived as a single column whose name was the
   * whole header line.
   */
  @Test
  void aHashCommentedSemicolonCsvKeepsItsOwnDelimiter() throws Exception {
    assertThat(importDocumentPropertyNames("documents-commented", COMMENT_BLOCK + SEMICOLON_CSV))
        .as("the header came from the first data line and was split on its own ';'")
        .containsExactlyInAnyOrder("id", "name", "score")
        .isEqualTo(importDocumentPropertyNames("documents-plain", SEMICOLON_CSV));
  }

  // -----------------------------------------------------------------------------------------------------------

  private FormatImporter detect(final String name, final String content) throws Exception {
    return detect(name, content, AnalyzedEntity.EntityType.DATABASE);
  }

  /**
   * The format {@code content} is recognised as, and nothing more. {@code SourceDiscovery.getSchema()} would go on
   * to parse the source with that format, which for a commented XML or JSON source, or for a {@code //}-commented
   * one of any kind, fails downstream of everything this issue is about (#7490).
   */
  private FormatImporter detect(final String name, final String content, final AnalyzedEntity.EntityType entityType)
      throws Exception {
    return detect(name, content, entityType, null);
  }

  private FormatImporter detect(final String name, final String content, final AnalyzedEntity.EntityType entityType,
      final String userDelimiter) throws Exception {
    // No .nt/.csv/.json extension: the format has to be decided by sniffing the content, which is the point
    final Path file = sourceFile("issue-7347-" + name + ".txt", content);

    final SourceDiscovery discovery = new SourceDiscovery("file://" + file);
    final ImporterSettings settings = new ImporterSettings();
    settings.url = "file://" + file;
    settings.documents = settings.url;
    settings.vertices = settings.url;
    settings.edges = settings.url;
    if (userDelimiter != null)
      settings.options.put("delimiter", userDelimiter);

    final Source source = discovery.getSource();
    try {
      return discovery.analyzeSourceContent(new Parser(source, 0), entityType, settings, new ConsoleLogger(0));
    } finally {
      source.close();
    }
  }

  private Map<String, Object> importTriples(final String name, final String content, final String route) throws Exception {
    final String databasePath = seedGraphDatabase("issue-7347-" + name);
    final Path file = sourceFile("issue-7347-" + name + ".txt", content);

    return new Importer((route + " file://" + file + " -database " + databasePath
        + " -vertexType Node -edgeType Related").split(" ")).load();
  }

  private List<String> importDocumentPropertyNames(final String name, final String content) throws Exception {
    final String databasePath = "target/databases/issue-7347-" + name;
    databasePaths.add(databasePath);
    FileUtils.deleteRecursively(new File(databasePath));

    final Path file = sourceFile("issue-7347-" + name + ".txt", content);
    new Importer(("-documents file://" + file + " -database " + databasePath
        + " -documentType Doc -forceDatabaseCreate true").split(" ")).load();

    try (final Database database = new DatabaseFactory(databasePath).open()) {
      assertThat(database.countType("Doc", true)).as("both data rows became documents").isEqualTo(2);
      return new ArrayList<>(database.iterateType("Doc", true).next().asDocument(true).getPropertyNames());
    }
  }

  /**
   * The vertex type the RDF format resolves its subjects and objects against, created up front rather than left to
   * the import: an RDF source's analysis registers only the EDGE type. The same setup every other
   * {@code RDFImporterFormat} test does, and nothing this issue is about.
   */
  private String seedGraphDatabase(final String name) {
    final String databasePath = "target/databases/" + name;
    databasePaths.add(databasePath);
    FileUtils.deleteRecursively(new File(databasePath));

    try (final Database database = new DatabaseFactory(databasePath).create()) {
      database.transaction(() -> {
        database.getSchema().createVertexType("Node").createProperty("id", Type.STRING);
        database.getSchema().getType("Node").getOrCreateTypeIndex(Schema.INDEX_TYPE.LSM_TREE, true, new String[] { "id" });
        database.getSchema().createEdgeType("Related");
      });
    }
    return databasePath;
  }

  private Path sourceFile(final String name, final String content) throws Exception {
    final Path file = Path.of("target", name).toAbsolutePath();
    Files.createDirectories(file.getParent());
    Files.writeString(file, content, StandardCharsets.UTF_8);
    sourceFiles.add(file);
    return file;
  }
}
