/*
 * Copyright © 2021-present Arcade Data Ltd (info@arcadedata.com)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * SPDX-FileCopyrightText: 2021-present Arcade Data Ltd (info@arcadedata.com)
 * SPDX-License-Identifier: Apache-2.0
 */
package com.arcadedb.integration.importer;

import com.arcadedb.database.Database;
import com.arcadedb.database.DatabaseFactory;
import com.arcadedb.integration.TestHelper;
import com.arcadedb.schema.Schema;
import com.arcadedb.schema.Type;
import com.arcadedb.utility.FileUtils;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.MethodSource;

import java.io.File;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.util.Map;
import java.util.stream.Stream;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Issue #7347: {@code SourceDiscovery.analyzeText()} opened with two loops meant to skip leading {@code #} and
 * {@code //} comment lines, and between them they skipped nothing. {@code skipLine()} stopped ON the {@code '\n'}
 * that ended the comment, so the loop condition and the {@code analyzeChar()} dispatch inside it both looked at a
 * newline - which matches neither loop's comment character nor any of the dispatch's three - and the
 * {@code parser.reset()} between the two loops handed the consumed line back anyway. A commented source was
 * therefore sniffed ON its comment: the comment's own spaces became the delimiter candidates and a canonical
 * N-Triples file was imported as space-delimited CSV, dying on a {@code NumberFormatException} naming the second
 * word of the comment.
 * <p>
 * The row loops have to agree with the sniffer about what a comment is, or a line the sniffer skipped arrives as
 * data: {@code #} is the univocity parser's own comment character and never reaches {@code parseNext()}, and the
 * leading {@code //} block is dropped by {@code CSVImporterFormat.sourceReader()}.
 *
 * @author Luca Garulli (l.garulli@arcadedata.com)
 */
class Issue7347CommentLinesSniffingTest {

  private static final String TRIPLES = """
      <http://a/s1> <http://a/rel> <http://a/o1> .
      <http://a/s2> <http://a/rel> <http://a/o2> .
      <http://a/s3> <http://a/rel> <http://a/o3> .
      """;

  /**
   * The issue's own repro. Before the fix this did not import three edges instead of two - it did not import at
   * all, and the exception named {@code "generated"}, the second word of the comment.
   */
  @ParameterizedTest(name = "{0}")
  @MethodSource("commentBlocks")
  void anNTriplesSourceImportsThroughItsLeadingCommentBlock(final String name, final String comments) throws Exception {
    final Map<String, Object> report = importRdf(name, comments + TRIPLES);

    assertThat(report)
        .as("a commented source imports exactly like the identical source without the comments")
        .containsEntry("parsedRecords", 3L)
        .containsEntry("createdEdges", 3L);
  }

  static Stream<Arguments> commentBlocks() {
    return Stream.of(//
        Arguments.of("hash", "# generated by something\n"), //
        Arguments.of("hash-block", "# generated by something\n# and a second comment line\n"), //
        Arguments.of("slash", "// generated by something\n"), //
        Arguments.of("slash-block", "// generated by something\n// and a second comment line\n"), //
        Arguments.of("hash-then-slash", "# a '#' block\n// followed by a '//' one\n"), //
        Arguments.of("slash-then-hash", "// a '//' block\n# followed by a '#' one\n"));
  }

  /**
   * The baseline the parameterized cases are measured against, asserted rather than assumed.
   */
  @Test
  void theSameSourceWithoutCommentsIsTheBaseline() throws Exception {
    assertThat(importRdf("plain", TRIPLES)).containsEntry("parsedRecords", 3L).containsEntry("createdEdges", 3L);
  }

  /**
   * The same shape on delimited text, where the comment line used to become the header: every column of the import
   * was then named after a word of the comment, and the first real row was consumed as data for it.
   */
  @ParameterizedTest(name = "{0}")
  @MethodSource("csvCommentBlocks")
  void aCsvSourceKeepsItsRealHeaderThroughALeadingCommentBlock(final String name, final String comments) throws Exception {
    final String databasePath = "target/databases/test-import-7347-csv-" + name;
    final File file = new File("target/importer-7347-csv-" + name + ".csv");
    Files.writeString(file.toPath(), comments + "id,name\n1,Jay\n2,Elon\n", StandardCharsets.UTF_8);

    FileUtils.deleteRecursively(new File(databasePath));
    try {
      new Importer(new String[] { "-documents", "file://" + file.getAbsolutePath(), "-database", databasePath,
          "-documentType", "Person" }).load();

      try (final Database db = new DatabaseFactory(databasePath).open()) {
        assertThat(db.countType("Person", true)).as("the two data rows, and only those").isEqualTo(2);
        assertThat(db.getSchema().getType("Person").getPropertyNames())
            .as("the header is the real header row, not the first line of the comment block")
            .contains("id", "name");
      }
    } finally {
      final DatabaseFactory factory = new DatabaseFactory(databasePath);
      if (factory.exists())
        factory.open().drop();
      file.delete();
      TestHelper.checkActiveDatabases();
    }
  }

  static Stream<Arguments> csvCommentBlocks() {
    return Stream.of(//
        Arguments.of("none", ""), //
        Arguments.of("hash", "# exported on some date\n"), //
        Arguments.of("slash", "// exported on some date\n"), //
        Arguments.of("hash-block", "# exported on some date\n# by someone\n"), //
        Arguments.of("slash-block", "// exported on some date\n// by someone\n"), //
        Arguments.of("hash-then-slash", "# exported on some date\n// by someone\n"));
  }

  /**
   * A single leading {@code /} is not a comment: the second character is PEEKED, so the line keeps its first
   * character. Without the lookahead the {@code /} is read to find out and cannot be given back, and the line
   * arrives one character short - which for the source's FIRST line means a column named {@code id} where the
   * source says {@code /id}.
   * <p>
   * The leading slash has to be on the first line for this to bite: comment detection looks at the head of the
   * source and, once it has seen a line that is not a comment, never looks again.
   */
  @Test
  void aFirstLineOpeningWithASingleSlashIsData() throws Exception {
    final String databasePath = "target/databases/test-import-7347-slash";
    final File file = new File("target/importer-7347-slash.csv");
    Files.writeString(file.toPath(), "/id,name\n/usr/local,first\n/opt,second\n", StandardCharsets.UTF_8);

    FileUtils.deleteRecursively(new File(databasePath));
    try {
      new Importer(new String[] { "-documents", "file://" + file.getAbsolutePath(), "-database", databasePath,
          "-documentType", "Path" }).load();

      try (final Database db = new DatabaseFactory(databasePath).open()) {
        assertThat(db.countType("Path", true)).isEqualTo(2);
        assertThat(db.getSchema().getType("Path").getPropertyNames())
            .as("the '/' that opens the first line is data, so the column is named for the whole of it")
            .contains("/id");
        final Object path = db.query("sql", "select from Path where name = 'first'").nextIfAvailable()
            .getProperty("/id");
        assertThat(path).as("and the row under it is read whole too").isEqualTo("/usr/local");
      }
    } finally {
      final DatabaseFactory factory = new DatabaseFactory(databasePath);
      if (factory.exists())
        factory.open().drop();
      file.delete();
      TestHelper.checkActiveDatabases();
    }
  }

  // -----------------------------------------------------------------------------------------------------------

  /**
   * Imports {@code content} as RDF through the live CLI path. The file is deliberately extension-less: the format
   * has to be decided by sniffing the content, which is the route under test.
   */
  private Map<String, Object> importRdf(final String name, final String content) throws Exception {
    final String databasePath = "target/databases/test-import-7347-" + name;
    final File file = new File("target/importer-7347-" + name + ".txt");
    Files.writeString(file.toPath(), content, StandardCharsets.UTF_8);

    FileUtils.deleteRecursively(new File(databasePath));
    try (final Database seed = new DatabaseFactory(databasePath).create()) {
      seed.transaction(() -> {
        seed.getSchema().createVertexType("Node").createProperty("id", Type.STRING);
        seed.getSchema().getType("Node").getOrCreateTypeIndex(Schema.INDEX_TYPE.LSM_TREE, true, new String[] { "id" });
        seed.getSchema().createEdgeType("Related");
      });
    }

    try {
      final Map<String, Object> report = new Importer(new String[] { "-url", "file://" + file.getAbsolutePath(),
          "-database", databasePath, "-edgeType", "Related" }).load();

      try (final Database db = new DatabaseFactory(databasePath).open()) {
        assertThat((long) db.countType("Related", true)).isEqualTo(report.getOrDefault("createdEdges", 0L));
      }

      return report;
    } finally {
      final DatabaseFactory factory = new DatabaseFactory(databasePath);
      if (factory.exists())
        factory.open().drop();
      file.delete();
      TestHelper.checkActiveDatabases();
    }
  }
}
