name: dev

on:
  push:
    branches:
      - dev 

env:
  GHCR_REGISTRY: ghcr.io
  GHCR_IMAGE: raft-tech/arcadedb
  SSF_REGISTRY: nexus.ssf.sclzdev.net
  SSF_IMAGE: raft/arcadedb
  IB_REGISTRY: registry1.dso.mil
  TAG: dev

jobs:
  dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.GHCR_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Login to SSF Nexus
        uses: docker/login-action@v3
        with:
          registry: ${{ env.SSF_REGISTRY }}
          username: ${{ secrets.SSF_REGISTRY_USER }}
          password: ${{ secrets.SSF_REGISTRY_PASS }}

      - name: Login to Iron Bank
        uses: docker/login-action@v3
        with:
          registry: ${{ env.IB_REGISTRY }}
          username: ${{ secrets.IB_USER }}
          password: ${{ secrets.IB_PASS }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.GHCR_REGISTRY }}/${{ env.GHCR_IMAGE }}:${{ env.TAG }}
            ${{ env.SSF_REGISTRY }}/${{ env.SSF_IMAGE }}:${{ env.TAG }}
