name: release

on:
  workflow_dispatch:
    inputs:
      tag:
        required: true
        type: string
        description: "Tag to be released, without leading 'v' (will be added for git tag but omitted from image tag).  Ex: 1.0.0-rc1, 1.0.0"

env:
  GHCR_REGISTRY: ghcr.io
  GHCR_IMAGE: raft-tech/arcadedb
  SSF_REGISTRY: nexus.ssf.sclzdev.net
  SSF_IMAGE: raft/arcadedb
  IB_REGISTRY: registry1.dso.mil

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.GHCR_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Login to SSF Nexus
        uses: docker/login-action@v3
        with:
          registry: ${{ env.SSF_REGISTRY }}
          username: ${{ secrets.SSF_REGISTRY_USER }}
          password: ${{ secrets.SSF_REGISTRY_PASS }}

      - name: Login to Iron Bank
        uses: docker/login-action@v3
        with:
          registry: ${{ env.IB_REGISTRY }}
          username: ${{ secrets.IB_USER }}
          password: ${{ secrets.IB_PASS }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.GHCR_REGISTRY }}/${{ env.GHCR_IMAGE }}:${{ inputs.tag }}
            ${{ env.SSF_REGISTRY }}/${{ env.SSF_IMAGE }}:${{ inputs.tag }}

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          generateReleaseNotes: true
          tag: v${{ inputs.tag }}