# This workflow is managed by https://github.com/raft-tech/df-gh-templates. All attempts to edit outside of df-gh-templates will be futile.
name: Push tags to SSF

on:
  push:
    tags:
      - '**'

jobs:
  push-to-ssf:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Push To SSF
        run: |
          echo Pushing tag ${GITHUB_REF_NAME} to SSF...
          git config user.name "Raft"
          git config user.email "info@teamraft.com"
          git remote add ssf "https://raft:${{ secrets.SSF_ACCESS_TOKEN }}@${{ secrets.SSF_REPO }}"
          git push ssf ${GITHUB_REF_NAME}