#!/usr/bin/env python3
"""Animated explanations of the Raft protocol as ArcadeDB implements it.

These four diagrams are not about the tests: they describe leader election, log replication, quorum
and partitions, and how the algorithm is wired into this codebase. Every number, entry type,
setting and endpoint on them comes from ha-raft/ and GlobalConfiguration, not from the Raft paper.

Run through build_all.py, which also writes the index page.
"""

from catalog import emit
from workflow_svg import (AMBER, BLUE, GREEN, GREY, PURPLE, RED, Scene, chip, client_to, code_card,
                          cross_stamp, cut, isolated, layout, log_strip, node_state, node_to_client,
                          raft_link, stamp)


# ============================================================================ leader election
def leader_election():
    layout(3)
    scenes = [
        Scene(
            step="every node starts as a FOLLOWER",
            caption="A node that hears nothing from a leader for its election timeout assumes there is none.",
            detail="arcadedb.ha.electionTimeoutMin=5000 / electionTimeoutMax=10000 (ms) - Ratis picks a random value in that range per node",
            dur=3.8,
            body=[code_card(92, ["the timeout is RANDOMISED per node:",
                                 "  5000ms .. 10000ms",
                                 "so the three nodes rarely time out",
                                 "together, and a split vote is rare"],
                            title="why a range, not a value", color=AMBER)]
                 + [node_state(i, "FOLLOWER", BLUE, "term 0 - no leader") for i in range(3)],
        ),
        Scene(
            step="one timer fires first",
            caption="The first node to time out increments the term, becomes a CANDIDATE and votes for itself.",
            detail="term 0 -> term 1;  votes for itself = 1 of 3;  a majority of 3 is 2",
            dur=3.4,
            body=[node_state(0, "FOLLOWER", BLUE, "term 0"),
                  node_state(1, "CANDIDATE", AMBER, "term 1 - votes 1/3"),
                  node_state(2, "FOLLOWER", BLUE, "term 0"),
                  chip(352, 96, "election timer fired on arcadedb-1", AMBER, w=286)],
        ),
        Scene(
            step="RequestVote to every peer",
            caption="The candidate asks the other nodes for their vote, over the Raft port, not over HTTP.",
            detail="RequestVote(term, candidateId, lastLogIndex, lastLogTerm)  -  Ratis gRPC on arcadedb.ha.raft.port = 2434",
            dur=3.6,
            body=[node_state(1, "CANDIDATE", AMBER, "term 1"),
                  node_state(0, "FOLLOWER", BLUE, "deciding"), node_state(2, "FOLLOWER", BLUE, "deciding"),
                  raft_link(1, 0, "RequestVote(term 1)", AMBER),
                  raft_link(1, 2, "RequestVote(term 1)", AMBER)],
        ),
        Scene(
            step="one vote per peer per term",
            caption="A peer grants its single vote only if the candidate's log is at least as up to date as its own.",
            detail="a candidate whose lastLogIndex/lastLogTerm is behind is refused, which is what keeps committed entries safe",
            dur=4.0,
            body=[code_card(92, ["granted when:",
                                 "  candidate term >= own term",
                                 "  AND no vote cast this term",
                                 "  AND candidate log is not behind"],
                            title="the vote rule", color=GREEN),
                  node_state(1, "CANDIDATE", GREEN, "votes 3/3 >= 2"),
                  node_state(0, "VOTED", GREEN, "granted"), node_state(2, "VOTED", GREEN, "granted"),
                  raft_link(0, 1, "vote", GREEN), raft_link(2, 1, "vote", GREEN)],
        ),
        Scene(
            step="majority reached -> LEADER",
            caption="Two of three is a majority, so the candidate becomes leader for term 1 - and only for term 1.",
            detail="exactly one leader can exist per term: two majorities of the same cluster always share at least one node",
            dur=3.6,
            body=[node_state(1, "LEADER", GREEN, "term 1"),
                  node_state(0, "FOLLOWER", BLUE, "term 1"), node_state(2, "FOLLOWER", BLUE, "term 1"),
                  stamp(1, "elected")],
        ),
        Scene(
            step="heartbeats keep the term alive",
            caption="The leader sends empty AppendEntries on a timer; every one of them resets the followers' election timers.",
            detail="the heartbeat interval is well under electionTimeoutMin, so a healthy leader is never voted out",
            dur=3.6,
            body=[node_state(1, "LEADER", GREEN, "heartbeating"),
                  node_state(0, "FOLLOWER", BLUE, "timer reset"), node_state(2, "FOLLOWER", BLUE, "timer reset"),
                  raft_link(1, 0, "AppendEntries(empty)", GREEN),
                  raft_link(1, 2, "AppendEntries(empty)", GREEN)],
        ),
        Scene(
            step="a split vote just ends the term",
            caption="If two candidates start at once nobody reaches a majority; the term ends with no leader and the timers re-randomise.",
            detail="no leader is ever elected by a minority, so a split vote costs one election round, never correctness",
            dur=4.0,
            body=[code_card(92, ["term 2: two candidates, 1 vote each",
                                 "  -> no majority, no leader",
                                 "term 3: new random timeouts,",
                                 "  one node almost always wins"],
                            title="split vote", color=RED),
                  node_state(0, "CANDIDATE", AMBER, "term 2 - 1 vote"),
                  node_state(1, "FOLLOWER", GREY, "already voted"),
                  node_state(2, "CANDIDATE", AMBER, "term 2 - 1 vote"),
                  cross_stamp(0, "no majority", AMBER), cross_stamp(2, "no majority", AMBER)],
        ),
        Scene(
            step="what ArcadeDB exposes",
            caption="Election state is observable and steerable from outside the cluster, which is what the HA tests drive.",
            detail='GET /api/v1/cluster -> {"isLeader":..., "leaderHttpAddress":...}   POST /api/v1/cluster/transfer-leader   POST .../step-down',
            dur=4.0,
            body=[code_card(92, ['GET  /api/v1/cluster',
                                 '       "isLeader": true',
                                 '       "leaderHttpAddress": ...',
                                 'POST /api/v1/cluster/transfer-leader',
                                 'POST /api/v1/cluster/step-down'],
                            title="operator surface", color=PURPLE),
                  node_state(1, "LEADER", GREEN, "isLeader:true"),
                  node_state(0, "FOLLOWER", BLUE, "knows the leader"),
                  node_state(2, "FOLLOWER", BLUE, "knows the leader"),
                  client_to(1, "GET /api/v1/cluster", BLUE, packet=True)],
        ),
    ]
    emit("raft-leader-election", "Raft - leader election",
         "Randomised timeouts, one vote per term, majority wins - and why a split vote is harmless",
         scenes, "How a term gets a leader, why exactly one, and what a split vote costs.",
         group="Raft protocol", source="ha-raft/ - RaftPropertiesBuilder, GetClusterHandler")


# ============================================================================ log replication
def log_replication():
    layout(3)
    scenes = [
        Scene(
            step="a write reaches the leader",
            caption="Only the leader may append. A write that lands on a follower is forwarded to the leader first.",
            detail="ServerIsNotTheLeaderException carries the leader address; LeaderCommandForwarder replays the command there",
            dur=3.6,
            body=[node_state(0, "LEADER", GREEN, "appending"),
                  node_state(1, "FOLLOWER", BLUE), node_state(2, "FOLLOWER", BLUE),
                  log_strip(0, ["1", "1", "1", "2", "2"], committed=5),
                  log_strip(1, ["1", "1", "1", "2", "2"], committed=5),
                  log_strip(2, ["1", "1", "1", "2", "2"], committed=5),
                  client_to(0, "CREATE VERTEX ...", GREEN, packet=True)],
        ),
        Scene(
            step="what is appended is an ENTRY",
            caption="The SQL never crosses the wire. The transaction is encoded as a typed Raft log entry.",
            detail="RaftLogEntryCodec encodes one of 8 types; the type byte is the whole version contract, so decoders must stay in step",
            dur=4.2,
            body=[code_card(92, ["TX_ENTRY                 (1)",
                                 "SCHEMA_ENTRY             (2)",
                                 "INSTALL_DATABASE_ENTRY   (3)",
                                 "DROP_DATABASE_ENTRY      (4)",
                                 "SECURITY_USERS_ENTRY     (5)",
                                 "BOOTSTRAP_FINGERPRINT    (6)",
                                 "SECURITY_GROUPS_ENTRY    (7)",
                                 "SECURITY_API_TOKENS      (8)"],
                            title="RaftLogEntryType", color=PURPLE),
                  node_state(0, "LEADER", GREEN, "index 6, term 2 - uncommitted"),
                  log_strip(0, ["1", "1", "1", "2", "2", "2"], committed=5),
                  node_state(1, "FOLLOWER", BLUE), node_state(2, "FOLLOWER", BLUE),
                  log_strip(1, ["1", "1", "1", "2", "2"], committed=5),
                  log_strip(2, ["1", "1", "1", "2", "2"], committed=5)],
        ),
        Scene(
            step="AppendEntries to every follower",
            caption="Each message carries the position the entry must follow, so a follower can refuse a log that does not line up.",
            detail="AppendEntries(term, prevLogIndex, prevLogTerm, entries[], leaderCommit) - a mismatch is rejected and retried further back",
            dur=3.8,
            body=[node_state(0, "LEADER", GREEN, "index 6 pending"),
                  log_strip(0, ["1", "1", "1", "2", "2", "2"], committed=5),
                  node_state(1, "FOLLOWER", AMBER, "appending 6"),
                  log_strip(1, ["1", "1", "1", "2", "2", "2"], committed=5),
                  node_state(2, "FOLLOWER", AMBER, "appending 6"),
                  log_strip(2, ["1", "1", "1", "2", "2", "2"], committed=5),
                  raft_link(0, 1, "AppendEntries(prev 5)", AMBER), raft_link(1, 2, "")],
        ),
        Scene(
            step="a majority acks -> committed",
            caption="The entry commits as soon as a majority has written it to disk. The third node is not waited for.",
            detail="arcadedb.ha.quorum = majority (2 of 3) or all; quorum=all trades availability for every peer having the entry",
            dur=4.0,
            body=[code_card(92, ["majority: leader + 1 of 2 peers",
                                 "  -> a slow peer cannot stall writes",
                                 "all: every peer must ack",
                                 "  -> one slow peer stalls everything"],
                            title="arcadedb.ha.quorum", color=AMBER),
                  node_state(0, "LEADER", GREEN, "commitIndex 6"),
                  log_strip(0, ["1", "1", "1", "2", "2", "2"], committed=6),
                  node_state(1, "FOLLOWER", GREEN, "acked"),
                  log_strip(1, ["1", "1", "1", "2", "2", "2"], committed=5),
                  node_state(2, "FOLLOWER", BLUE, "still writing"),
                  log_strip(2, ["1", "1", "1", "2", "2", "2"], committed=5),
                  raft_link(1, 0, "ack", GREEN)],
        ),
        Scene(
            step="apply, then answer the client",
            caption="Committed is not enough: the entry is decoded and applied to the database before the client hears anything.",
            detail="ArcadeStateMachine.applyTransaction decodes the TX_ENTRY and applies it - the state machine IS the ArcadeDB database",
            dur=3.8,
            body=[node_state(0, "LEADER", GREEN, "applied to the database"),
                  log_strip(0, ["1", "1", "1", "2", "2", "2"], committed=6),
                  node_state(1, "FOLLOWER", BLUE), node_state(2, "FOLLOWER", BLUE),
                  log_strip(1, ["1", "1", "1", "2", "2", "2"], committed=5),
                  log_strip(2, ["1", "1", "1", "2", "2", "2"], committed=5),
                  node_to_client(0, "COMMIT ok", GREEN, packet=True), stamp(0, "applied")],
        ),
        Scene(
            step="followers learn the commit next round",
            caption="The commit position rides along on the following AppendEntries, so followers apply one round trip later.",
            detail="leaderCommit is piggybacked on the next AppendEntries - which is why a follower read can lag a leader read",
            dur=3.6,
            body=[node_state(0, "LEADER", GREEN, "commitIndex 6"),
                  log_strip(0, ["1", "1", "1", "2", "2", "2"], committed=6),
                  node_state(1, "FOLLOWER", GREEN, "applied 6"),
                  log_strip(1, ["1", "1", "1", "2", "2", "2"], committed=6),
                  node_state(2, "FOLLOWER", GREEN, "applied 6"),
                  log_strip(2, ["1", "1", "1", "2", "2", "2"], committed=6),
                  raft_link(0, 1, "leaderCommit=6", GREEN), raft_link(1, 2, "")],
        ),
        Scene(
            step="a lagging follower is backfilled",
            caption="The leader keeps a next-index per follower: on a mismatch it walks back and resends until the logs agree.",
            detail="a peer too far behind for the retained log is handed the database instead, as an INSTALL_DATABASE_ENTRY",
            dur=4.0,
            body=[node_state(0, "LEADER", GREEN, "nextIndex[2] = 3"),
                  log_strip(0, ["1", "1", "1", "2", "2", "2"], committed=6),
                  node_state(1, "FOLLOWER", GREEN, "in step"),
                  log_strip(1, ["1", "1", "1", "2", "2", "2"], committed=6),
                  node_state(2, "FOLLOWER", AMBER, "behind - backfilling"),
                  log_strip(2, ["1", "1"], committed=2),
                  raft_link(0, 2, "resend from index 3", AMBER)],
        ),
        Scene(
            step="entries travel in batches",
            caption="Under load the entries are grouped rather than sent one by one, and oversized ones are refused up front.",
            detail="RaftGroupCommitter batches up to 500 entries per dispatch; an entry over raft.grpc.message.size.max is rejected synchronously",
            dur=3.8,
            body=[code_card(92, ["RaftTransactionBroker",
                                 "  maxBatchSize   500",
                                 "  maxQueueSize   10000",
                                 "  offerTimeout   100ms",
                                 "oversized entry -> rejected before",
                                 "  it can corrupt the sliding window"],
                            title="batching", color=PURPLE),
                  node_state(0, "LEADER", GREEN, "batched dispatch"),
                  node_state(1, "FOLLOWER", BLUE), node_state(2, "FOLLOWER", BLUE),
                  raft_link(0, 1, "up to 500 entries"), raft_link(1, 2, "")],
        ),
    ]
    emit("raft-log-replication", "Raft - log replication",
         "From a client write to an applied transaction: append, replicate, commit on a majority, apply",
         scenes, "The write path: what is appended, when it commits, and when the client is answered.",
         group="Raft protocol",
         source="ha-raft/ - RaftLogEntryType, RaftTransactionBroker, ArcadeStateMachine")


# ============================================================================ quorum and partitions
def quorum_and_partitions():
    layout(3)
    scenes = [
        Scene(
            step="majority = 2 of 3",
            caption="Every decision - electing a leader, committing an entry - needs a majority, and majorities always overlap.",
            detail="any two majorities of the same cluster share at least one node, and that node remembers the newer term",
            dur=3.8,
            body=[code_card(92, ["3 nodes -> majority 2   (survives 1)",
                                 "5 nodes -> majority 3   (survives 2)",
                                 "2 nodes -> majority 2   (survives 0)",
                                 "an even cluster buys nothing"],
                            title="why odd sizes", color=AMBER)]
                 + [node_state(0, "LEADER", GREEN, "term 1")]
                 + [node_state(i, "FOLLOWER", BLUE, "term 1") for i in (1, 2)],
        ),
        Scene(
            step="the network splits 2 + 1",
            caption="The leader ends up alone on one side. It does not know that yet - it only knows its acks stopped arriving.",
            detail="in the e2e-ha suite this is a real Docker network disconnect, not a simulated one",
            dur=3.6,
            body=[isolated(0, "term 1, alone"), cut(0, 1, "partition"),
                  node_state(1, "FOLLOWER", AMBER, "majority side"),
                  node_state(2, "FOLLOWER", AMBER, "majority side")],
        ),
        Scene(
            step="the isolated leader steps down",
            caption="A leader that cannot reach a majority cannot commit anything, so it gives up leadership by itself.",
            detail="entries it had appended but not committed stay uncommitted - no client was ever told they succeeded",
            dur=4.0,
            body=[isolated(0, "stepped down"),
                  log_strip(0, ["1", "1", "1", "1"], committed=3),
                  cut(0, 1, ""),
                  node_state(1, "FOLLOWER", AMBER, "election timer firing"),
                  node_state(2, "FOLLOWER", AMBER, "election timer firing"),
                  log_strip(1, ["1", "1", "1"], committed=3), log_strip(2, ["1", "1", "1"], committed=3)],
        ),
        Scene(
            step="the majority elects in a NEW term",
            caption="The two connected nodes hold a majority, so they can elect - and they do it in a higher term.",
            detail="term 1 -> term 2; the old leader is still on term 1 and will be corrected the moment it is reachable again",
            dur=3.6,
            body=[isolated(0, "stale: term 1"), cut(0, 1, ""),
                  node_state(1, "LEADER", GREEN, "term 2"), node_state(2, "FOLLOWER", BLUE, "term 2"),
                  raft_link(1, 2, "term 2 heartbeat", GREEN)],
        ),
        Scene(
            step="writes continue on the majority",
            caption="Two acks out of three is still a majority, so the connected side keeps committing normally.",
            detail="the cluster tolerates the loss of one node out of three - that is exactly what majority quorum buys",
            dur=3.6,
            body=[isolated(0, "frozen at index 3"),
                  log_strip(0, ["1", "1", "1", "1"], committed=3), cut(0, 1, ""),
                  node_state(1, "LEADER", GREEN, "commitIndex 5"),
                  log_strip(1, ["1", "1", "1", "2", "2"], committed=5),
                  node_state(2, "FOLLOWER", GREEN, "acked"),
                  log_strip(2, ["1", "1", "1", "2", "2"], committed=5),
                  client_to(1, "writes keep committing", GREEN, packet=True)],
        ),
        Scene(
            step="the minority refuses to write",
            caption="On the isolated side nothing can commit, so a write there fails or times out instead of diverging.",
            detail="this is the whole point: a minority that cannot commit cannot produce a second, conflicting history",
            dur=3.8,
            body=[isolated(0, "no quorum"), cross_stamp(0, "rejected"),
                  client_to(0, "INSERT ...", RED, packet=True), cut(0, 1, ""),
                  node_state(1, "LEADER", GREEN), node_state(2, "FOLLOWER", BLUE)],
        ),
        Scene(
            step="heal: the stale tail is truncated",
            caption="On rejoin the old leader sees the higher term, drops the entries it never committed and takes the leader's.",
            detail="index 4 on the old leader was never acknowledged to any client, so discarding it loses nothing that was promised",
            dur=4.2,
            body=[code_card(92, ["old leader had:  1 1 1 [1]",
                                 "new leader has:  1 1 1  2  2",
                                 "               ^ uncommitted",
                                 "-> truncate the tail, replay 4 and 5"],
                            title="log reconciliation", color=PURPLE),
                  node_state(0, "REJOINING", PURPLE, "truncate then replay"),
                  log_strip(0, ["1", "1", "1", "2", "2"], committed=3),
                  node_state(1, "LEADER", GREEN), node_state(2, "FOLLOWER", BLUE),
                  log_strip(1, ["1", "1", "1", "2", "2"], committed=5),
                  log_strip(2, ["1", "1", "1", "2", "2"], committed=5),
                  raft_link(1, 0, "catch-up", PURPLE)],
        ),
        Scene(
            step="one history, always",
            caption="Split-brain is not detected and repaired here - the algorithm makes a second history impossible to create.",
            detail="one leader per term + majority overlap + commit-before-answer: a committed entry survives every later election",
            dur=4.0,
            body=[node_state(i, "CONVERGED", GREEN, "same log, same data") for i in range(3)]
                 + [log_strip(i, ["1", "1", "1", "2", "2"], committed=5) for i in range(3)]
                 + [stamp(i, "identical") for i in range(3)],
        ),
    ]
    emit("raft-quorum-and-partitions", "Raft - quorum, partitions and split-brain",
         "Why a minority can never write, and why healing is truncate-and-replay rather than merge",
         scenes, "What a majority buys, what happens on each side of a partition, and how a rejoin resolves.",
         group="Raft protocol", source="ha-raft/ - Quorum, RaftHAServer; exercised by SplitBrainIT")


# ============================================================================ Raft inside ArcadeDB
def raft_in_arcadedb():
    layout(3)
    scenes = [
        Scene(
            step="two ports, two jobs",
            caption="Clients speak HTTP on 2480. Consensus is a separate Ratis gRPC channel on 2434, peer to peer.",
            detail="arcadedb.ha.serverList = host:raftPort:httpPort,...  -  arcadedb.ha.raft.port = 2434 by default",
            dur=3.8,
            body=[code_card(92, ["2480  HTTP - clients, Studio, tests",
                                 "2434  Ratis gRPC - consensus only",
                                 "",
                                 "-Darcadedb.ha.enabled=true",
                                 "-Darcadedb.ha.serverList=...",
                                 "-Darcadedb.ha.quorum=majority"],
                            title="wiring", color=AMBER)]
                 + [node_state(0, "LEADER", GREEN)] + [node_state(i, "FOLLOWER", BLUE) for i in (1, 2)]
                 + [raft_link(0, 1, "2434"), raft_link(1, 2, "")],
        ),
        Scene(
            step="the state machine IS the database",
            caption="Raft does not replicate pages or a separate store: applying an entry runs the transaction on the local database.",
            detail="ArcadeStateMachine.applyTransaction decodes the entry and applies it; the snapshot is the set of database files on disk",
            dur=4.0,
            body=[code_card(92, ["Raft log entry",
                                 "  -> RaftLogEntryCodec.decode",
                                 "  -> ArcadeStateMachine.apply",
                                 "  -> the ArcadeDB database itself",
                                 "snapshot = the database files",
                                 "  (no .md5 companion, by design)"],
                            title="apply path", color=PURPLE),
                  node_state(0, "LEADER", GREEN, "applied"), node_state(1, "FOLLOWER", GREEN, "applied"),
                  node_state(2, "FOLLOWER", GREEN, "applied")],
        ),
        Scene(
            step="what gets replicated",
            caption="Data is only one of the eight things that travel the log; users, groups and API tokens travel it too.",
            detail="SECURITY_USERS_ENTRY / SECURITY_GROUPS_ENTRY / SECURITY_API_TOKENS_ENTRY are node-scoped: no database name, global position only",
            dur=4.2,
            body=[code_card(92, ["TX_ENTRY               transactions",
                                 "SCHEMA_ENTRY           types, indexes",
                                 "INSTALL_DATABASE_ENTRY whole database",
                                 "DROP_DATABASE_ENTRY    removal",
                                 "SECURITY_USERS_ENTRY   users file",
                                 "SECURITY_GROUPS_ENTRY  groups file",
                                 "SECURITY_API_TOKENS    token hashes",
                                 "BOOTSTRAP_FINGERPRINT  first entry"],
                            title="RaftLogEntryType", color=PURPLE),
                  node_state(0, "LEADER", GREEN), node_state(1, "FOLLOWER", BLUE),
                  node_state(2, "FOLLOWER", BLUE), raft_link(0, 1, ""), raft_link(1, 2, "")],
        ),
        Scene(
            step="writes are leader-only, and forwarded",
            caption="A write on a follower is not refused outright: it names the leader, and the command is replayed there.",
            detail="ServerIsNotTheLeaderException.getLeaderAddress() - LeaderCommandForwarder - a null leader address is the retryable case",
            dur=4.0,
            body=[node_state(1, "FOLLOWER", AMBER, "not the leader"),
                  node_state(0, "LEADER", GREEN, "executes"), node_state(2, "FOLLOWER", BLUE),
                  client_to(1, "POST /api/v1/command", AMBER, packet=True),
                  raft_link(1, 0, "forward to leader", AMBER)],
        ),
        Scene(
            step="a new or far-behind peer",
            caption="A peer that cannot be caught up from the retained log is given the whole database instead.",
            detail="INSTALL_DATABASE_ENTRY; arcadedb.ha.logSegmentSize=64MB bounds what the log retains before a snapshot takes over",
            dur=3.8,
            body=[node_state(0, "LEADER", GREEN, "ships the database"),
                  node_state(1, "FOLLOWER", GREEN, "in step"),
                  node_state(2, "JOINING", PURPLE, "INSTALL_DATABASE_ENTRY"),
                  log_strip(0, ["1", "1", "2", "2", "2"], committed=5),
                  log_strip(1, ["1", "1", "2", "2", "2"], committed=5),
                  log_strip(2, [], committed=0),
                  raft_link(0, 2, "install database", PURPLE)],
        ),
        Scene(
            step="reads, and where they are served",
            caption="A follower read can trail the leader by a round trip, so the tests poll instead of reading once.",
            detail="leader lease ratio 0.9 for leader reads; followers apply on the next AppendEntries, which is the lag every HA test awaits",
            dur=3.8,
            body=[node_state(0, "LEADER", GREEN, "commitIndex 9"),
                  node_state(1, "FOLLOWER", AMBER, "applied 8"), node_state(2, "FOLLOWER", AMBER, "applied 8"),
                  log_strip(0, ["1", "2", "2", "2", "2"], committed=5),
                  log_strip(1, ["1", "2", "2", "2", "2"], committed=4),
                  log_strip(2, ["1", "2", "2", "2", "2"], committed=4),
                  client_to(1, "SELECT count(*)", BLUE, packet=True)],
        ),
        Scene(
            step="the knobs that matter",
            caption="Five settings decide how this cluster behaves under stress; the defaults favour resilience over fast failover.",
            detail="quorum - electionTimeoutMin/Max - logSegmentSize - rpc request timeout 10s - staging timeout 30s",
            dur=4.2,
            body=[code_card(92, ["ha.quorum             majority | all",
                                 "ha.electionTimeoutMin 5000 ms",
                                 "ha.electionTimeoutMax 10000 ms",
                                 "ha.logSegmentSize     64MB",
                                 "rpc request timeout   10 s",
                                 "staging timeout       30 s",
                                 "leader lease ratio    0.9"],
                            title="GlobalConfiguration", color=AMBER)]
                 + [node_state(i, "TUNED", GREEN) for i in range(3)],
        ),
    ]
    emit("raft-in-arcadedb", "Raft - how ArcadeDB wires it up",
         "Ports, entry types, the state machine, follower forwarding, snapshots and the tuning knobs",
         scenes, "The mapping from the algorithm to this codebase: what runs where, and on which setting.",
         group="Raft protocol", source="ha-raft/, GlobalConfiguration, server/.../LeaderCommandForwarder")


ALL = (leader_election, log_replication, quorum_and_partitions, raft_in_arcadedb)
